### PR TITLE
[SofaKernel] Add a "sofa_add_module" in SofaMacro.cmake

### PR DESCRIPTION
**Pull request by damienmarchal**
As in SofaNG we are calling the activable/deactivable 'plugins' modules
I added a macro that have the right "name" instead of hijacking the
sofa_add_plugin's one.

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
Thanks for this PR @damienmarchal 
Just a question that may end into a debate: do we continue differentiating "plugins" and "modules"? It induced only misunderstanding during STC#5.

**Comment by damienmarchal** [comment]
Now fundamentally to me they are the same. Module is probably a more adequate name than plugin as it convey the idea of 'modul'arization while plug'in' convey they idea of internal/external. Having a consortium supported Module compared to an external one doesn't change the nature (it is still a module).

But honestly I don't really care...what really matter to me is to make more and more of them :)

**Comment by guparan** [comment]
Agreed, I don't really care either. I think we have to stick to one name and I prefer Module for the reason you just mentioned. I just don't want to confuse historical users who think "module = what we have now = not really modular = bad".

**Comment by epernod** [comment]
so external plugins are introducing new modules into Sofa? 🦄

**Comment by damienmarchal** [comment]
@guparan job's done.

**Comment by damienmarchal** [comment]
So this PR is merged...but the CI configuration needs to be updated to rename PLUGIN_XXX into MODULE_XXX this is the cause of the failing test on the CI.

**Pull request merged**
