### PR TITLE
[SofaGuiQt] Introduce expand/collapse buttons

### PR DESCRIPTION
**Pull request by alxbilger**
Suggestion of buttons to expand all or collapse all in the scene graph view.

https://user-images.githubusercontent.com/10572752/132018160-1192c958-1300-4ef3-b92a-3f0a0c10ae29.mp4

Note that the same feature already exists by right clicking on the root node.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
That's cool 👍 especially with scenes with dozens of falling things.... (and penalty contacts 😆)
Just a thought: the 'collapse all' will obviously always show only root, maybe the 'collapse all' should show the first node (i.e root) still expanded ?

**Comment by alxbilger** [comment]
> That's cool 👍 especially with scenes with dozens of falling things.... (and penalty contacts 😆)
> Just a thought: the 'collapse all' will obviously always show only root, maybe the 'collapse all' should show the first node (i.e root) still expanded ?

Yes, I also thought about it. I decided to keep it simple, but I don't mind doing your suggestion.

**Comment by fredroy** [comment]
> 
> 
> > That's cool 👍 especially with scenes with dozens of falling things.... (and penalty contacts 😆)
> > Just a thought: the 'collapse all' will obviously always show only root, maybe the 'collapse all' should show the first node (i.e root) still expanded ?
> 
> Yes, I also thought about it. I decided to keep it simple, but I don't mind doing your suggestion.

Lets see what the other guys will say

**Comment by alxbilger** [comment]
Here is the behavior suggested by @fredroy 


https://user-images.githubusercontent.com/10572752/132175335-469bbd54-4e93-454f-bb24-0c1e2128513f.mp4

**Comment by guparan** [comment]
Cool feature, +1 to have the root node always expanded.

**Review by guparan — APPROVED** [review]

**Pull request merged**
