### PR TITLE
[SofaSimulationCore] Remove unused class VisitorAsync

### PR DESCRIPTION
**Pull request by alxbilger**
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
I dont know why this file is in SofaSimulationCore, but if you look at the content of this header file, you can see
```c++
#include <MultiThreading/config.h>
...
#include <MultiThreading/Tasks.h>
```

it would mean that the Multithreading plugin should be enabled **before** SofaSimulationCore (obviously impossible), so this code would never be usable as it is. 🧐

**Comment by alxbilger** [comment]
> I dont know why this file is in SofaSimulationCore, but if you look at the content of this header file, you can see
> 
> ```c++
> #include <MultiThreading/config.h>
> ...
> #include <MultiThreading/Tasks.h>
> ```
> 
> it would mean that the Multithreading plugin should be enabled **before** SofaSimulationCore (obviously impossible), so this code would never be usable as it is. monocle_face

How can it compile?

**Comment by alxbilger** [comment]
> Have you checked @alxbilger that it is well unused in InSimo ISSOFA released by @fjourdes ?

I just checked, and the file does not exist on the repository.

**Comment by fredroy** [comment]
> 
> 
> > I dont know why this file is in SofaSimulationCore, but if you look at the content of this header file, you can see
> > ```c++
> > #include <MultiThreading/config.h>
> > ...
> > #include <MultiThreading/Tasks.h>
> > ```
> > 
> > 
> > it would mean that the Multithreading plugin should be enabled **before** SofaSimulationCore (obviously impossible), so this code would never be usable as it is. monocle_face
> 
> How can it compile?

If it is not included, it is not compiled.
My guess is that this file was included in Multithreading, or is included in a private plugin using Multithreading (thus enabling  `-I/path/to/Multithreading`)

**Comment by fspadoni** [comment]
This is a base class to implement an asynchronous visitor. 
I have implemented a few in the MultiCoreGpu plugin. 

This file was originally in the Multithreading plugin and then move to Sofa simulation core with the task scheduler.
The class depends only on the Visitor and Task class definition.

The include files with the MultiThreading path are wrong, they should be:

#include <sofa/config.h> // for SOFA_SIMULATION_CORE_API 
#include <sofa/simulation/TaskScheduler.h> // for the definition of Task

If you want to remove it from Sofa Simulation Core  it's ok, I will keep a copy in the plugin.

**Review by fspadoni — COMMENTED** [review]
This is a base class to implement an asynchronous visitor.
I have implemented a few in the MultiCoreGpu plugin.

This file was originally in the Multithreading plugin and then move to Sofa simulation core with the task scheduler.
The class depends only on the Visitor and Task class definition.

The include files with the MultiThreading path are wrong, they should be:

#include <sofa/config.h> // for SOFA_SIMULATION_CORE_API
#include <sofa/simulation/TaskScheduler.h> // for the definition of Task

If you want to remove it from Sofa Simulation Core it's ok, I will keep a copy in the plugin.

**Comment by alxbilger** [comment]
I see two options:
- We remove it and @fspadoni copies it in his plugin
- We keep it (or move it in the multithreadplugin). In this case, we need to have a reason to keep it, such as an example of an implementation of such a visitor. @fspadoni Would you like to explain how it works? I may have some interests to implement some myself.

**Comment by fredroy** [comment]
It has been some time now that this PR is stalled.
As far as I know, there is still no implementation of VisitorAsync, so IMO it should be deleted.
(and it is not really complicated to replicate if needed, it just inherits Visitor and adds a "Status" member)

**Comment by alxbilger** [comment]
> It has been some time now that this PR is stalled.
> As far as I know, there is still no implementation of VisitorAsync, so IMO it should be deleted.
> (and it is not really complicated to replicate if needed, it just inherits Visitor and adds a "Status" member)

I agree. Manipulation of a `status` is understood. Setting to "to review".

**Comment by fredroy** [comment]
`mac_clang-3.5_options — Build OK. FIXME: 43 units ` 🥴
in case: [ci-build][force-full-build]

**Comment by fredroy** [comment]
I suppose this was a quirk from the CI.

**Pull request merged**
