### PR TITLE
[SofaVolumetricData] Split the module into multiple plugin

### PR DESCRIPTION
**Pull request by damienmarchal**
This PR is here to support Issue #388 

This is the beginning of a work on cleaning and modularizing the
SofaVolumetricData.
The module is splitted in two Plugins.
- SofaDistanceGrid
- SofaImplicitField

A third plugin act as a transitional package SofaVolumetricData guiding
other developpers on the change they have to do in order to have their
code compiling again.

CHANGELOG.txt:
 - SofaVolumetricData was strongly refactored and splitted in two plugins SofaDistanceGrid and SofaImplicitField. Please report to sofa-dev any broken behavior.  A transitional plugin SofaVolumetricData is provided for one year. 

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hi guys...

OMG no one answered in 5 days !! 
Still 2 days and it will be merged as-is. 
Are you sure :) ?

**Comment by untereiner** [comment]
Is there a removal date for the third plugin ? (To force developers to make the changes)

**Comment by damienmarchal** [comment]
@untereiner thank for the question. 

What I would dream of some kind of consensus about how we proceed and I'm totally open for suggestions.

I see the goods of making smooth transition in a code base (user of the code base will praise you) and the bad of maintaining the transitional package.

On my side... I would say: 
- we remove the transitional packages after 1 year and at each Sofa release we make their use more and more "verbose".

**Comment by guparan** [comment]
Hi @damienmarchal, thank you for this massive work.
117 changed files in 1 commit is not easy to review so this may take a while to be merged but be sure we (I included) are going to check it out.
About the deprecation policy, I agree with your proposal of 1 year transition + highlights in releases.
I'm curious to see this PR [ci-build]'ed [with-scene-tests] 😉

**Comment by untereiner** [comment]
I agree with you but to avoid calendar issues I would speak rather in term of release: Two releases for the transition and remove at the third one.

**Comment by damienmarchal** [comment]
Thanks you all the for the feedback. 

I appologize about the reviewing work. And you are right, this one is very hard. We can also be a bit more "lazy" in the reviewing, merging it, write a good changelog a tell people to send feedback if something goes wrong. 

I'm pushing this one because we have a nice other PR waiting and this one have new cool features (from distance field modeling to tetrahedral meshing). 

EDIT: actually moving from module to plugins without refactoring is much easier...but well... I was not able to prevent me.

**Comment by damienmarchal** [comment]
Not ready ?

**Comment by guparan** [comment]
Let's see if it **really** builds ;-)

**Comment by damienmarchal** [comment]
Thanks for spotting that... can you do the same for the others plugnization ?

**Comment by guparan** [comment]
I did, the plugins are activated by default in the others.

**Comment by damienmarchal** [comment]
[ci-build] to take into account the last merge.

**Comment by damienmarchal** [comment]
[ci-build]

**Pull request merged**
