### PR TITLE
[SofaNG] Setup Engine

### PR DESCRIPTION
**Pull request by fredroy**
#1527 

based on:
- #2805 (for TriangleOctree in helper)

Deprecates _**SofaEngine**_, **_SofaGeneralEngine_** and **_SofaMiscEngine_**

Create various submodules according to their nature (way of sorting is mine, matter of discussion)
~~- **Data**: manipulating Data (aka core::objectmodel::Data<>)~~
~~- **Geometry**: various algo on geometry ops~~
~~- **Math**: apply math functions~~
~~- **Mesh**: generate or modify meshes~~
~~- **Rigid**: rigid utilities (i.e vec+quat types)~~
~~- **ROI**: select Region Of Interest~~
~~- **Transform**: transformations ops (matrices)~~

- **Analyze** : inputs contains some kind of measurement/value
- **Generate** : create data from inputs
- **Select** : filter inputs
- **Transform**: apply some function on inputs

https://github.com/sofa-framework/sofa/issues/2906

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Review by guparan — APPROVED** [review]
CMake part is green :+1:

**Comment by epernod** [comment]
> What about:
> 
>     * **DataAnalysis**: regrouping both Math and Geometry
> 
>     * **DataProcessing**: old name Data
> 
>     * **Mesh**: generate or modify meshes
> 
>     * **Rigid**: rigid utilities (i.e vec+quat types)
> 
>     * **Select**: select Region Of Interest
> 
>     * **Transform**: transformations ops (matrices)
> 
> 
> what do you think about this @epernod @alxbilger?

My suggestion:

* **Analysis** : Output = new Data "information" from Mesh and/or other Data
* **Generate** : Output = new Data from Mesh and/or other Data
* **Modify**: Output = modified a/several input Data
* **Rigid**: Output = rigid utilities (i.e vec+quat types)
* **Select**: Output = Data from select Region Of Interest
* **Transform**: Output = transformations ops (matrices)

**Comment by alxbilger** [comment]
One rule for consistency could be to chose a verb (or a noun) for all modules.

If a verb:

- Analyze
- Generate
- Modify
- Select
- Transform

If a noun:

- Analysis
- Generation
- Modification
- Selection
- Transformation
 
In any case, I think it would make sense to dispatch the content of Rigid into the other modules. It seems we want to organize by functionality, not by types.
I still need to think about Analysis/Generation vs DataAnalysis/DataProcessing. I am not yet convinced.

**Comment by epernod** [comment]
could you describe what is what? I don't see the diff between Analyse and Process and then what do you put in Mesh ? 
Is a subsetEngine creating dofs in Mesh? or Process ?

**Pull request merged**
