### PR TITLE
[LinearSolver.Direct] Parallelization of H A^-1 H^T in SparseLDLSolver

### PR DESCRIPTION
**Pull request by alxbilger**
The parallelized function is `SparseLDLSolver::doAddJMInvJtLocal`.

# Benchmarks

I rely on the scene provided by @bakpaul with light changes: https://gist.github.com/alxbilger/1b82b1488a2741be845d7d9da18c25e5. The SOFA timer to focus on is `Get Compliance` as it is the deepest timer in the hierarchy containing the `doAddJMInvJtLocal` function.

- Master branch (commit df49f3a754264489b14db69b38862a5b45d57168)

```
100 iterations done in 12.9731 s ( 7.70827 FPS).
```

```
 LEVEL   START    NUM      MIN     MAX   MEAN     DEV    TOTAL  PERCENT ID
   5      15.41    1       0.01  121.72   98.03   20.57   98.03   77.48 .....Get Compliance
```

- This PR (without parallelization)

The benchmark should be similar to the master branch

```
100 iterations done in 13.1572 s ( 7.6004 FPS).
```

```
 LEVEL   START    NUM      MIN     MAX   MEAN     DEV    TOTAL  PERCENT ID
   5      16.31    1       0.01  134.76   98.34   22.21   98.34   76.54 .....Get Compliance
```

- This PR (with parallelization)

```
100 iterations done in 5.94345 s ( 16.8253 FPS).
```

```
 LEVEL   START    NUM      MIN     MAX   MEAN     DEV    TOTAL  PERCENT ID
   5      15.76    1       0.01   30.62   26.85    5.55   26.85   47.91 .....Get Compliance
```

On my machine there is a nice speedup of x3.66 on the `Get Compliance` timer, and x2.18 in terms of global FPS.

# Additional Benchmarks

I wanted to make sure that the usual solve of SparseLDLSolver did not regress in terms of performances. I benchmarked `examples/Component/LinearSolver/Direct/FEMBAR_SparseLDLSolver.scn` on 10000 steps.

- Master branch (commit df49f3a754264489b14db69b38862a5b45d57168)

```
10000 iterations done in 28.2657 s ( 353.785 FPS).
```

- This PR

```
10000 iterations done in 28.3223 s ( 353.078 FPS).
```

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
I did some benches on TorusFall.scn🤐
master 
`5000 iterations done in 41.7616 s ( 119.727 FPS)`

pr       
 `5000 iterations done in 36.09 s ( 138.543 FPS)`

**Comment by alxbilger** [comment]
> I did some benches on TorusFall.scn🤐 master `5000 iterations done in 41.7616 s ( 119.727 FPS)`
> 
> pr `5000 iterations done in 36.09 s ( 138.543 FPS)`

Thank you for the benchmark. In the PR, did you activated the parallel computation? I would like to know that there is no performance regression in the single-threaded implementation.
I did not parallelize the third loop: I would like to test that to speed up more.

**Comment by bakpaul** [comment]
So I've made a benchmark on my side too, it is a rectangular beam falling on a cube. Little specs  : 

ezgif com-video-to-gif

Beam : 
 - 625 points
 - 2304 tetra

Constraints : 
 - 276 constraints
 - 200 CG iteration
 
-----
Synchronous inverse product
- BuildSystem step took a mean of 66.25 ms (75% of the time step)
- Simulation fps : ~ 11 FPS

----
Asynchronous inverse product
- BuildSystem step took a mean of 49.81 ms (69% of the time step)
- Simulation fps : ~ 14 FPS

**Review by bakpaul — DISMISSED** [review]

**Comment by bakpaul** [comment]
Ok, I've just realized that the strange tetra crushing that appears on the top of the beam doesn't appear before your pr (on the commit from which your branch has been created). So there might be something wrong going on... Do you want my scene to do some tests on your side ?

**Comment by alxbilger** [comment]
@bakpaul thanks for the benchmark. Yes, I would like your scene to investigate both the behavior and the performances (I am a bit disappointed so far).

**Comment by bakpaul** [comment]
Here it is ! 
[625-Falling-Lagrangian.zip](https://github.com/sofa-framework/sofa/files/12036504/625-Falling-Lagrangian.zip)

**Comment by alxbilger** [comment]
@bakpaul I used your scene for benchmarks and updated the PR description accordingly. However, I don't observe the artefact your mention, even when going step by step.

**Comment by bakpaul** [comment]
Nice job, it is indeed faster on my computer too. 
For the artifact, it still appears at the top of the beam on the contact, at step 46 (see image) event with your modified scene (I saw only the ShewchukPCGLinearSolver that was different).  

image

Would be great to know what are the difference between our compilation configurations.

**Comment by alxbilger** [comment]
@bakpaul Strange, I checked again (with and without parallelization) and I don't have the artefact you have. `ShewchukPCGLinearSolver` is not a difference because you use an alias of it (`PCGLinearSolver`). In the benchmark I translated the beam to measure mainly the contacts and skip the falling part. But I still don't see the artefact when I remove the translation.
@fredroy @hugtalbot would you like to test this branch with the scene provided by @bakpaul ?

**Comment by fredroy** [comment]
> @bakpaul Strange, I checked again (with and without parallelization) and I don't have the artefact you have. `ShewchukPCGLinearSolver` is not a difference because you use an alias of it (`PCGLinearSolver`). In the benchmark I translated the beam to measure mainly the contacts and skip the falling part. But I still don't see the artefact when I remove the translation. @fredroy @hugtalbot would you like to test this branch with the scene provided by @bakpaul ?

I tested the scene of @bakpaul and I get the same artefact on ubuntu 23.04/gcc12.2
EDIT: and I dont have the artefact on Windows/MSVC2022 😶‍🌫️

**Comment by alxbilger** [comment]
@fredroy Thanks for trying.
So the regression depends on the OS. Great!
I added a regression test for this scene in https://github.com/sofa-framework/sofa/pull/4055

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by alxbilger** [comment]
Some notes:

- It was extremely hard to understand why L^T was used in the first step of the solve, and not L. I hope it's clearer now with the comment I added. Anyway, it requires to have the knowledge of the CSR and CSC formats, and how they relates to the transpose.
- I would like to use C++20 `std::span` in some functions such as `solveLowerUnitriangularSystemCSR`.
- Regression tests threshold are usually set to 1e-4. IMO it's not enough to capture errors happening on a single DOF because it's an average

**Review by bakpaul — APPROVED** [review]

**Review by fredroy — APPROVED** [review]

**Pull request merged**
