### PR TITLE
[SofaKernel] Vector serialization

### PR DESCRIPTION
**Pull request by thomas-lemaire**
[SofaKernel] re-open PR #330 

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
I'm still thinking about the getValueString issue. 
If implementing a specific getValueStringAsPythonSyntax() in SofaKernel is not easy because of the operator<< what do you think about an intermediate step consisting in implementing the python serialization syntax in the Binding_Data of the repr function in the following way:
```cpp
static PyObject * Data_repr(PyObject *self)
{
    BaseData* data = get_basedata( self );
    return PyObject_Repr(getDataValuePython(data));
}
```
It is very few lines of code and it would make the whole PR nearly 'non breaking' 
(as repr was just undefined now) ? 

EDIT: fixed the code.

**Comment by thomas-lemaire** [comment]
Good idea @damienmarchal ! (with the code fix ;-)

It has the overhead to copy once more the data in once more conversion data -> PyObject, but it does not look horrible.

**Comment by thomas-lemaire** [comment]
_Side note_

Let's see it the other way around ;-)
With a [,] serialization of Sofa datatype, there would not any need for the complexity of GetDataValuePython() and just taking the data string representation and creating the PyObject out of it would be enough.

Anyway this is not the good way to go since the data is actually copied and does not offer data modification on the python side.

**Comment by damienmarchal** [comment]
Right for the overhead, my target was clearly to minimize the developement time because this is a very scarce resource.

The good news I see is that if the function a performance limiting we are still able to improve it a lot (by order of magnitude).

**Comment by damienmarchal** [comment]
@hugtalbot I already give my opinion in #PR 330. 
And it is: please don't merge it now and give us time to find a smoother way of managing the API change. 

I re-explain the situation: 
This PR add Python like serialization&deserialization 
- The de-serialization preserve backward compatibility. 
- The serizaliation is changing the behavior on how Sofa is serializing data. The new behavior is implemented in place of the old one and thus is breaking the API. This API exists since years in Sofa. It will thus cost time to fix & update external code-base. The situation is made worse because the API breaks is silent (ie the code will compile but not work as expected)

Breaking the API is not mandatory to implement a python like serialization. So I strongly recommend to implement a non breaking solution as a transition... 
Alternative solutions I have in mind are:
 - a cheap10 lines python approach based on repr (see previous response) (A PR with this would change two time less files and be a non breaking change).
 - a full C++ version in the form of a getStringValueAsPython  
 - a full C++ version in the form of an extra parameter to getStringValue
 - ...other ?

**Pull request closed without merging**
