### PR TITLE
[extlibs/gtest] Update gtest  & clean the CMakeLists.txt

### PR DESCRIPTION
**Pull request by damienmarchal**
This shouldn't break anything and is a first step toward the slighgly more ambitious pr #601 

CHANGELOG:
- update gtest from their master (version 1.9: sha1 447d58b4ee8ea96b4757a5bb5f0b3be75af6c2a1)
- update the CMakeLists so that they correctly export the needed -D to be used as a shared library
- Fix the problem of missing GTEST_API_ operator<< gtest by implementing the function in TestMessageHandler_test instead of gtest.

NB:  A better FIX for the GTEST_API_ operator<< could be to make submit PR to gtest but I have no more time left. 
______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
@guparan Here it is the failure on windows are removed. 
Do we go fast path ? [ci-build][with-scene-tests]

**Comment by guparan** [comment]
Could you just specify the new GTest version in the description please?

**Comment by damienmarchal** [comment]
The current version we now have in extlibs 1.9...but actually the update didn't needed anychange so I assume that with the old gtest we had the fix would have work equally well.

**Comment by damienmarchal** [comment]
Yes... with the CImgPlugin fix you are doing the windows platform will be green :)

**Comment by guparan** [comment]
Cool, green is my favorite color ;-)

**Comment by damienmarchal** [comment]
@hugtalbot @bcarrez can you make a quick review of this...so that we can work fast merge for this one.

**Comment by guparan** [comment]
I just added a commit to clean the custom `EXPECT_ATLEASE_ONE_NONFATAL_FAILURE` macro. Tell me if I'm wrong but it would better be a macro expecting MORE than 1 failure to clearly distinct from `EXPECT_NONFATAL_FAILURE` (GTest one).

**Comment by damienmarchal** [comment]
Well I don't really see the cleaning there just renaming to a name I find more ambiguous because EXPECT_NONFATAL_FAILURES is much less 'distinct' fom EXPECT_NONFATAL_FAILURE  than the previous one... but maybe I miss-understood the commit.

Anyway if you think this is better I don't really care as this is a macro to "test" the testing framework so of very limited usage.

**Comment by guparan** [comment]
The most important is just the `if (results.size() <= 1)` in `HasFailures`.
About the name, I started by fixing the typo "ATLEASE" and finnaly changed the whole thing but it's not very important we can go back to "ATLEAST" if you prefer :-)

EDIT: Actually we can't since the new behavior is to pass only if there is MORE than 1 failure.

**Comment by damienmarchal** [comment]
@guparan +for the typo and for the careful reading. Thanks.
With the new condition the macro is now equivalent to something like EXPECT_ATLEAST_TWO_FAILURES ? But as you can see in the dashboard this is  not what the tests are expecting as there is now one new test failure reported in the dashboard.

**Comment by guparan** [comment]
Ok I didn't take the time to run the tests myself so I wanted to see the Dashboard. Is it actually possible to have more than 1 failure in a test ? Both "ATLEAST_ONE" and "ATLEAST_TWO" seem useless there.

**Comment by guparan** [comment]
Just tried it and using `EXPECT_NONFATAL_FAILURE` works well on Windows.
Why did you create `EXPECT_ATLEAST_TWO_FAILURES` in the first place @damienmarchal ?

**Comment by damienmarchal** [comment]
Because defaultTestBehavior was supposed to fail three time and not one (this is not working with EXPECT_NONFATAL_FAILURE). The fact it actually fails only once has been changed later by changing the default behavior in BaseTest. The rational for this change was that for a transitional period of time it was decided to avoid warnings messages to generate a test failure so that the dashboard is less "red" and the tests was not refactor since this decision. 
 
EDIT: I didn't made EXPECT_ATLEAST_TWO_FAILURES...only ONE.

**Comment by guparan** [comment]
Not sure to understand. Shall we safely remove this custom macro (ONE **and** TWO versions) or do we want to keep it for a transitional period?
If we keep it, I have to redo my commit.

**Comment by guparan** [comment]
I just replaced my commit by a simple typo fix.
Thank you for the clear explanations @damienmarchal

**Pull request merged**
