### PR TITLE
[SofaEulerianFluid] Pluginizing the module

### PR DESCRIPTION
**Pull request by damienmarchal**
There is not a lot of contribution to make plugin from the old sofa modules. 
Here is one. 

The general idea is that it should decrease compilation time and memory footprint of sofa. 

This is my contribution to the issue stated by @hugtalbot  in 
https://github.com/sofa-framework/sofa/issues/346

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
Do not forget to add `RequiredPlugin` in Fluid2D and Fluid3D example scenes. 😉

**Comment by guparan** [comment]
Not sure 71a7aa2f60bc8afe6e13518f2dd358307320aa8b and 91b858706c146c41610ef05a96ac9fd3acab82e2 are needed here.

**Comment by damienmarchal** [comment]
Oups... I have not idea where it come from... probably started from the  wrong branch???? 
I assume I now have to make a clean branch and cherry-pick the right commit ?

**Comment by guparan** [comment]
It's done ;-)

**Comment by damienmarchal** [comment]
Can we pass this one to ready ?

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
@guparan this one should be ready as you fixed it :)

**Pull request merged**
