### PR TITLE
[SofaKernel] FIX FileRepository on Windows

### LINKED ISSUE #17: FileRepository and special characters
FileRepository needs to be checked and fixed.

It does not work for sure in some situations, e.g. if a sofa install is copied in a path containing accents on windows, FileRepository does not find the files.

Note I have not go any further, and everything needs to be investigated.
I did not test with the distributed, precompiled package. I did not test on linux...

### PR DESCRIPTION
**Pull request by guparan**
ADD dependencies to boost::filesystem and boost::locale

Fixes #17

### CODE REVIEW

**Comment by damienmarchal** [comment]
I cannot test myself on window but:
    - the tests is not failing anymore. 
    - no new tests are failing. 
    - I don't think the new boost dependency is a problem.  

I let @matthieu-nesme  (who made the issue #17) to make the final decision.

**Comment by matthieu-nesme** [comment]
Great! and the fix is impressively concise.
The only concern could be the dynamic link to boost libraries, I guess it is mandatory?

**Comment by guparan** [comment]
Not all of them, we could replace `${Boost_LIBRARIES}` with `${Boost_SYSTEM_LIBRARY} ${Boost_FILESYSTEM_LIBRARY} ${Boost_LOCALE_LIBRARY}`

**Comment by bcarrez** [comment]
(edited)
No problem for me since boost is now mandatory. 
As seen in the main CMakeLists.txt, line 158:
`find_package(Boost REQUIRED)`

Does the job, no test broken, fixes one failing test: green light for me.

**Comment by damienmarchal** [comment]
Can I merge it ?

**Comment by guparan** [comment]
Nope, I have to search first for any header only improvement.

**Comment by guparan** [comment]
So there is [no header-only way](http://www.boost.org/doc/libs/1_62_0/more/getting_started/unix-variants.html#header-only-libraries) to use boost::filesystem and boost::locale.
The only improvement I see would be to move the `find_package(Boost COMPONENTS filesystem locale QUIET)` to SofaHelper.
Don't know if this would be a real improvement though 😕

**Comment by damienmarchal** [comment]
So we merge it this way ?

**Comment by guparan** [comment]
No objections so I vote yes :)

**Pull request merged**
