### PR TITLE
[SofaMiscForceField] Fix MeshMatrixMass init and topologicalChanges

### PR DESCRIPTION
**Pull request by epernod**
Depends/include PR #2192 and PR #2191

[ci-depends-on https://github.com/sofa-framework/regression/pull/14]

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build]

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
2 regression tests are failing : 
 - Regression_test/StateRegression_test.sceneTest/EulerExplicitSolver
 - Regression_test/StateRegression_test.sceneTest/EulerImplicitSolver

Could it be that the references of these 2 scenes are bogus themselves ? (thus needing to update them?)

**Comment by epernod** [comment]
> 
> 
> 2 regression tests are failing :
> 
>     * Regression_test/StateRegression_test.sceneTest/EulerExplicitSolver
> 
>     * Regression_test/StateRegression_test.sceneTest/EulerImplicitSolver
> 
> 
> Could it be that the references of these 2 scenes are bogus themselves ? (thus needing to update them?)

yes probably as both scenes are using MeshMatrixMass. I'll try to check the values to see if it is a regression or a fix... 🤞

**Comment by epernod** [comment]
Yes, the references scenes are wrong. Both scenes have a totalMass input of 15 but summing all vertices and edges mass values give:
- On master: 0.14867
- On this branch: 15

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Pull request merged**
