### PR TITLE
[SofaKernel] Clean DefaultPipeline (BREAKING)

### PR DESCRIPTION
**Pull request by damienmarchal**
This PR is focused on cleaning the DefaultPipeline component.

It contains:
   - several tests with one of them is an OpenIssue (the depth parameter that is not checked nor generate warnings)
   - fix of the data field names that are not following the sofa guidelines, this may break code
     directly using these attributes. 
   - change some of the docstring to be more helpful
  
It also depend on the following other pull-requests: 
    - https://github.com/sofa-framework/sofa/pull/101

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by guparan** [comment]
Thanks for the PR and sorry for the delay.

FileMonitor.updateNoChange_test is failing (regression) on MacOS: https://ci.inria.fr/sofa-ci/job/mac_clang-3.4_options/4289/testReport/(root)/FileMonitor/updateNoChange_test
Do you know why?

**Comment by damienmarchal** [comment]
@guparan 
I don't think this is a regression. 

This test fails on MacOS from time to time because of a timeout. It was described by @bcarrez  somewhere (i'm searching:)).

We should propably re-create a new issue because this is something that need to be fixed.

EDIT: I didn't find where it was described by bruno so let me describe it better. The problem is related to the fact that the test are using a delay to wait the OS to notify the application a file has changed...but on MacOS the delay is not big enough causing the test to  fail.

**Comment by damienmarchal** [comment]
voila

**Pull request merged**
