### PR TITLE
[SofaTest] Add Backtrace::autodump to all tests

### PR DESCRIPTION
**Pull request by damienmarchal**
As requested by @matthieu-nesme in https://github.com/sofa-framework/sofa/issues/149
(but what is the xml ?) 

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings nor unit test failures.
- [x] does not break existing scenes.
- [x] does not break API compatibility.
- [x] has been reviewed and agreed to be transitional.
- [x] is more than 1 week old.

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by matthieu-nesme** [comment]
@damienmarchal, I am talking about these xml files:
```
[ RUN      ] BilateralInteractionConstraint_test/1.attributesTests
bash: line 1:  2202 Segmentation fault      build/bin/SofaConstraint_test --gtest_output=xml:build/tests/SofaConstraint_test/report.xml 2>&1
```

(copied from https://ci.inria.fr/sofa-ci/job/centos_clang-3.4_options/262/console)

But I think @guparan is working on the subject.

**Comment by guparan** [comment]
Did not have time to start this yet. 😢 
As discussed last wednesday, the idea would be to simply `cat` the output of crashed tests during the `print-summary()` phases (for unit tests and scene tests). So only scripts stuff.

**Comment by damienmarchal** [comment]
So let Guillaume finish...
But is the autodump stuff useful or not ?
If Backtrace is not installed by default how a failing test will print anything ?

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Pull request merged**
