### PR TITLE
[GUI.Qt] Add clickable link to online documentation

### PR DESCRIPTION
**Pull request by alxbilger**
image

TODO:
- [ ] Add this feature in SofaImGui

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by damienmarchal** [comment]
Definitely a must have. 
(for future work... rendering the docstring as markdown)

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by bakpaul** [comment]
That's a great feature with the growing community, thank's !

**Comment by alxbilger** [comment]
Now the URL is generated automatically based on the namespace and class name. And interestingly, the website is able to find the right page even if the URL is not exact. For example:

- https://www.sofa-framework.org/community/doc/components/animationloop/freemotionanimationloop is converted automatically to https://www.sofa-framework.org/community/doc/components/animationloops/freemotionanimationloop/
- https://www.sofa-framework.org/community/doc/components/collision/detection/algorithm/bruteforcebroadphase -> https://www.sofa-framework.org/community/doc/components/collisions/broadphases/bruteforcebroadphase/
- https://www.sofa-framework.org/community/doc/components/collision/detection/intersection/minproximityintersection -> https://www.sofa-framework.org/community/doc/components/collisions/intersectiondetections/minproximityintersection/

**Review by bakpaul — APPROVED** [review]

**Pull request merged**
