### PR TITLE
[STC#5][STC#6] Coding sprints

### PR DESCRIPTION
**Pull request by guparan**
Finally, here it is! 

Please edit this description to complete the changelog:
- Remove all SOFA_EXTERN_TEMPLATE
- Remove all #ifdef SOFA_DEV
- Remove PS3 and XBOX code
- Remove SOFA_SUPPORT_MAPPED_MASS
- Remove into weird #pragma once 
- Remove commented code.
- Replace conditionally compiled code.
Eg: 
```cpp
#ifndef NDEBUG
            serr << "Loop for computing connexity has reach end." << sendl;
#endif
```
By a systematically compiled version
```cpp
if (CHECK_TOPOLOGY)
       msg_error() << "Loop for computing connexity has reach end.";
```
- Remove all code using #define SOFA_NEW_HEXA
- Add macro CHECK_TOPOLOGY (see above) to turn all topology component in verbose mode
- FIX several dll macro missing in Base and Mesh collisions

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by damienmarchal** [comment]
@EulalieCoevoet , @VannesteFelix can one of you test this branch with our plugins SoftRobots & MOR on the big's felix machine to see if this work well ?

**Comment by VannesteFelix** [comment]
On the BFM it compile perfectly!
There are just some errors related to update & doUpdate function that will need to be fixed but this doesn't come from this MR. (@EulalieCoevoet)
I also test some examples and still no error for me, so it should be ok.

**Comment by damienmarchal** [comment]
Thank you Felix for the report. I think we should merge this code quickly because branch divergence is increasing and start to cost to much time.

NB: It took me some time to understand why you were refering to BFM (TV?) :)

**Comment by epernod** [comment]
[ci-build][with-scene-tests][with-regression-tests]

**Comment by damienmarchal** [comment]
I don't know

**Pull request merged**
