### PR TITLE
[SofaBaseLinearSolver] CGLinearSolver must call super init() to check required Data

### PR DESCRIPTION
**Pull request by alxbilger**
`CGLinearSolver::init()` did not call `init()` of its base class. The result is that the check of the required Data, which is in `BaseObject::init()`, is never called. `CGLinearSolver` has required Data, therefore the error never triggered when one of the required Data was not set.

[ci-depends-on https://github.com/sofa-framework/Compliant/pull/4]
[ci-depends-on https://github.com/sofa-framework/Flexible/pull/3]
[ci-depends-on https://github.com/sofa-framework/SofaPython/pull/2]
[ci-depends-on https://github.com/sofa-framework/SofaPython3/pull/211]

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by alxbilger** [comment]
> Cool @alxbilger so if there is Required data and in `Inherit::init()` is called then the error gets not triggered. Correct? We should investigate other components with this Required feature.

That's the opposite: to catch an error if a required Data is missing, the component must call `Inherit::init()`.

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
few CUDA scenes are failing, all with the messages `[ERROR] [CGLinearSolver(cGLinearSolver1)] Required data "threshold" has not been set. (Current value is 1e-05)` so I suppose these scenes must be updated too

**Comment by alxbilger** [comment]
> few CUDA scenes are failing, all with the messages `[ERROR] [CGLinearSolver(cGLinearSolver1)] Required data "threshold" has not been set. (Current value is 1e-05)` so I suppose these scenes must be updated too

@fredroy ok I did not catch them. Thanks

**Comment by guparan** [comment]
CI looks happy, I'll merge the dependent PRs :+1:

**Comment by guparan** [comment]
[ci-build][with-all-tests]

**Comment by alxbilger** [comment]
I think we're done. Can you check again @guparan @fredroy ?

**Review by guparan — APPROVED** [review]

**Pull request merged**
