### PR TITLE
Renaming the HeartBeatEvent with one called IdleEvent

### PR DESCRIPTION
**Pull request by damienmarchal**
Hi all,

Following the discussion here: 
https://github.com/sofa-framework/sofa/commit/d5241217967853394d103f2f06b2f8359dbde6f9#commitcomment-19827546

This pull-request rename the HeartBeatEvent with one called IdleEvent. 
As HeartBeatEvent was introduced last week I don't expect it will break sofa 
in anyway. 

DM.

### CODE REVIEW

**Comment by guparan** [comment]
[ci-build]

**Comment by guparan** [comment]
[ci-build]

**Comment by guparan** [comment]
[ci-build]

**Comment by matthieu-nesme** [comment]
OK for the IdleEvent renaming.

But this PR is also adding GLSLFileListener.
Is FileListener already pushed? I cannot see it.

Can you give us a work on the extra cost when the shader do not change?

**Comment by damienmarchal** [comment]
Hi Mathieu,

Thank you for the feedback... the GLSL stuff is a mistake... I didn't knew that pull-request was for a branch and not for a specific commit. So i continued to to work in this branch (I will not do the same mistake in the future). 

Now to answer your question...the overhead is near zero. 
- The GLSLListener is triggered by the file FileMonitor. 
- FileMonitor is using the event based "select" system API and is not actively 'polling' the files. AFAIK this is the most efficient way to monitor files. 
- If your application don't call FileMonitor::update(0) then this cost nothing.

Currently only runSofa is calling FileMonitor::update(0) when started with the -i (for interactive) command line option. 

So the different scenarios is:
- runSofa -i & changing the file (this cost the reload of the shader)
- runSofa -i & not changing the file (this cost calling the select system call) 
- runSofa as usual...this cost nothing. 

I hope I answer you question and yet again, thank you for your feedback on this PR. 

Now about FileListener... it is part of the FileMonitor API that is already in Sofa.  

DM.

**Comment by damienmarchal** [comment]
So I reverted the GLSL shader and will make a separated pull request for it.

**Pull request merged**
