### PR TITLE
[SofaHelper] GLSL: Load shader source code from a standard string

### PR DESCRIPTION
**Pull request by fredroy**
It is useful to be able to load shaders directly from a std::string as it allows us to not need filesystem management. Consequently "fixed" shaders like shadows (or normal rendering when OpenGL Core profile will come) will be directly integrated into the libs (no more share/shaders directory to locate/find/read)

[needed to solve  #142  ]

Checklist to merge this PR: 
  - [x] succeed on each compilation setup on the CI 
  - [x] does not generates new warnings or test failure 
  - [x] does not seems to break existing scenes.
  - [x] does not seems to break API compatibility.  
  - [x] cleans stuff
  - [x] have tests on the introduced features. 
  - [x] is now 1 week old and no one send a 'no go' comment.

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hi Fred,

Thank for this PR. 

+1 for the cleannig
+1 for the tests 
Maybe it should be told in the PR description. 

I'm surprise by the C++ code in the test.glsl file. I don't think this is a good naming convention because it is really hard to understand that the content of the .gsl file is actually c++. So I suggest to rename the file with a more classical .cpp (or .cppglsl if you really want something no .cpp).  

There is some place in the code that introduces new std::cerr. Can you please update to use the dmsg_* API 

I will try the PR to see if it does not interfere with the livecoding features.

**Comment by fredroy** [comment]
Thanks for your fast answer !

I will rename the extension of the C++/shader file.
As a side note, this file is using [Raw String Litterals](https://en.wikipedia.org/wiki/C++11#New_string_literals), as it allowed me to directly copy-paste content of the shader file into a string (without escaping end-of-line, quotes, etc.)
I will also remove the std::cerr/cout to use the msg_ api.
Finally, one test is failing on MacOS (only!) about filemonitor because of my commits and I dont really know why ?? (FileMonitor.updateNoChange_test)

**Comment by damienmarchal** [comment]
@fredroy I really like the Raw String Litteral, 

The FileMonitor test is probably not related with your PR, It is an old bug that was soved last week...but maybe it wasn't  @bcarrez  ...

**Comment by damienmarchal** [comment]
This PR: 
  - [ ] succeed on each compilation setup on the CI (because of buggy CI, we have to restart the build)
  - [ ] does not generates new warnings or test failure (waiting the CI)
  - [x] does not seems to break existing scenes.
  - [x] does not seems to break API compatibility.  
  - [x] clean stuff
  - [x] have tests on the introduced features. 
  - [ ] is now 1 week old and no one send a 'no go' comment. 

I will redo a build on the CI this week so that every item in my checklist can be checked :)

**Comment by damienmarchal** [comment]
[ci-build]

**Pull request merged**
