### PR TITLE
[SofaSimulationGraph] Reading links fail when owner is invalid

### PR DESCRIPTION
**Pull request by alxbilger**
This is an attempt to fix the failing unit tests about the links.
Only 2 changes of behavior:

1. The function `read` returns `false` and don't do anything in case the link has no owner.
2. Paths not starting with '@' are not added to the list of links

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
Just looking at the code, it is fine for me but I don't have the whole overview of Link API. I know that @damienmarchal was reworking the BaseLink API. If you could give a look ?

**Comment by alxbilger** [comment]
> Just looking at the code, it is fine for me but I don't have the whole overview of Link API. I know that @damienmarchal was reworking the BaseLink API. If you could give a look ?

Yes, I kind of noticed that it required a rework, but my goal was just to fix a failing unit test.

**Comment by fredroy** [comment]
> 
> 
> > Just looking at the code, it is fine for me but I don't have the whole overview of Link API. I know that @damienmarchal was reworking the BaseLink API. If you could give a look ?
> 
> Yes, I kind of noticed that it required a rework, but my goal was just to fix a failing unit test.

I recall that this test was failing on purpose actually (to keep track to work on the Link)
@damienmarchal ?

**Comment by alxbilger** [comment]
> > > Just looking at the code, it is fine for me but I don't have the whole overview of Link API. I know that @damienmarchal was reworking the BaseLink API. If you could give a look ?
> > 
> > 
> > Yes, I kind of noticed that it required a rework, but my goal was just to fix a failing unit test.
> 
> I recall that this test was failing on purpose actually (to keep track to work on the Link)
> @damienmarchal ?

Well... putting technical debt in failing unit tests does not force developers to fix the debt... It is as invisible as an GitHub issue (yes, because we know that the test is failing, so at some point we just don't care about it), and it pollutes diagnostics on the CI.

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Pull request merged**
