### PR TITLE
[Sofa.Core] minor refactoring for Data::read() to move into BaseData the reading code

### PR DESCRIPTION
**Pull request by damienmarchal**
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Comment by damienmarchal** [comment]
Haha no surprise tests didn't worked :)

**Review by alxbilger — COMMENTED** [review]
Can you explain what `BaseData::read` does?

**Comment by damienmarchal** [comment]
Hi @alxbilger 

Thanks for reviewing the PR. 
BaseData::read is an existing function in sofa, that do the reading from a stream into a data field. 

The PR does not change only how it was implemented. Before the PR, Data::read is duplicated for every type of data stored in the data field while in most of the case the reading pattern  is the same. With the PR the "shared" behavior is moved into the base class which allows to enforce a consistent behavior regarding error checking & resetting the value when the field to parse is empty.

**Comment by damienmarchal** [comment]
[ci-build][with-all-tests]

**Comment by damienmarchal** [comment]
Merged by mistake...reverted in emergency mode.

**Pull request merged**
