### PR TITLE
[helper] Cleaning & Improving helper::vector & helper::set

### PR DESCRIPTION
**Pull request by damienmarchal**
The state of vector.h and set.h is a bit messy right now. 

A recent PR have added tests to vector & fix several crashes & infinite loop. It appears that the problematic code is also in set.h so a general code factoring is needed. 

There is also some details on container refactoring in PR #113 
Finally it is not very clear what should be in std:: and what should be in sofa::helper:: ...
and there is a lot of code in the .h for only two specialization I see no reason why they shouldn't be make extern and implemented in .cpp. 

So this PR is a WIP in which everyone is welcome to contribute.

My current todo list is:
- implement tests for set so we can refactor safely. 
- declare int & unsigned int as extern template & move specialization from .h to .cpp for vector & set
- have everything in sofa::helper for consistancy (vector, set, map, pair, list, deque)
- fix the problem pointed by @maxime-tournier  in #271 in the remove* functions.  
- remove the lines added by hugo 
```cpp
/// \todo: refactoring of the containers required
/// More info PR #113: https://github.com/sofa-framework/sofa/pull/113
```
______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
@JeremieA I re-read carefully your comment on #113 to compare to what @maxime-tournier is proposing (which look an improvement against the actual code). I actually forgot that you made your own refactoring of theses classes and don't want to interfere so do you prefer we can just close this PR and wait for your refactoring ?

**Comment by damienmarchal** [comment]
@maxime-tournier  and @matthieu-nesme 
Thanks for your suggestions,

It is not very clear when you are refering to "current approach" if you are discussing about the sofa version or the one that is already in this PR. 

Existing Sofa looks like: 
```cpp
namespace std{
       ... operator<<(ostream, std::set); 
}
```

In this PR it looks like: 
```cpp
namespace sofa::helper{
       using std::set ;   /// do we need the template prefix as matthieu suggested ?  
       ... operator<<(ostream, sofa::helper::set); 
}
```

Maxime's suggestion 
```cpp
namespace foo{
       template<class ...T>
                struct vector final : std::vector<T...> {
                using std::vector<T...>::vector;
       };
       ... operator<<(ostream, sofa::helper::set); 
}
```

The sofa existing one is clearly bad as it pollute the namespace. It seems to me that maxime's suggestion avoid the need to have 'using operator<<' in calling code. It is unclear to me what are the drawback.

**Comment by matthieu-nesme** [comment]
After discussing with Max, my solution does not work as the type alias does not prevent the << operator defined on foo::vector to be used on std::vector.
So Max's solution is the one!

**Comment by damienmarchal** [comment]
I have commited the version using 'using' and replaced the std::* by their counterpart; 
I have to work on something else this afternoon & tomorrow so if some you guys want to implement the @maxime-tournier's approach feel free to commit directly in this PR.

**Pull request closed without merging**
