### PR TITLE
[Regression] Test linear solvers for regression

### PR DESCRIPTION
**Pull request by alxbilger**
Add scenes to test for regression. The scenes are about linear solvers.
The async solvers are not added due to the unpredicted nature of the solvers (cannot be tested for regression).

[ci-depends-on https://github.com/sofa-framework/Regression/pull/23]

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Review by epernod — CHANGES_REQUESTED** [review]
2 new scenes tests are failing on windows:
```FEMBAR_ShewchukPCGLinearSolver_BlockJacobiPreconditioner```
```FEMBAR_ShewchukPCGLinearSolver_PrecomputedWarpPreconditioner```
Any idea why? What is different form the others ones you added?

**Comment by alxbilger** [comment]
> 2 new scenes tests are failing on windows: `FEMBAR_ShewchukPCGLinearSolver_BlockJacobiPreconditioner` `FEMBAR_ShewchukPCGLinearSolver_PrecomputedWarpPreconditioner` Any idea why? What is different form the others ones you added?

That's a good question! Especially as I am on Windows. I'll have a look. Otherwise, I'll remove those tests for the moment.

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by alxbilger** [comment]
@epernod @fredroy it seems the issue was due to the files paths length

**Comment by fredroy** [comment]
> @epernod @fredroy it seems the issue was due to the files paths length

Nice find ! 👍

**Pull request merged**
