### PR TITLE
[all] Restore 'human readable' saving to xml

### PR DESCRIPTION
**Pull request by damienmarchal**
The current implementation of file saving in XML is in fact doing a kind of complete dumping of the state of the objects in the scene. This is bad because this produce totally unreadable scene.  

The idea of this PR is to implement a much more "user friendly" file saving as described in this issue
https://github.com/sofa-framework/sofa/issues/41

Saving caduceus.scn with the old way look produce a 2Mb file like this:  http://pastebin.com/01hfAeAT
while with the current code it is a 3.5Kb file looking like this: http://pastebin.com/K3jzVxcE

Please help to improve it by reporting any problem or patch. 

Additional things to do in future PR:
    - support saving of scene created from Python (I have a prototype...I'm waiting integration of this PR)
    - support saving scene to python (with the same readability logic)
    - fix the broken component that parse directly the xml attribute instead of using data. This is the case of  (VisualModelImpl, CubeTopology). These component have to be fixed one by one (including test to validate that there is no regression). 
    - implement a more "dump" like feature to save a scene that have been simulated.  

Checklist to be merge: 
  - [ ] succeed on each compilation setup on the CI.
  - [ ] does not generates new test failure. 
  - [ ] does not seems to break existing scenes. 
  - [ ] does not seems to break API compatibility.  
  - [ ] introduces new component with tests & documentation. 
  - [ ] is now 1 week old and no one send a 'no go' comment.

### CODE REVIEW

**Comment by guparan** [comment]
Nice work Damien! I will have a look at the code ASAP...
Does someone know why the XML export was done the "dumping way" at first?
Anyway I like this kind of "user friendly" pull requests :)

**Comment by matthieu-nesme** [comment]
Hi Damien, thanks for that work.

- what's the story about MechanicalObject::d_size?
- I am not a big fan of adding more Data (for the overcost we know)
     - 'template' can easily be managed by hand
     - 'src' can disappear at export, being replaced by the Links it had created
- having the gui choosing which Data must be saved is limiting and dangerous. Limiting because, you have to implement it in each gui that is able to save. Dangerous because you can manually change a Data that will be incompatible with another Data present in the loaded scene.

A more generic way to know which Data must be exported has to be found. It is linked to saving a scene after simulation. It is not trivial for sure.

My guess is each Base should have an virtual 'export' function. By default this function exports every Data (by default all data are persistent). Then component by component you can unselect some Data from the export (by setting them un-persitent) in their constructor. For complex situations, including possible incompatible Data (not so many components), a specific 'export' function can be implemented.

Little by little every scenes should be exportable, including during simulation.

**Comment by damienmarchal** [comment]
Hi Mathieu,

- About the 'd_size' data field. It is there just to store the attribute passed by the user. As the parse function already do the resize using the raw value of the attribute it was not needed to do any resize(d_size.getValue) anywhere. 

- I share your concern about the cost of adding data. 
According to the last updates in Issue https://github.com/sofa-framework/sofa/issues/44) it seems that data is not that crucial for a real simulation. 

To have more insight I just made a quick test with the following result: 
The time to create 200 000 (empty) component (without calling the init function):
      - with 6   Data field is 1.10sec
      - with 10 Data field is 1.55sec
So one data field added to a component cost 0.05ms at component creation (it is higher than what I expected). 
Now for a more realistic scenario with 200 SphereModel created and initialized one extra data field rise the cost from 3.1 ms 3.2ms and that this is 'dialuated' in all the other cost (collision detection, mechanics). 

About your suggestion to set everything to persistent by default and have each component decide what is good to save or not. This is what SOFA actually does and this behave terribly. 
I see two reason for that:
   - there is a lot of component that 'forgot' to set/unset the persistent values.
   - it is very hard to identify what is relevant to save, IMO because what is relevant to save is a matter of context of use, a Data 'useless' for one may be very useful for someone else. 

This is why I choose to do things in the reversed way and let the client code to select what to save   (so that you may eventually implement dedicated widgets to let the user select what to save).  

I see at least to different context of use and thus saving strategies. 

For my context of use it is more important to save scenes that are as close as possible as the one written by the user. This is why I made the XML loader and the GUI have the responsability to make persistent:
   - the value given explicitely in the scene file
   - the value specified explicitely in the GUI via the widget or the manipulators
Despite being very simple this work very well and without any risk that some authors breaks the saving because he forgot/decide not to setPersistent(false) in his component (and this happened quite a lot in the past).

For your context of use, for which saving a simulated scene is important I think a very simple solution would be to write a visitor to switch all the Data values to persistent.  And I would suggest to put this feature to a different entry in the menu (what about "Export" or "Dump" ?) so that in the same application we can either save or dump the scene with very well defined semantics ? 

Now about the fact that some Data editted in the UI can be incompatible with another Data. I will let that for another day because to me this is a much more general UI problem.  

Finally to improve a bit the general readability in any context of use we could, when writing big chunk of numbers (like vector.size() > 20) save them in separated files leading to something like:  
<MechanicalObject name position="@file://./name.position468768764568.txt" />

I will come back later with commit that take your remarks into account.

**Comment by damienmarchal** [comment]
Here is a list of component that are using raw attributes and thus will fail to be saved:
ImplicitSurfaceMapping: minx/max
 RuleBasedContactManager: 
CubeTopology: parse, min/max
SelectConnectedLabelROI 
RegularGridTopology
GridTopology
MeshLoader
VisualModelImpl
BaseObject (the src/template)

From my point of view using raw attribute in the parse function to ease scene writing allows developpers to implement 'creative' UX behaviors, and it is causing a lot of trouble. The problem is that doing this always breaks the consistency of the user interface of Sofa (when looking to the XML scene the user have not idea what is a 'parsed only' attribute and what is a data; when looking in the GUI he does not know that 'parsed attributes' exists and has no way to discover and manipulate them). 

For attributes of the like: "xmin", "ymin" (in the CubeTopology) or the "sx", "sy" (in the VisualModelImpl)
I'm considering to replace them with an extended point based notation for attribute 
"sx" -> "scaled3d.x" 
this would make it very clear that sx is in fact a subfield of the scale3d Data. (Haven't looked on how we can implement that) 

Now about the 'size' attribute to set the size of all arrays in MechanicalObject...this a clear example of what you call a Dangerous behavior (having and saving Data that are not compatible to each other).
The best solution I currently have is to warn the user that 'size' is in fact transformed to setting all arrays into position.size='10'. We we could also rename that by writing 'initialSize' assuming that if the array is set...the initialSize is overwritten. 

To be continuated... time to code.

**Pull request closed without merging**
