### PR TITLE
[All] Remove ExtVecType

### LINKED ISSUE #957: ExtVec3Type could be removed
I will delete ExtVec3Type if I understand this is useless.
See #863 
______________________________________________________

Suggested labels:

### PR DESCRIPTION
**Pull request by fredroy**
Fix #957 

Breaks:

1. as extvec3 and vec3 are synonyms, compilation will fail if templates are instanced on Vec3 and ExtVec3. Especially for mapping:
 e.g: 
`SomeMapping<Vec3Types, ExtVec3Types>
SomeMapping<Vec3Types, Vec3Types>`

this will fail because the compiler will try to instanciate SomeMapping twice with the same types.

2. scenes where a mechanicalobject, an OglModel and a mapping are present in the same node:
e.g:
`    <Node>
	    ....
        <MechanicalObject name="DOFs" template="Vec3d" translation="0 0 -4" />
         ...
        <OglModel name="Visual"  color="red" />
        <IdentityMapping input="@." output="@Visual" />
    </Node>`
   
 will fail now because the mapping could think you are referring to the same input and output. (linking  ¨@." to the OglModel instead of the MechanicalObject)
It was not failing previously because there is no mapping instanced on <ExtVec,Vec>, therefore the mapping was finding the MechanicalObject as its input.

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][force-full-build]

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][force-full-build]

**Comment by epernod** [comment]
force full build?? this one has been hidden from us :)

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Pull request merged**
