### PR TITLE
[cmake] Add option to limit cores used to build specific targets

### PR DESCRIPTION
**Pull request by bcarrez**
This PR adds the cmake option "NINJA_BUILD_POOL_FLEXIBLE" which limits the number of CPU cores used to build the Flexible target (default value: 1). Can be easily replicated to other projects as needed. 
This is only effective when using Ninja.
This will make possible to optimize the number of build threads without hitting the RAM limit on CI, but also on workstations.
______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings nor unit test failures.
- [x] does not break existing scenes.
- [x] does not break API compatibility.
- [x] has been reviewed and agreed to be transitional.
- [ ] is more than 1 week old (or has fast-merge label).
- [ ] reports important changes in Changelog.

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
+1 for this excellent feature :)

**Comment by matthieu-nesme** [comment]
Would it be possible to set the nb of threads automatically to the max (like default ninja w/o the j option)?
(or to deactivate the pool...)

**Comment by bcarrez** [comment]
I just added the option SOFA_NINJA_BUILD_POOLS to activate the pools feature for ninja (default:OFF). This way, by default, the feature will be inactive for the average user but it can be easily used by the CI or any "advanced user".

**Comment by damienmarchal** [comment]
I recommand a fast-merge on this one.  With this we will be able to add -j3 on windows builds...and on "heap" error we will reduce "locally" the number of jobs.

**Comment by matthieu-nesme** [comment]
tip-top. Mergeable right now!

**Pull request merged**
