### PR TITLE
[Project] Add the graph illustrating the workflow of a PR review in CONTRIBUTING

### PR DESCRIPTION
**Pull request by hugtalbot**
Add the graph illustrating the workflow of a PR review in the SOFA community

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by epernod** [comment]
Sorry maybe you said it at the Dev meeting but how does the reviewer1 notify he want a second reviewer?

**Review by epernod — COMMENTED** [review]
Sorry maybe you said it at the Dev meeting but how does the reviewer1 notify he want a second reviewer?

**Review by epernod — APPROVED** [review]
yes, makes sense

**Comment by damienmarchal** [comment]
@hugtalbot  for a second review... it is better to explicitely say so by pointing to someone for the review.

**Pull request merged**
