### PR TITLE
[SofaKernel] Fixes 344 : Make sure the mechanical object's state vectors size matches their respective argument size

### LINKED ISSUE #344: MechanicalObject output an error on the position state vector's size when debug is enabled
When sofa is compiled in debug mode, if the positions are initialized manually in the _position data attribute_ of the MechanicalObject, the later will always output an error stating that the position state vector contains a bad size.

This message is called because the `MechanicalObject::init()` method calls `MechanicalObject::write(VecCoordId::position())` before setting the `vsize` member (with .`MechanicalObject::resize()`).

One solution would be to first set the size accordingly to the _position data attribute_ of the MechanicalObject in the `MechanicalObject::init()` method before the `MechanicalObject::write()` is called.

To reproduce the error, first compile Sofa in debug mode, and try with the following scene:
```
<Node>
   <MechanicalObject position="0 0 -2.5    0 0 7.5    10 0 -2.5    10 0 7.5" />
 </Node>
```
It should output something like:
`[WARNING] [MechanicalObject(mObject1)] Writing to State vector position(V_COORD) with incorrect size : 4 != 1`

### PR DESCRIPTION
**Pull request by jnbrunet**
This PR fixes #344. 

It also add a small feature to print a warning if one or more of the vector's size passed by argument to the scene don't match the others.

To reproduce, use the following scene with the debug binaries:
```
<Node>
   <MechanicalObject name="p" position="0 0 -2.5    0 0 7.5    10 0 -2.5    10 0 7.5" />
   <MechanicalObject name="v" velocity="@p.position" />
   <MechanicalObject name="f" force="1 0 0 1 0 0 1 0 0" position="@p.position" />
   <MechanicalObject name="ef" externalForce="@p.position" />
   <MechanicalObject name="fp" free_position="@p.position" />
   <MechanicalObject name="fv" free_velocity="@p.position" />
   <MechanicalObject name="rp" rest_position="@p.position" />
   <MechanicalObject name="rep" reset_position="@p.position" />
   <MechanicalObject name="rev" reset_velocity="@p.position" />
   <MechanicalObject name="dx" derivX="@p.position" />
 </Node>
```
Before PR:
```
[WARNING] [MechanicalObject(p)] Writing to State vector position(V_COORD) with incorrect size : 4 != 1
[WARNING] [MechanicalObject(v)] Writing to State vector velocity(V_DERIV) with incorrect size : 4 != 1
[WARNING] [MechanicalObject(f)] Writing to State vector position(V_COORD) with incorrect size : 4 != 1
[WARNING] [MechanicalObject(rp)] Accessing State vector restPosition(V_COORD) with incorrect size : 4 != 1
[WARNING] [MechanicalObject(rp)] Accessing State vector restPosition(V_COORD) with incorrect size : 4 != 1
[WARNING] [MechanicalObject(rep)] Writing to State vector resetPosition(V_COORD) with incorrect size : 4 != 1
[WARNING] [MechanicalObject(fp)] Writing to State vector freePosition(V_COORD) with incorrect size : 4 != 1
[WARNING] [MechanicalObject(fv)] Writing to State vector freeVelocity(V_DERIV) with incorrect size : 4 != 1
[WARNING] [MechanicalObject(rep)] Accessing State vector resetPosition(V_COORD) with incorrect size : 4 != 1
[WARNING] [MechanicalObject(rev)] Accessing State vector resetVelocity(V_DERIV) with incorrect size : 4 != 1
```
After PR:
```
[WARNING] [MechanicalObject(f)] One or more of the state vectors passed as argument don't match the size of the others : position(size 4) force(size 3) 
```

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Great...shouldn't the test scene become a test to detect future regression ?

**Comment by jnbrunet** [comment]
Well in this case, the bug was a wrongfully warning printed only when Sofa is built in debug. Can we create tests that are that specific?

I could try to do some regex ninja tests on the application output, but it would have to be executed on debugged configurations. Let me know if this is something you would like to see for this PR.

**Comment by damienmarchal** [comment]
I was thinking that the PR was about keeping the vsize and real vector size the same so I was thinking 
to a test that fails if there is a size mismatch. But I may be wrong...I'm really weak on these part of Sofa.

**Comment by jnbrunet** [comment]
The rest of the init code will automatically adjust the vector size with or without my code, but it will print a wrong warning every time. My PR just fixes this by pre-adjusting the vector size and print a good warning in the case that the scene got a positive mismatch with its parameter's vectors size.

The other solution would be to definitely remove those warning in MechanicalObject's read and write functions, for which I'm not very sure why they would be useful to the developers.

**Comment by damienmarchal** [comment]
Ok so if the pr is just about wrong messages no need for test :)

**Review by damienmarchal — APPROVED** [review]

**Comment by damienmarchal** [comment]
@guparan...the failing test on stl exporter are also fixed. 
@jnbrunet Thanks again for the PR.

**Pull request merged**
