### PR TITLE
[SofaCore] Move definition of Link::updateLinks to BaseLink.h

### PR DESCRIPTION
**Pull request by damienmarchal**
This PR the updateLinks method in SingleLink and MultiLink.
The rational is taht there is no need to implement general algortihm in templated class if one version is possible for their abstract Base class.

Implementing the algorithm in the has multiple advantage:
- easier to read, understand and debug because there the code is template free
- faster to compile as only one version of the code has to be code-generated instead of having one version for each type template in each the compilation units. 
- as the implementation is not templated it can be defined in the .cpp instead of the .h, this permit to have less #include files that propagate in all our code base. 

Basically:
    SingleLink<T>::updateLinks (in  Link.h)
    MultiLink<T>::updateLinks (in  Link.h)
    are now implemented in BaseLink.cpp

several methods (_doXXX_) in BaseLink have been introduced to expose Link<> behavior to BaseLink.

This PR is based on top if #1717 and #1749
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build][with-regression-tests][with-scene-tests]

**Comment by damienmarchal** [comment]
[ci-build][with-regression-tests][with-scene-tests]

**Comment by damienmarchal** [comment]
[ci-build][with-regression-tests][with-scene-tests]

**Comment by damienmarchal** [comment]
[ci-build][with-regression-tests][with-scene-tests]

**Comment by fredroy** [comment]
I set breaking because of the API changes, even if I am sure nobody will even notice it.

**Pull request merged**
