### PR TITLE
FIX: Mouse picking on Mechanical Object 

### PR DESCRIPTION
**Pull request by olivier-goury**
Solves issue #84 

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Congratulation Olivier for your two PRs in a row. 

If there is an open issue that is related with this fix you can connect it so that when the PR is merge...the corresponding issue is closed. 

@hugtalbot I think you can merge this one bypassing our traditional reviewing process :) 

[ci-build]

**Comment by bcarrez** [comment]
This PR is so simple I cannot imagine anything that would go against its fast merging.

**Comment by matthieu-nesme** [comment]
indeed, nice finding :)

**Comment by maxime-tournier** [comment]
Thank you so much for this, it had been bugging me for ages!

**Comment by bcarrez** [comment]
So... I take the responsibility to merge it. Blame me if I break something.

**Pull request merged**
