### PR TITLE
[SofaKernel] Fix getRelativePath() in DataFileName + add tests

### PR DESCRIPTION
**Pull request by damienmarchal**
Problem:
The implementation of getRelativePath is broken as it returns the current
value which can be either a relative or an absolute path.

Solution:
The new implementation is building a real relative path against the path contained
in the DataRepository.

I also added few test for DataFileName to valide the different behaviors.

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings nor unit test failures.
- [x] does not break existing scenes.
- [x] does not break API compatibility.
- [x] has been reviewed.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by matthieu-nesme** [comment]
missing python binding

**Comment by damienmarchal** [comment]
The relativePath  was existing in C++ but not in python. 
I fixed the c++ version because it was not working but I didn't planned in this PR to add a new feature to Python. 

But fundamentally you are right.. It would be nicer to have it exposed and I can hijack this PR for that :)

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
For merging this PR I ignore gcc-5.4 because the CI is not ready on this build target.

**Comment by guparan** [comment]
Hi @damienmarchal,
You broke [DataFileName_test](https://ci.inria.fr/sofa-ci/job/windows7_VS-2015_amd64_pr_1_options/178/testReport/(root)/DataFileName_test/checkSetGetRelativePath/) on Windows with this PR. 
Could you have a look?

**Comment by damienmarchal** [comment]
This PR introduces the DataFileName_test and seems to have never succeeded on windows. 
Thank for pointing me that, I will fix that asap.

**Comment by damienmarchal** [comment]
Ok, so I gave it a quick look. 
The good news is that this PR does not breaks anything. 
The bad news is that the failing test may be a new OpenIssue. 

The underlying problem is that the implementation of 
std::string FileRepository::relativeToPath(std::string path, std::string refPath)
is converting the path to be to lowercase on windows but not on Linux/MacOS.

I see no good reason why we should do that only on Windows so I think we should fix this function to gave it a consistant behavior on all OS as well as a behavior that correspond to its name. 

If returning a lowercased relative path is important this should be implemented in a separated function.

**Comment by guparan** [comment]
Thanks for this quick clarification!

Shouldn't we just remove the lowercase transformations? 
This shouldn't break anything as Windows is case-insensitive (normally).

**Comment by matthieu-nesme** [comment]
I guess lowercasing on windows was to simplify path comparisons (using string comparison). Be careful not to break something else while removing it.

**Comment by damienmarchal** [comment]
I share's @guparan  that the lowering at this location should be remove because it just make any sense to have that there. But Mathieu is totally right this could eventually break someone's code and thus we cannot do that without care.

**Pull request merged**
