### PR TITLE
[SofaBaseMechanics] 🐛 FIX draw function in UniformMass

### PR DESCRIPTION
**Pull request by marques-bruno**
(when no mstate is provided)

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Yes :)

**Comment by marques-bruno** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
Good to me.
Just a small note that in a future PR it would be better to test if the componentState is Valid before drawing.

**Comment by epernod** [comment]
```ubuntu_gcc-7_options — Build OK. FIXME: 3 units, 276 scenes, 1 regression ``` ?

**Comment by damienmarchal** [comment]
lol :+1:

**Comment by guparan** [comment]
Trust me, CI is OK :factory_worker:

**Pull request merged**
