### PR TITLE
[SofaSimpleFem] Remove branches based on type of matrix

### PR DESCRIPTION
**Pull request by alxbilger**
Since CRS matrix are now optimized when inserting a 3x3 block, it is no longer necessary to have branches in force fields, where a branch is selected based on the type of matrix.
The virtual call to `add` is generic, but leads to the optimized matrix insertion.

I did not notice any significant performances changes in the scenes located in `examples\Benchmark\Performance\MatrixAssembly`

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
I really dont see why the Quater test fails with mac in this PR 🤔

**Comment by alxbilger** [comment]
> I really dont see why the Quater test fails with mac in this PR 🤔

@fredroy I see the test uses randomly generated quaternions as input (the seed is based on the current time -> this should be changed). It's probably a hint that something is wrong, and that it fails randomly.

**Comment by fredroy** [comment]
> 
> 
> > I really dont see why the Quater test fails with mac in this PR 🤔
> 
> @fredroy I see the test uses randomly generated quaternions as input (the seed is based on the current time -> this should be changed). It's probably a hint that something is wrong, and that it fails randomly.

Duly noted

**Pull request merged**
