### PR TITLE
[All] Fix some warnings

### PR DESCRIPTION
**Pull request by epernod**
Several warning types:
- uint/int conversion
- bad init order
- missing break
- unused variables

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by guparan** [comment]
CI complains about 4 crashing scenes (timeout) on all configs:
```
examples/Components/collision/RayTraceCollision.scn
examples/Components/misc/MeshTetraStuffing.scn
examples/Tutorials/StepByStep/Dentistry_Haptics/dentalSurgery_Annex.scn
examples/Tutorials/StepByStep/Dentistry_Python/5_MeshGeneration.scn
```
Any idea?

**Comment by epernod** [comment]
I removed a commit by force push. It was failing on some OS.
Could it be linked to a bad rebuild?

**Comment by guparan** [comment]
TriangleOctree appears in all crash outputs.
Maybe adding those `break` actually broke something? :laughing:

**Comment by guparan** [comment]
> I removed a commit by force push. It was failing on some OS.
> Could it be linked to a bad rebuild?

The latest build was manually triggered by you after the force push, including scene tests. So I guess the answer is no.

**Comment by epernod** [comment]
> TriangleOctree appears in all crash outputs.
> Maybe adding those `break` actually broke something? 😆

let see... if switch without break is waited....

**Comment by guparan** [comment]
Seems good :+1:

**Pull request merged**
