### PR TITLE
[CI] Replace 'make' by 'ninja' when available. 

### PR DESCRIPTION
**Pull request by damienmarchal**
Add support for the Ninja generator and build system. 

Ninja is faster when doing incremental builds and it reports the number of file compiled like this [45/1384] instead of a percentage [5%]].

Having the numbers is very useful to debug CI/ccach problem.

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
Can someone check & merge this quickly I would like to use it to optimize the windows builds time.

[EDIT] I typed to fast :) it will work on windows but does not with visual 2015

**Comment by guparan** [comment]
This one was merged too fast.
I wanted to change a bit the code :(

**Comment by thomas-lemaire** [comment]
sorry, it looked simple and fine for me... 

----- Mail original -----

**Pull request merged**
