### PR TITLE
[SofaGuiQt] Fix compilation when QtGuiInteraction plugin enabled

### PR DESCRIPTION
**Pull request by BehnamBinesh**
This commit fixes compilation error while adding QtGuiInteraction plugin.

### CODE REVIEW

**Comment by matthieu-nesme** [comment]
It depends on your Qt version.

The actual code is for Qt4 while removing QApplication::UnicodeUTF8 (like in your proposal) is for Qt5.

A #ifdef should be added to check the Qt version.

But what about renaming "gridLayout" in "_14"?!

**Comment by damienmarchal** [comment]
gg mathieu for spotting the renaming to "_14" 

On my side I prefer code without #ifdef all around. 

What about something like ? 
```cpp
#ifdef QT_SOMETHING_WITH_5
#define QT_TERM QApplication::UnicodeUTF8
#else
#define QT_TERM
#endif 
̀``

Then use QT_TERM instead of QApplcation::UnicodeUTF8

**Comment by matthieu-nesme** [comment]
I've got no opinion.
Just be aware you'll need a comma and that's the other way around.

```cpp
#ifdef QT_4
#define QT_TERM ,QApplication::UnicodeUTF8
#else // QT5
#define QT_TERM
#endif

**Comment by damienmarchal** [comment]
@BehnamBinesh can you update your pull-request ?

**Comment by matthieu-nesme** [comment]
@damienmarchal  it is not the right place, but it is the right moment, in case you did not know it.
It is easy to modify an existing PR. You simply have to add the fork containing the PR in your local repo (`git remote add`), you can then have access to the PR like any other branch.

The pb with this specific PR, is that the branch is the master of the BehnamBinesh fork, it is quite disturbing to modify the master of someone else, but I guess it is ok here.

**Comment by guparan** [comment]
@matthieu-nesme: What would be the right place for your #ifdef proposal?

**Comment by matthieu-nesme** [comment]
I have no preference.
Either at each QApplication::translate (more verbose but more explicit) or using a more global preprocess variable (less verbose, as suggested by Damien)

**Comment by guparan** [comment]
@matthieu-nesme or @damienmarchal could you review my commits please?

**Comment by damienmarchal** [comment]
Looks ok to me.

**Comment by bcarrez** [comment]
The code looks safe, the topic seems enough discussed and everyone seems ok. Very unlikely to break anything in the current state, I merge it. 
If it breaks something, please report it.

**Pull request merged**
