### PR TITLE
Fix VS2013 build

### LINKED ISSUE #98: status of VS2013
Currently sofa does not compile with VS2013, and I see there is no VS2013 VM on the continuous integration.
- Is VS2013 support dropped ?
- I read in some email that there is a plan to have again a VS2013 VM, is it still the plan ?

thomas

### PR DESCRIPTION
**Pull request by guparan**
Please tell me if anything is wrong or unclear. 
I'm not C++11 fluent (yet) ;)

Fixes #98

### CODE REVIEW

**Comment by damienmarchal** [comment]
Everything looks clear to me. 
Why did you taggued this with "bug" ?

**Review by damienmarchal — APPROVED** [review]
I cannot test windows compilation but the CI seems happy with your code. 

I didn't expected that fixing for VS2013 it would be that nice. 

Maybe you could replace #if defined(WIN32) && _MSCV_VER<19000 
with something like #ifdef COMPILER_IS_VISUAL2013 to make the condition more clear.

**Comment by damienmarchal** [comment]
So, after discussion it was decided to avoid the #ifdef can you update that ?

**Comment by guparan** [comment]
Done. I amended my last commit :)

**Pull request merged**
