### PR TITLE
[CGALPlugin] MeshGenerationFromImplicit and associated shapes

### PR DESCRIPTION
**Pull request by thomasgosse**
PR #351 should be merged before.

## Description

This PR aims at meshing an implicit shape with CGAL ; ImplicitShape is a concept of class (inheriting from BaseObject) defining any implicit shape by a common method `eval(Point p)` which returns the value of the function at this point.
Basically, it's possible to create a component inheriting from ImplicitShape, to describe a shape (torus, sphere etc.) by its literal equation.

## User Guide

A Sofa scene file is featured (in the CGALPlugin scene repertory) and allows the user to choose the type of ImplicitShape he wants to mesh, and to change the values relating to the mesh (**facet_size**, **approximation** and **cell_size**).

- Fill the scene with a shape :

`<DistanceGridComponent`   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`name="grid_cmp"`
> .tmg is our extention file which is actually a simple list of values corresponding to the function evaluated at each point : see PR #353 
`filename="/path/file.tmg"`  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`nx="243"`   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ny="243" `  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`nz="243"`   
`/>` 

or  
`<ImplicitSphere name="sphere" />`

or any class inhereting from ImplicitShape.

- Modify the mesh component value's and use the correct component in the link

` <MeshGenerationFromDG`   
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`name="mesh" `
> The 3 following parameters can change the execution time (from a few seconds to much more)  
`facet_size="0.7" `  
`approximation="0.5"`   
`cell_size="0.4" `  

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`drawTetras="false"`  

> Then the link  
`function="@sphere"` which is actually a torus 
or	  
`grid="@grid_cmp"`
  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`xmin_box="0.0" `  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ymin_box="0.0" `  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`zmin_box="-5.0" `  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`xmax_box="27.0" `  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`ymax_box="27.0" `  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`zmax_box="5.0" `  
`/>`

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hi Thomas,

Glad you made this PR, so thank you. 
 
Some feedback:
   - Everything in sofa is a component so the default name of "DistanceGridComponent" should be shortened into "DistanceGrid" when it is used in the scene. You can do that by overriding the function std::string Base::getClassName() const.
    - I would be much better to have the number of samples (the nx,ny,nz) stored at the beginning of the tmg file. 
    - I assume that in MeshGenerationFromDG, the DG is for DistanceGrid. As it work with ImplicitShape wouldn't it be better to name it MeshGenerationFromImplicitShape ?   
    - There is not tests for the added classes.

**Comment by thomasgosse** [comment]
@damienmarchal The "DistanceGrid" alias is already taken by the "DistanceGridCollisionModel" component, do you have another idea ?

**Comment by thomasgosse** [comment]
@damienmarchal Modifications have been done in DistanceGrid class that allows to read the number of sample in the .tmg file, and fill automatically nx, ny and nz at the instantiation of the grid. You can find these changes in PR #353.

**Comment by thomasgosse** [comment]
@hugtalbot You can start the review, I just modified/add some code as Damien wanted !

**Comment by damienmarchal** [comment]
@ThomasGosse & @hugtalbot about the nameing of DistanceGrid.

The easy path:
- don't rename DistanceGridComponent 

Intermediate path:
- rename DistanceGridComponent to DistanceField 

The hard path (probably in a future PR if we want to):
- your component should be named DistanceGrid
- remove the alias 'DistanceGrid' on DistanceGridCollisionModel 
- update all the Scenes to use DistanceGridCollisionModel
- add a rules in the SceneChecker (see recent PR about it) that warns that for sofa version < 17.12  DistanceGrid have been changed.

**Comment by damienmarchal** [comment]
Ok so I see still a lot of change to do before to have a clean PR to merge. 
The first change is probably to make the code available in an independant plugin. 
I wonder if this could be an opportunity to make the whole VolumetricData a plugin ....this could be a kind of gentle test for sofa core pluginiization, 

@guparan , @hugtalbot , @fredroy any opinion ?

**Comment by damienmarchal** [comment]
Hi all,

I'm still not sure if moving the whole VolumetricData into a plugin is a move we want to make so I pushed the current version to get your opinion if the direction is ok for you (or not). 
If we are courageous... is suggest re-organizing the directory/file layout otherwise we could just have all the file dropped into the plugin.

**Comment by damienmarchal** [comment]
Now I see there is code duplicated with InterpolatedImplicitSurface...So I will seriously rework this PR...possibly making a new one.

**Pull request closed without merging**
