### PR TITLE
[all]  Unifying color datafield

### PR DESCRIPTION
**Pull request by damienmarchal**
Summery of the problem statement:
currently in sofa there is not rules to describe colors inthe data fields. Consequently some components use Data, others rely on Data and others are using a combination of Data with private float r,g,b,a member. So there are component that accepts color by string "blue" or "#aabbccdd", other works by passing "0 1 0 1" while others "0 1 2".

This lack of consistency in a problem in term of user interface design which impact XML, python scene as all as in GUIs like runSofa or qtQuickSofa.

To solve that I replace the existing data fields with a dedicated type for color (see defaulttype::RGBAColor introduced in PR ##119) .

The advantages are multiple:
-  expose color in a consistent way to the users.
-  all the components now supports the following way to set color: "blue", "0 0 1 1", "0 0 1", "#0000AAAA", "#0000AA", "#00AA", "#00A",
-  the code to convert the string to a RGBAColor is no more duplicated in component and is now more robust and reports more errors to the users.
-  the behavior of the RGBAColor public API is now tested in Color_test.cpp.

The disadvantage is that despite I try not to break things (especially in scene) ... it may happens (brecause the commit is rather big & touch a lot of files). So please test it on one or two scene of your choice and report problem.

This PR depends on PR #119
This PR replace PR #124 
This PR solve the Issue #64

Checklist to be merge:

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings nor unit test failures.
- [x] does not break existing scenes.
- [x] does may break API compatibility.
- [x] has been reviewed.
- [x] is more than 1 week old.

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by matthieu-nesme** [comment]
Really good cleaning.
Should not break scenes, but could eventually break components in private plugins, but they should be easy to update.

**Comment by matthieu-nesme** [comment]
[ci-build]

**Comment by matthieu-nesme** [comment]
[ci-build]

**Comment by guparan** [comment]
Is this still a work in progress?

**Comment by damienmarchal** [comment]
Not since one week. 
We were waiting VS-2013 to be removed.  
I just fixed the merge with master done by froy which was looking weird on OglLabel and 
add some tests.

**Comment by damienmarchal** [comment]
[ci-build]

**Pull request merged**
