### PR TITLE
[SofaKernel] Remove SofaTest dependency from framework_test

### PR DESCRIPTION
**Pull request by fjourdes**
This PR removes the dependency from SofaTest to the framework_test executable.
The reason for this is that SofaTest depends on a **lot** (if not all...) of librarires which do not reside 
in SofaKernel. So having a dependency to SofaTest somewhat defeats the whole puropose of writing
self contained fast to compile unit tests.
As a general rule, it should be a requirement that SofaKernel can compile without any dependency to 
libraries that do not reside in SofaKernel.
This PR address the problem only for framework_test, but the problem persists in SofaSimulation_test

# CHANGELOG
- Moved AdvancedTimer_test and DefaultAnimationLoop to SofaSimulation_test since they require to be able to instantiate a concrete instance of a Node
- Moved _TrackedData_test to SofaSimulation_test since it requires to be able to instantiate an AnimateBeginEvent object
- Removed dependency to SofaTest from framework_test, which implied the following
  - removing calls to EXPECT_MSG_NOEMIT ( which is defined in SofaTest )
  - copy pasting EXPECT_MAT_NEAR and EXPECT_MAT_DOUBLE_EQ macros from SofaTest in MatTypes_test.cpp

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
Thank you for this PR @fjourdes. It brings me a question: what is the purpose of `SofaKernel/modules/sofa/simulation/simulation_test`? Couldn't we split it in `SofaSimulationGraph_test` + `SofaSimulationTree_test` + `framework_test`?

**Comment by fjourdes** [comment]
@guparan : good question. Actually I also believe it should be split to actually match the current architecture. That is to say each library gets its own test exectuable ( provided one exist ). But for me that was beyond the scope of this pull request, which was to propose the removal of the `SofaTest` dependency from the `framework_test` executable, for the aforementioned reasons.

**Comment by damienmarchal** [comment]
Hi François,

Thank for this PR. Currently SofaTest contains two different things: 1) a set of utilitary classes to implement tests and 2) specific tests on component. 

To me the right approach is to split that in two. The utility classes should be moved into SofaKernel and be part of the framework as we want to use the utility classes to make test. While the specific tests can stay on SofaTest. 

Once that done the dependency to SofaTest can be removed. But the test in framework are still using the helper class including the ability to generate failure based on sofa error messages. 


EDIT: I forgot to say that your are totally right saying that these backward dependencies are bad and have a lot of consequence on modularization & compilation time in Sofa. As far as I can say @maxime-tournier is also working actively on that.

**Comment by damienmarchal** [comment]
@fjourdes What do you think about the approach taken in #471 ?

**Comment by guparan** [comment]
SOFA-dev meeting: we close this PR as #471 will be merged. Many thanks for your investment @fjourdes :-)

**Pull request closed without merging**
