### PR TITLE
[all] Replacement of std::cout with msg_* (week 17)

### PR DESCRIPTION
**Pull request by damienmarchal**
When I have free time but cannot be concentrated I do trivial 'cleaning' changes resulting in this kind of PR where I replaced the std::cout by msg_info.

CHANGELOG for @hugtalbot :
Trivial replacement of std::cout by msg_info
  - [SofaUserInteraction] 
  - [SofaValidation]
  - [SofaVolumetricData]
  - [SofaOpenGl]
  - [SofaNonUniformFem]
  - [SofaPython]
  - [SofaSparseSolver]
  - [SofaSphFluid]
  - [SofaTopology]
  - [SofaUserInteraction]

I also replaced this code pattern:
```cpp
#ifndef NDEBUG
     std::cout << blahblah
#endif
```

into this pattern:
```cpp
dmsg_info() << 
....
```
______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings nor unit test failures.
- [x] does not break existing scenes.
- [x] does not break API compatibility.
- [x] has been reviewed
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
After dev-meeting this PR needs to be updated to:
    - use dmsg_* instead of the condition on N_DEBUG

The change for conditional code will be done a separated PR so this PR is to review again :)

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by guparan** [comment]
Is this "pr: ready" ?

**Comment by damienmarchal** [comment]
At meeting it was asked me to update minor details...and was returned to wip...I have done the requested change so I change the tag to to-review.I didn't wanted to set it to ready because I prefer to have third "eye" looking at the change even if they are minor. 

I think if you think it is ok then the pr is ready and you can merge it.

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build] after merge #264

**Pull request merged**
