### PR TITLE
STC#4 Coding sprint base

### PR DESCRIPTION
**Pull request by guparan**
This is the work on which was based the STC#4 coding sprint.
It has to be merged to clearly differentiate deprecation and pluginization works afterwards.

It is a reopening of #429 (sort of).
I started from https://github.com/SofaDefrost/sofa/commits/deprecating_components beheaded until 456d88343e210ce89d9f7436c290be92fe438313 and merged it with master.
________________________________________________________________

It does:
- split the CMakeFile.txt in three sets to allow component deprecation/stabilization.
- implement a light C++ api in sofa::simpleapi::* to create component with a pythonic look & feel
- use the simpleapi to change the code of SceneCreator to cut the dependencies and to simplify the plugizniation of modules.  
- in SceneCreator, create SceneUtil.h where some function from SceneCreator are now. 
- remove the module/sofa/component/typedef/*  (which seems to cause no real problem)
- mute the SOFA_DECL_CLASS/SOFA_LINK_CLASS so maybe...as everything works in the CI we ca n probably remove those lines and stop using them in .cpp  
- remove c++ tutorials from CMakeList before real removal they are slow to compile, and induce big dependencies so it will slow down the deprecation. 
- add an InfoComponent in the loaded scene to indicate when an object failed to be created. 

To avoid post-cleaning workload I merged:
- PR#422 Fix for SofaImplicitField and SofaVolumetricData plugin
- PR#407 [SofaSphFluid & SofaMiscCollision] Pluginizing the two modules
For the same reasons we may also merge #414 #424 and #425

Notes: 
- the SceneCreator refactoring is not fully working and generates few test failures but this can be fix easily. 
- removing the typedef & SOFA_DECl/SOFA_LINK seems to ok. 

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
So if I understand this PR is not containing any work or fix done during the STC right ? 
So we really need to have the second PR (the one with deprecation) ready. 

EDIT: ok I understand.

**Comment by damienmarchal** [comment]
I'm fixing the failing tests in https://github.com/sofa-framework/sofa/pull/457

**Comment by damienmarchal** [comment]
As suggested by @guparan this one is to merge when we will be sure that #457 will have fixed the tests.
It is still unclear to me.

**Comment by guparan** [comment]
@damienmarchal why aren't you fixing the tests directly in this PR?

**Comment by damienmarchal** [comment]
Hello Guillaume,

I didn't planned to make a PR with this "base" and was thinking that you would use it during the coding-sprint and make a single PR after the sprint updating & fixing everything. So now I prefer to work in the post-sprint branch because I have not time to back-ports fix to an already deprecated code base, in addition working in this branch allows me to find & fix the extra problems introduced during the sprint.

**Comment by guparan** [comment]
Then could we merge this one?

**Comment by damienmarchal** [comment]
Hello Guillaume,

I'have mixed feeling. On one side I would like the sprint branch to be merged asap so that we can all start from this baseline and continue deprecating/pluginizing (I know bruno is waiting, as is the pluginization done during the STC) but, on the other side I dislike to merge things that fails. 

Currently the base branch have several tests failing and I fixed all of them in #457. I'm not sure all of them are easy to cherry-pick so I would recommend to merge this one and immediately after merge the #457 so that master is not in a broken state for a long time. 

Actually in #457 only one test remains to be fixed, the "VariationalXXX". This one was not in the base branch but appeared during the sprint. I have no idea what is wrong so if this speak to you @hugtalbot , @StephaneCotin, @ChristianDuriez please help. 

So my opinion is that we should accept the risk of merging #453 and #457 in a row so that we can restart working from a shared code base and continue our work and deals with the breaking/regression introduced. 
It also have advantages as more people will try this branch we will have more feedback on the deprecation process.

**Pull request merged**
