### PR TITLE
[CGAL] Fix build problem

### PR DESCRIPTION
**Pull request by bcarrez**
CGAL plugin has some build issues in some circumstances, this PR aims to fix it:

- build error if "image" plugin is deactivated
- BOOST_PARAMETER_MAX_ARITY too low by default (5 by default, where CGAL needs 12 at least)

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by bcarrez** [comment]
There is still a build problem with the "image" plugin. See issue #352 .

**Comment by guparan** [comment]
[ci-build]

**Comment by guparan** [comment]
Hi @bcarrez, is this PR still wip?

**Comment by bcarrez** [comment]
This PR is not WIP anymore and is ready to review.

**Pull request merged**
