### PR TITLE
[SofaBaseTopology Test] Add battery of tests on topology containers

### LINKED ISSUE #43: Creating tests on Topological operations
Hi,

several tests were already done for topological modifier, they are tested through scenes in examples/Components/Topology/TopologicalModifiers

They test: add/remove of topological elements
- Is sofaVerification still used? 
- I can easily rewrite those tests in c++ using the ::Sofa_test  api. Is it better? what is the politic between doing tests through scene or Sofa_test.

### PR DESCRIPTION
**Pull request by epernod**
as promised since long time ago...

There is still a lot of work to do but here is a first set of tests on the topology containers.
- Do not test yet the topological changes.
- Neither more complex algo like incision.
- Nor TopologicalData...

it is just the beginning !

FIX #43 

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by epernod** [comment]
Several tests are not passing yet due to error in the code to be fixed soon.

**Comment by damienmarchal** [comment]
I cannot support more what you are doing, thanks Erik !

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
Ok what is the strategy, there is 10 units tests crashing. Do I solve them in this PR or in a next one?

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Pull request merged**
