### PR TITLE
[All] Fix override warnings

### PR DESCRIPTION
**Pull request by vmagno**
This PR removes warnings caused by inconsistent use of the override keyword. While it might not remove all of them (not all plugins have been checked), it allows developers to actually fix the remaining ones rather than ignoring them because it will only generate more warnings.

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by fredroy** [comment]
[ci-build]

**Comment by guparan** [comment]
Nice job @vmagno, did you use a Clang program?
This PR makes the mac_clang-3.4_options build go from [2307](https://ci.inria.fr/sofa-ci/job/mac_clang-3.4_options/6119/consoleText) to [8692](https://ci.inria.fr/sofa-ci/job/mac_clang-3.4_options/6108/consoleText) override warnings (counting `-Winconsistent-missing-override` occurences). 
I guess it will only go worse until all missing `deprecated` are added.

**Comment by vmagno** [comment]
I actually just used grep to parse clang's compilation output to find the files and lines where the warning occurred, then sed to add the override keyword. I didn't do all plugins so there might still be a lot to add. But for the ones I went through, the number of override warnings went from over 1000 to none (with clang 5 on Linux).
It's true that I didn't test on Mac... At least now when we add override somewhere it should remove warnings rather than add more.

**Comment by damienmarchal** [comment]
Hi @vmagno  
Great job, could you please update the PR to take into account the changes made in master ? 
(Small tips: Most of the the problematic files have been moved in the plugins directory :))

**Comment by vmagno** [comment]
Ok it's done (I think it worked)

**Comment by damienmarchal** [comment]
@vmagno according to github there is still conflict on a bunch of file. 

I'm also a bit surprise with the fact that your PR contains commit from a lot of people and wonder if there is no merge/rebase work to do.

**Comment by vmagno** [comment]
Ok, done with more confidence now. I did a rebase to include changes done to master since that PR was first submitted this morning, but either it did something weird or other PRs were merged before this one. I did a merge this time. Let me know if you want to get rid of the commits appearing twice (I'll probably start the PR over).

**Comment by guparan** [comment]
Hey @vmagno, I rebased it 😉

**Comment by damienmarchal** [comment]
@guparan you are my hero in term of making good looking commit history :)

**Comment by guparan** [comment]
I merge, beware of further conflicts since this PR edits a lot of files...

**Pull request merged**
