### PR TITLE
[SofaValidation] ADD Monitor test (API BREAK)

### PR DESCRIPTION
**Pull request by marques-bruno**
Hi,
with @IPeterlik we noticed not so long ago that the pointers to the velocity, forces and positions of the mechanical object linked to the Monitor were not pointing at the same place before and after the call to init().
To show the issue I made this test scene for the monitor, but now the problem doesn't show up anymore. So it either has been corrected or the problem came from somewhere else.

Anyway the test is coded now, so here's a PR for it.

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hi @lagarkane  

Thanks for this PR. +1 for adding new tests :)

**Comment by guparan** [comment]
Thanks @lagarkane 
LGTM

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by marques-bruno** [comment]
OK,
I updated the PR with a few things:
1 / the test now checks the content of the generated files for error
2 / Monitor has an additional data field "fileName" through which one can override the default path to the generated files
3 / Monitor now respects basic coding guidelines
Looks a bit better now

**Comment by marques-bruno** [comment]
@damienmarchal you closed and then reopened the PR: Should I change something or is it mergable?
Shouldn't this kind of API-Breaking PRs be merged only on punctual releases?

**Comment by damienmarchal** [comment]
Closing & Re-opning was a mistake :)

You are right, breaking changes should be done only for punctual release...I wanted to discuss that in issue #318. But given the amount of breaking changes people want to merge...It think maybe the 17.16 will be a "breaking" release. To make the change more manageable by user I introduced a recent PR #329 for which I would like to have feedback (or support or thumb-up :)). 
 
Can you describe what exactly are the breaking and if you have time it would be super great if with #PR329 you can provide a custom hook to warn inform user of which changes happens.

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by guparan** [comment]
Previous build was affected by master errors. Let's [ci-build] again.

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by marques-bruno** [comment]
on my machine:

> [==========] Running 2 tests from 1 test case.
> [----------] Global test environment set-up.
> [----------] 2 tests from Monitor_test
> [ RUN      ] Monitor_test.testInit
> [       OK ] Monitor_test.testInit (21 ms)
> [ RUN      ] Monitor_test.testModif
> [       OK ] Monitor_test.testModif (17 ms)
> [----------] 2 tests from Monitor_test (38 ms total)
> 
> [----------] Global test environment tear-down
> [==========] 2 tests from 1 test case ran. (38 ms total)
> [  PASSED  ] 2 tests.


The purpose of this PR was initially to create a test to uncover a bug that some people in our team went through.
I personally never had the problem on my machine, but I know that @IPeterlik had it for instance.
It would be interesting to investigate deeper into this issue, but without being able to reproduce it on my workstation, I don't really know how I could do it. :/

**Comment by guparan** [comment]
[ci-build]

**Comment by guparan** [comment]
Test is fixed. Failure was due to the fact that test values were generated before c81e4b73f24c2272e9346be3b5c0a1756ecdca59.

**Comment by marques-bruno** [comment]
👍

**Pull request merged**
