### PR TITLE
[tests] Update code base to use the new gtest macro and avoid depecations warnings.

### PR DESCRIPTION
**Pull request by damienmarchal**
…ion warning.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by guparan** [comment]
[ci-build][with-all-tests]

**Comment by damienmarchal** [comment]
It is weird. On my PC I have a lot of warning related to deprecation of gtest features while on the CI I see none of them. Anyone can explain ?

**Comment by damienmarchal** [comment]
This PR is fast-merge and pass everything. Any volunteer ?

**Comment by damienmarchal** [comment]
fred roy set it to ready :)

**Pull request merged**
