### PR TITLE
[Simulation.Core] Remove useless and annoying timers

### PR DESCRIPTION
**Pull request by alxbilger**
Useless:

For example, the timer in `UpdateMappingVisitor::processMechanicalMapping` does not measure anything.

Annoying:

I don't think it is a good practice to add timer on individual components. In particular, the ones I removed measure neglectable durations. The fact that there is one timer for every component adds a lot of pollution in the analysis of the timings, for nothing because it is neglectable.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Review by epernod — CHANGES_REQUESTED** [review]
why useless? because they are always instantaneous?
could you just put a description on why useless and annoying

**Comment by alxbilger** [comment]
@epernod Thanks for the review. I added a description on the PR

**Review by epernod — APPROVED** [review]
ok, trust in your profiling experience !

**Pull request merged**
