### PR TITLE
[git] Add various temporary files to .gitignore

### PR DESCRIPTION
**Pull request by ScheiklP**
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by epernod** [comment]
I'm not sure adding the .comp is a good idea, some of them have been created for the scene example and could change. 
Normally your .comp files should be hosted outside of SOFA sources. You can specify the path inside the PreComputedConstraintCorrection using the Data: fileCompliance (or something like that)

**Comment by fredroy** [comment]
> I'm not sure adding the .comp is a good idea, some of them have been created for the scene example and could change. Normally your .comp files should be hosted outside of SOFA sources. You can specify the path inside the PreComputedConstraintCorrection using the Data: fileCompliance (or something like that)

Actually this is the purpose of this PR, to ignore .comp (among others) files to be considered by git.

**Comment by epernod** [comment]
> > I'm not sure adding the .comp is a good idea, some of them have been created for the scene example and could change. Normally your .comp files should be hosted outside of SOFA sources. You can specify the path inside the PreComputedConstraintCorrection using the Data: fileCompliance (or something like that)
> 
> Actually this is the purpose of this PR, to ignore .comp (among others) files to be considered by git.

Sorry my answer was: I'm not sure adding the .comp into the gitignore file is a good idea

**Comment by alxbilger** [comment]
> > > I'm not sure adding the .comp is a good idea, some of them have been created for the scene example and could change. Normally your .comp files should be hosted outside of SOFA sources. You can specify the path inside the PreComputedConstraintCorrection using the Data: fileCompliance (or something like that)
> > 
> > 
> > Actually this is the purpose of this PR, to ignore .comp (among others) files to be considered by git.
> 
> Sorry my answer was: I'm not sure adding the .comp into the gitignore file is a good idea

@hugtalbot do you have an opinion?

**Pull request merged**
