### PR TITLE
[SofaExporter] Modularize (+minor dependency cleaning)

### PR DESCRIPTION
**Pull request by damienmarchal**
Hey, 

Waiting for FOSDEM to start...so let's make a small cleaning PR. 

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by epernod** [comment]
Thank you for your contribution. Could you please check the CI , I think there is à problem

**Comment by epernod** [comment]
Thank you for your contribution. Could you please check the CI , I think there is à problem

**Comment by damienmarchal** [comment]
Hi Erik, 

Thanks for the feedback. I reorder the SofaGUI Cmake inclusion order to have it compiling.

**Comment by epernod** [comment]
what is the goal here in fact? to put all exporter as a plugin in a next PR?
I don't understand the class move from modules/SofaExporter/ to modules/SofaExporter/src/SofaExporter/

**Comment by damienmarchal** [comment]
Hello Erik,

As said in the PR description. This PR is converting the code into a properly package module/plugin. 
The move of the files is to enforce package encapsulation.

Currently in Sofa a module/plugin that can be search through the find_package() CMake macro. A lot of 
modules are exporting "{CMAKE_CURRENT_DIRECTORY}../" when they are imported. 
Example:
    SofaExporter 
    SofaPython

If a third module SofaX is just doing find_package(SofaExporter) it is possible to write
```#include <SofaExporter/aaa.h>```
which is expected....but also 
```#include <SofaPython/bbb.h>```
This work because of the ../ in SofaExporter allows the SofaX to include SofaPython which is bad as this breaks package encapsulation.  

The solution to fix that is to have the files to include in a subdirectory of the module/plugin. 
So in our case SofaExporter is exporing its include path as "{CMAKE_CURRENT_DIRECTORY}/src/"
If done that we... the SofaX module can still do
```#include <SofaExporter/aaa.h>```
But the ```#include <SofaPython/bbb.h>``` will fails.

**Comment by VLinternship** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
I'm a bit confused about config.h inclusion pipeline. Could you explain the necessity of having both initModule.h and config.h headers?
see #904

**Comment by damienmarchal** [comment]
To me these have two totally different usages.
 
config.h is containing the different parameters related to the module...and it should be included in every .h of a module because this is where the SOFA_MODULE_API is implemented.

Appart from that is the initModule.cpp/initModule.h which contains the defintion/declaration for functions needed to intialize the module.

In the past initModule.h  was containing the initModule() function...but when it is a real plugin we are using the Plugin API and dlopen for that. If we want to allow people to use the module without using the dynamic library we add into initModule.h the declaration of the "C" function that are in initModule.cpp

**Comment by untereiner** [comment]
Hi guys :)
You could let cmake generate for you for each module the config.h (basically only defines for import/export symbols rules, If I am right) using [generete_export_header](https://cmake.org/cmake/help/v3.7/module/GenerateExportHeader.html).

**Comment by damienmarchal** [comment]
Hi @untereiner, thanks for the tip.

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests]

**Pull request merged**
