### PR TITLE
[SofaSPHFluid] Fix invalid plugin initialization.

### PR DESCRIPTION
**Pull request by damienmarchal**
All tests scenes are now failing because we cannot load the SofaSphFluid plugin. 
This fix should helps ;) 

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
[ci-build] [with-scene-tests] 😉

**Comment by damienmarchal** [comment]
Ok so it seems it solves the problem. Let's wait the result on macos & windows before merging.

**Comment by bcarrez** [comment]
Due to CI lags and huge waiting times, I approve the merge of this PR right away...

**Comment by damienmarchal** [comment]
Upon's Bruno's agreement. I merged :)

**Pull request merged**
