### PR TITLE
[extlibs] update nlohmann_json parser

### PR DESCRIPTION
**Pull request by damienmarchal**
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build][with-scene-test][with-regression-tests]

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests][with-regression-tests]

**Comment by jnbrunet** [comment]
Hey @damienmarchal ,

Thanks for this PR.

Shouldn't we just pull this from git directly  (as we are doing for SP3) ? This project seems quite active, and we could pull a stable tag. See also [here](https://github.com/nlohmann/json#embedded-fetchcontent).

Edit:
They are also supporting quite a lot of [package managers](https://github.com/nlohmann/json#package-managers). We could also remove it from SOFA and do as we are doing for Eigen, boost and all.

**Comment by damienmarchal** [comment]
Doing the same as for Eigen, boost is definitely the way to go. Given that I want to stay focused on other tasks I let anyone with free time to do that nicer move. And if no one has time..then I suggest merging the updated version.

**Pull request merged**
