### PR TITLE
[LinearAlgebra] Explicit instantiations and extern template for some matrices

### PR DESCRIPTION
**Pull request by alxbilger**
BlockDiagonalMatrix, BlockFullMatrix and BlockVector are now explicitly instantiated with extern template. This leads to compilation problems that have been fixed (missing includes, missing parameters in `asub` etc)

BlocFullMatrix has been deprecated in order to rename it to BlockFullMatrix.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by damienmarchal** [comment]
Thanks for the PR @alxbilger,

Looks good to me. 
More generally I'm very surprised we didn't notice performance drop by have more and more explicit template instantiation. To me this is an indication that either the lto/gto are now very efficient or that our old code without the explicit template instantiation was not optimized by the compiler as we were expecting.

**Comment by alxbilger** [comment]
LTO is not activated by default on compilers.
@damienmarchal Do you recommend to get rid of some explicit instantiations?

**Comment by damienmarchal** [comment]
Hi @alxbilger 

I think that what compiler's developers consider as "default" shouldn't have any consequence in our code architecture and thus, I'm 100% convinced it is way better to set the properly the compilation parameters to cope with a default compiler option compare to increase the dependency graph (#include) or code complexity.

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Pull request merged**
