### PR TITLE
[all] Add parsing for Python repr in addition to the sofa one.

### PR DESCRIPTION
**Pull request by damienmarchal**
This is an attempt to refactor from PR #332 to make it non breaking. 

No need for review now this is in WIP. 

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests]

**Comment by damienmarchal** [comment]
It is such a pain to have left unfinished stuff...now it is time to restart them.

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by guparan** [comment]
Do you agree to close this one @damienmarchal ?

**Comment by damienmarchal** [comment]
Well, this is a very long standing PR. I put that into postpone.

**Pull request closed without merging**
