### PR TITLE
[SofaGuiQt] Fix: several QWidget do not have a parent

### PR DESCRIPTION
**Pull request by epernod**
This fixes the problem of closing runSofa while window like pluginManager or VisitorWindow being open and not killed when main application stop.

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hello I think the QDocBrowser also miss this.

**Comment by damienmarchal** [comment]
Next :)

**Comment by epernod** [comment]
Done for QDocBrowser, wait for CI I didnt recompiled the branch on my computer...

**Comment by damienmarchal** [comment]
Thanks you Erik for this useful PR.

**Pull request merged**
