### PR TITLE
[runSofa] ADD infinite iterations option to batch gui

### PR DESCRIPTION
**Pull request by m4n4n**
On running the command: bin/runSofa -g batch -n infinite
infinite iterations will start and time computed after every 1000 iterations will be echoed.
Solving the issue #552 

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
Hey @m4n4n,

Thanks for your updated PR!

Did you check this remark from @tgaugry on your previous PR?
> I kinda see what you went through. The argument parser isn't that intuitive TBO.
> 
> I recently had to do a similar task, so if you still want the "infinite" flag, you can check this [line](https://github.com/tgaugry/sofa/commit/326f4f4c8fea61783e40225cb4abac648e569922#diff-5904f9a1380b53f6de2fdc644b6b1a48R112)  and the `parseSkipOption` function in the same file. 
> Maybe this would solve your problem ?

It would indeed be better to not allow a `-1` value to the `n` option but instead to create a new option like `-infinite`. It doesn't have to be a value of the `n` option ;-)

**Comment by guparan** [comment]
Let's [ci-build] this anyway :+1:

**Comment by m4n4n** [comment]
@guparan Yes I did and I have included that function so now the command is:
bin/runSofa -g  batch n infinite
I have just used nbIter=-1 for computational purposes.

**Comment by gaurab4163** [comment]
@m4n4n @guparan These lines of code:
https://github.com/m4n4n/sofa/blob/7a0b89cb0c9420930a862312466c8f7bfdcc218a/applications/sofa/gui/BatchGUI.cpp#L55-L63
is duplicated in `else` condition following it. Wouldn't it be better to refactor it so they appear only once?

**Comment by guparan** [comment]
Indeed, @m4n4n could you try to refactor your code to avoid this big duplication?

**Comment by m4n4n** [comment]
@guparan Sure, on it.

**Comment by guparan** [comment]
Thanks, that's a start but not quite refactored. Here is a proposal (not tested):
```cpp
int BatchGUI::mainLoop()
{
    if (groot)
    {   
        bool infiniteLoop = (nbIter == -1);

        if (infiniteLoop)
        {   
            msg_info("BatchGUI") << "Computing " << nbIter << " iterations." << msgendl;
        }
        else
        {
            msg_info("BatchGUI") << "Computing infinite iterations." << msgendl;
        }

        sofa::helper::AdvancedTimer::begin("Animate");
        sofa::simulation::getSimulation()->animate(groot.get());
        msg_info("BatchGUI") << sofa::helper::AdvancedTimer::end("Animate", groot.get()) << msgendl;
        //As no visualization is done by the Batch GUI, these two lines are not necessary.
        sofa::simulation::getSimulation()->updateVisual(groot.get());
        sofa::simulation::Visitor::ctime_t rtfreq = sofa::helper::system::thread::CTime::getRefTicksPerSec();
        sofa::simulation::Visitor::ctime_t tfreq = sofa::helper::system::thread::CTime::getTicksPerSec();
        sofa::simulation::Visitor::ctime_t rt = sofa::helper::system::thread::CTime::getRefTime();
        sofa::simulation::Visitor::ctime_t t = sofa::helper::system::thread::CTime::getFastTime();

        signed int i = 2; // one simulation step is animated above
        while(infiniteLoop || i <= nbIter)
        {
            sofa::helper::AdvancedTimer::begin("Animate");
            sofa::simulation::getSimulation()->animate(groot.get());
            //As no visualization is done by the Batch GUI, these two lines are not necessary.
            sofa::simulation::getSimulation()->updateVisual(groot.get());

            if(infiniteLoop && i % 1000 == 0 || i == nbIter)
            {
                t = sofa::helper::system::thread::CTime::getFastTime()-t;
                rt = sofa::helper::system::thread::CTime::getRefTime()-rt;
                msg_info("BatchGUI") << i << " iterations done in " << ((double)t)/((double)tfreq) << " s ( " << (((double)tfreq)*i)/((double)t) << " FPS)." << msgendl;
                msg_info("BatchGUI") << i << " iterations done in " << ((double)rt)/((double)rtfreq) << " s ( " << (((double)rtfreq)*i)/((double)rt) << " FPS)." << msgendl;    
                
                if(infiniteLoop)
                {
                    msg_info("BatchGUI") << "Press Ctrl + C (linux)/ Command + period (mac) to stop " << msgendl;
                }
            }

            i++;
        }
    }
    return 0;
}
```

**Comment by m4n4n** [comment]
@guparan Thank you for the help. I have refactored it accordingly. It is also able to handle the case for number of iterations set to 1.

**Comment by guparan** [comment]
You are right about the case of 1 iteration. I broke it by starting `i` to 2. Handling the 1 iteration case differently is a bit overkill though.

Here is my update (still not tested):
```cpp
int BatchGUI::mainLoop()
{
    if (groot)
    {   
        if (nbIter != -1)
        {   
            msg_info("BatchGUI") << "Computing " << nbIter << " iterations." << msgendl;
        }
        else
        {
            msg_info("BatchGUI") << "Computing infinite iterations." << msgendl;
        }
        
        sofa::helper::AdvancedTimer::begin("Animate");
        sofa::simulation::getSimulation()->animate(groot.get());
        msg_info("BatchGUI") << "Processing." << sofa::helper::AdvancedTimer::end("Animate", groot.get()) << msgendl;
        // As no visualization is done by the Batch GUI, these two lines are not necessary.
        sofa::simulation::getSimulation()->updateVisual(groot.get());
        sofa::simulation::Visitor::ctime_t rtfreq = sofa::helper::system::thread::CTime::getRefTicksPerSec();
        sofa::simulation::Visitor::ctime_t tfreq = sofa::helper::system::thread::CTime::getTicksPerSec();
        sofa::simulation::Visitor::ctime_t rt = sofa::helper::system::thread::CTime::getRefTime();
        sofa::simulation::Visitor::ctime_t t = sofa::helper::system::thread::CTime::getFastTime();
          
        signed int i = 1; // one simulation step is animated above  
       
        while (i <= nbIter || nbIter == -1)
        {
            if (i != nbIter)
            {
                sofa::helper::AdvancedTimer::begin("Animate");
                sofa::simulation::getSimulation()->animate(groot.get());
                //As no visualization is done by the Batch GUI, these two lines are not necessary.
                sofa::simulation::getSimulation()->updateVisual(groot.get());
            }

            if ( i == nbIter || (nbIter == -1 && i%1000 == 0) )
            {
                t = sofa::helper::system::thread::CTime::getFastTime()-t;
                rt = sofa::helper::system::thread::CTime::getRefTime()-rt;

                msg_info("BatchGUI") << i << " iterations done in " << ((double)t)/((double)tfreq) << " s ( " << (((double)tfreq)*i)/((double)t) << " FPS)." << msgendl;
                msg_info("BatchGUI") << i << " iterations done in " << ((double)rt)/((double)rtfreq) << " s ( " << (((double)rtfreq)*i)/((double)rt) << " FPS)." << msgendl;
                
                if (nbIter == -1) // Additional message for infinite iterations
                {
                     msg_info("BatchGUI") << "Press Ctrl + C (linux)/ Command + period (mac) to stop " << msgendl;
                }
            }

            i++;
        }
    }
    return 0;
}
```

**Comment by m4n4n** [comment]
Okay. I have made the required changes and its working. I should have done this right in the first go, though.

**Comment by guparan** [comment]
Looks good, let's [ci-build][with-scene-tests]

**Pull request merged**
