### PR TITLE
[SofaGeneralEngine] Improve mesh barycentric mapper engine

### PR DESCRIPTION
**Pull request by coolteemf**
Changed input variable name "InputMeshName" of MeshbarycentricMapperEngine to "topology" for added clarity
Modified label descriptions of MeshbarycentricMapperEngine variables for added clarity
Added a parse function to warn about the name change of InputMeshName
Added an example scene for this component

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hi @coolteemf 

Thanks for your PR. The change of name for "topology" is legitimate and unify this component with the convention used in other component. You also did great by using the parse method to provide user feedback. 

In Refine2mesh you commented a lot of code, could you explain a bit ? 
Because the general coding guidelines is that either the code is broken/invalid/deprecated and should be really removed or refactored or it is valid then it should be keept.

**Comment by coolteemf** [comment]
Hello @damienmarchal It seems this file was included by mistake.
The code was commented because it didn't compile but I didn't mean to put it in the pull request.
Only the commits about SofaGeneralEngine should have been there.
Thank you for the feedback

**Comment by damienmarchal** [comment]
Looks ok to me. @hugtalbot I let you set it to ready & fast-merge.

**Comment by coolteemf** [comment]
@hugtalbot Thank you very much for your help

**Pull request merged**
