### PR TITLE
[SofaKernel] Fix for windows MSVC build, issue 561

### PR DESCRIPTION
**Pull request by ErwanDouaille**
[WIP]
- I try to figure out how to fix the issue : https://github.com/sofa-framework/sofa/issues/561

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by ErwanDouaille** [comment]
[ci-build][with-scene-tests]

**Comment by ErwanDouaille** [comment]
[ci-build][with-scene-tests]

**Comment by ErwanDouaille** [comment]
Looks good ! Fast merge tag ?

**Comment by guparan** [comment]
Why don't we just use `Utils::getSofaPathPrefix()`? It actually does what we want x)  
Makes me think that the macro solution is overkill.

**Comment by ErwanDouaille** [comment]
@guparan because no one mention it during the meeting :'(
I will have a look on it this afternoon

**Comment by ErwanDouaille** [comment]
Close this PR, better solution here : https://github.com/sofa-framework/sofa/pull/568

**Pull request closed without merging**
