### PR TITLE
[runSofa] Add functionality of command for infinite iterations solving issue #552

### PR DESCRIPTION
**Pull request by m4n4n**
This solves the issue : [runsofa] -a -n conflict for batch #552
In case to run infinite iterations, the command to be run in command line is: 
 bin/runSofa -g batch -n -1

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by tgaugry** [comment]
Any reason to do this instead of adding a flag `--infinite-run` or similar ? `-1` is a bit counter-intuitive.

**Comment by m4n4n** [comment]
I wanted to pass on a flag after -n in a format such as -n infinite.
However, the general syntax constituted of a number after -n, such as: -g batch -n 20 (for 20 iterations).
Therefore the variable storing it was declared as an integer one and a lot of compilation errors came up when I tried to change to string variable and later on validate it for a digit or string.

**Comment by tgaugry** [comment]
I kinda see what you went through. The argument parser isn't that intuitive TBO.

I recently had to do a similar task, so if you still want the "infinite" flag, you can check this [line](https://github.com/tgaugry/sofa/commit/326f4f4c8fea61783e40225cb4abac648e569922#diff-5904f9a1380b53f6de2fdc644b6b1a48R112)  and the `parseSkipOption` function in the same file. 
Maybe this would solve your problem ?

**Comment by guparan** [comment]
Hi @m4n4n 
Did you have the time to rework this branch to base it on SOFA master as we discussed on Gitter?

**Comment by m4n4n** [comment]
I was busy studying about Pulse this weekend. Working on it currently. Will come up with a PR in the next couple of days.

**Comment by guparan** [comment]
See #613 for updated version.

**Pull request closed without merging**
