### PR TITLE
[SofaGuiQt] Multiple selection of timers in the profiler

### PR DESCRIPTION
**Pull request by alxbilger**
It is possible to select multiple timers to be displayed in the chart through checkboxes

multipleSelection

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by epernod** [comment]
yeah, happy to see the profiler is used!
Nice improvement!  I hope one day we will be able to display consumption per thread!!

**Comment by alxbilger** [comment]
> yeah, happy to see the profiler is used!
> Nice improvement! I hope one day we will be able to display consumption per thread!!

That is also something in my mind

**Comment by alxbilger** [comment]
@epernod Would you like to test this PR?

[ci-build][with-all-tests]

**Comment by epernod** [comment]
The new feature works smooth and fine. I just found a small bug when unchecking the last substep.
At start, there are 2 lines:  "Full animation" and a "selected substep":
snap01

When selecting a new one. the "unselected" line is still there
snap02

Then when unchecking everything, the last check step remind active. 
snap03

**Comment by epernod** [comment]
Note that for me this is a minor non-blocking bug. If you don't have time I prefer to have the feature merged now even if not perfect than waiting.

**Comment by alxbilger** [comment]
@epernod thanks for having taken the time to test this feature, and reporting the bug

**Pull request merged**
