### PR TITLE
[SofaPython] light module reload

### PR DESCRIPTION
**Pull request by matthieu-nesme**
Enforcing python module reload (to use their eventual modifications).

Note it could easily be added manually to the scene we are working on rather than doing it automatically at each scene loading.

Based on @damienmarchal code!!!

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings nor unit test failures.
- [x] does not break existing scenes.
- [x] does not break API compatibility.
- [x] has been reviewed and agreed to be transitional.
- [x] is more than 1 week old.
- [x] #204 is merged

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hi mathieu,

The provided code force a reload of the dependencies *each* time the runFile function is called. 

I see two problem with this approach: 
 - there is a  large 'un-needed' overhead that will be linear with the number of  PythonScriptController in the scene as well as in the amount of modules to reload (the depth of import dependency graph). 

-  there is *possibly* memory problems here. Let's me explain, normally all PythonScriptController are binded to functions that are from the same module set (the groupe of imported modules), this is made possible because python is caching the imported modules.  In the PR we flush the module set at each runFile so each PythonScriptController will be binded to its own reloaded ("private") version of the module. 


So for the moment I think that adding a single PythonEnvironment object automatically in a scene with a cleanup function to unload the module will be either conceptually cleaner and more efficient. 

EDIT: What do you think about the idea of having the PythonEnvironment as an object in the scene ? I can easily code that but if you don't think it good I don't want to waste time.

**Comment by matthieu-nesme** [comment]
Indeed I have not think of pythonscriptcontrollers importing other files.

But it should be easy to move this code in loadSceneWithArguments rather than in runFile.
I'll do it tomorrow.

**Comment by damienmarchal** [comment]
Using  loadSceneWithArguments only works for scene made with python. 
Maybe there exists a function in SofaPython for that task but I don't see one.

**Comment by matthieu-nesme** [comment]
You are right (once again).
I just pushed a new proposition where nothing is done in your back anymore.
You simply have to call `SofaPython.unloadModules()` manually where you want unload the modules.

**Comment by damienmarchal** [comment]
This approach exhibit the same behavior as the one previously done in runFile with the difference that you will need to add manually the unload somewhere in your scripts. If you have a lot of scripts this can quickly become really annoying and requires ppl to be aware of these subtilities. 

You never answered to my suggestion about having an object in the scene graph dedicated to this task... Eg: ```<PythonEnvironment deepreload="true"/> ```

This 'global' approach looks much cleaner than any per-script approach, it can be automatically be added etc...

**Comment by matthieu-nesme** [comment]
By adding the line manually, you do exactly what you want/need, nothing is done in your back, no overhead in added in the general case. Modules only need to be reloaded while developing our own module, so better to stay focus on this use case and not to try to do to much. Basically you call for unload once at the beginning of you scene (or in your first pythonscriptcontroller) and that's it.
Your python script completely answer my first needs.

Having an extra-component could do the job.

**Comment by matthieu-nesme** [comment]
In the component-based version, please do not create one automatically, let's the user add this component if he wants to reload modules. The best would even be not to touch to pythonenvironment (not to import your script), and that everything happens inside the component. It would require a modification regarding existingModules (because the component will be created after some of the scene imports).

**Comment by matthieu-nesme** [comment]
I pushed an even lighter version, with both a python function and a component.
It does not even require to modify the __import__ function.

**Comment by damienmarchal** [comment]
@matthieu-nesme 
I'm glad you are going to a per-scene approach which is really so much better than the per-script one. 
I actually commited similar code few hours ago in my initial PR :) 

The auto-install of the component is more  a matter of taste on which is not a big deal to me. 

To be more robust I suggest you to enforce that the autoreload component 
to be added at the scene root (easier to see if it is there) and to check that only a single component can be added per scene. 

EDIT: and +1 for not hooking the import anymore.

**Comment by damienmarchal** [comment]
@matthieu-nesme 
If you really want to be able from the script to activate/de-activate the reloading... the proper way of implementing that is to make a python function that adds the <Reload> component in the scene if it does not exist. Such implementation will be safe to use for the users compared to calling the __uninstall__ stuff as the existing approach do. 

In case of several calls to the doReload function from multiple python script may even return a nice message warning the user that what he is doing is 'not needed'. 

EDIT: I will give this version a try in this PR.

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by guparan** [comment]
[ci-build]

**Comment by guparan** [comment]
I'm afraid this PR was merged to fast.
- windows7_VS-2013_options_amd64 has 3 more test failures
- we don't know what happens for centos_clang-3.4_options and mac_clang-3.4_options
- there is 36 new test errors for centos_clang-3.4_options on origin/master after merge

**Comment by damienmarchal** [comment]
Yes I was really surprised you merged this one. 
You probably have to revert so that we have one more week to fix things.

**Comment by matthieu-nesme** [comment]
Indeed. I understand the problem, the mechanism also unloads the plugin's modules defined in c++. This modules are added to the sofa python environment while loading the plugin, so they cannot be imported again after being unloaded. I'll fix that.

**Comment by matthieu-nesme** [comment]
can we unmerge/revert the PR w/o deleting it?

**Comment by damienmarchal** [comment]
I reverted it to minimise the number of ppl having problem. ... 
I assume that now you need to make a new PR (maybe from a different branch name).

**Comment by matthieu-nesme** [comment]
new PR : #214 (using the same branch)

**Pull request merged**
