### PR TITLE
[SofaKernel] Add PerComponentLoggingMessageHandler to keep and history of messages.

### PR DESCRIPTION
**Pull request by damienmarchal**
Let's start from the begining. 

By default the msg_ api does not stores the messages because in some context of use it is not needed while in some other it is (in a non graphical sofa vs in a sofa GUI). 

Thanks to the MessageHandler class it is easy to add custom message storage that fits the application's needs.
 
Currently the existing LoggingMessageHandler can be used to store in a single storage queue the messages. The queue can be queried to get the messages for whatever the application developer want to do with them (displaying them in GUI or showing a long history, ...)

In serr/sout API a different scheme is used as the history is stored at the Base object level in a (size increasing) string. This behavior is now possible with the PerComponentLoggingMessageHandler.
This behavior is closer to the existing serr/sout but it also have several improved properties:
- the message are really stored (not just the 'text' description);
- no text concatenation (memory resize, memory copy) at each message,   
- the queue size of each component can be controlled with a data field as well as the message type to store or to ignore in the queue. 
- when the handler is not installed...there is not recording of the message...so there is a computation & memory zero cost. 

NB: The d_msgLevel and d_logLevel in Base* are only there for discussion but they are currently unused now. 

There PR also contains several new tests. 

Checklist to be merge: 
  - [x] succeed on each compilation setup on the CI.
  - [x] does not generates new test failure. 
  - [x] does not seems to break existing scenes. 
  - [x] does not seems to break API compatibility.  
  - [x] introduces new component with tests & documentation. 
  - [ ] is now 1 week old and no one send a 'no go' comment.

### CODE REVIEW

**Comment by guparan** [comment]
Thank you Damien for this PR.
Is it still a WIP or can we merge?

**Comment by damienmarchal** [comment]
Hi guillaume,

You can merge it.

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by guparan** [comment]
[ci-build] (sorry)

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by matthieu-nesme** [comment]
Super good initiative!

- these message handler should replace existing buffers. They should be removed because handling history with an handler is a way better idea. But the distributed gui should then use this new mechanism to print log history in the component widgets.

- please stop adding Data in Base!

**Comment by thomas-lemaire** [comment]
Some functionalities introduced by this PR looks redundant to the existing printLog data, and can replace it with great advantage.

Moreover, the current usage of this printLog data varies from one component to an other, and could be cleaned in the same time.
Maybe a sdebug stream (in addition to sout, serr) could be introduced to cover some of the misusage of the printLog data.
Initially, printLog is to print or not the component messages to the standard output

**Comment by damienmarchal** [comment]
Thanks  for your feedbacks. 

@matthieu-nesme I agree with you about adding Data to base. This was discussed in
issue https://github.com/sofa-framework/sofa/issues/44 for which there was no clear conclusion so I still have no clear idea on what to do. My current thinking is that fundamentally Data are good (among other things they are a big part of the sofa UIs as well as offer saving capabilities)...the problem is that their init cost is too high. Instead of not using them shouldn't we accelerate that ? (To restart the discussion I have added few benchmark to the issue https://github.com/sofa-framework/sofa/issues/44). 

@thomas-lemaire You are totally right about the printLog. Actually this was my long term target. But as I didn't wanted to break everything I just set-up the foundation of an alternative in this PR, to have your feedbacks, try the feature on few component then do the changing and cleaning all around in a second PR. Could we pursue the discussion in a dedicated issue (https://github.com/sofa-framework/sofa/issues/160) to define how we should do the general cleaning.

**Comment by damienmarchal** [comment]
@matthieu-nesme 

I looked back to the PR and I will remove the three Data field because:
   - controlling the queue size with a Data is not crucial. I will replace it with an attribute and get/set or an environment variable. 
   - the msgLevel is un-used and was there to rise discussion on whether or not controlling the level of messages emitted by an object make sense (eg when debugging). 
   - the logLevel'one is un-used yet but should one day override the behavior of the mis-used f_printLog.  
   
Thanks again to pointing that.

**Comment by thomas-lemaire** [comment]
good, I like the direction it takes 

I think if we (you ?-) add additionnal sXyz component stream (like at least sdebug, or a new component API to match the existing msg_Xyz API), we could then have the printLog data deprecated and replaced by msgLevel and start the transition. 

The removal of the per component "message buffer" has to be done in // in the gui and can be viewed as a separate problem. This would be the responsibility of the GUI to create those per component buffers 

thomas 

----- Mail original -----

**Comment by damienmarchal** [comment]
@thomas-lemaire I think that adding sdebug is for a different PR.

**Comment by matthieu-nesme** [comment]
I think that it is a good idea to treat the overall pb, not to miss something.
- removing msg buffers from Base
- removing printLog Data (but reading it from a parse function for backward compatibility.
- no need for sdebug, you can directly use msg_debug (or whatever). serr/sout can be kept not to become crazy, but no need to add more.
- It should be powerful enough to move some of the Data you added in Base directly in the msghandler (and set more globally these parameters).
- updating the gui to use the new msghandler buffers.

Something else ?

**Comment by thomas-lemaire** [comment]
The advantage of a component specific macro/stream (like sdebug to stay in the current spirit) would be to automatically add the component as the "sender" of the message. 
Which is BTW required by the gui to get and display messages coming from a given component. 

----- Mail original -----

**Comment by damienmarchal** [comment]
As asked I removed the Data in base. 

Now here is my working plan regarding all that ordering all the feedback received: 
   - PR0: was implementing a per component logging system on top of the msg_api to prove we can replace the existing error logging system. This was done in this PR.

   - PR1: with the introduced system to replace the existing logging of error (this PR is risky and touch a lot of file) it should contains: 
          - removing the filling of the messages in sout.
          - removing the old string based buffer (API BREAK). 
          - removing all the uses of the old message buffers and replace them with the new one (API BREAK). 
          - updating the gui to use the new msghandler buffers.

   - PR2: removing the printLog Data:
         - backward compatibility solution must be implemented. 
         - a replacement solution has to be implement to control the printing.
         - a replacement solution has to be implement to control the messages based on a per-component selection of the printed messages 

   - PR3: extending/unifying the sout/serr with more sdebug/swarning.  This must be discussed seriously during a meeting because I currently made a lot of attempts to this but didn't managed to implement a working solution without the sever flawn sout/serr have. If you have ideas on that please make a branch with working proposal so that we have sounded discussion. 

Anyone interested in working on PR1, PR2 and PR3 ?

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Pull request closed without merging**
