### PR TITLE
[SofaKernel] use string in base object description. 

### PR DESCRIPTION
**Pull request by damienmarchal**
This PR is based on #853 despite there is not real connection. 
I was to lazy to swtich branch

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by guparan** [comment]
Is this breaking for external users?

**Comment by epernod** [comment]
Indeed.. maybe keep a setAttribute (const char* ) that emit a deprecated warning and calling internally the setAttribute (std::string) ?

**Comment by damienmarchal** [comment]
If you want to do that i recommend the systematic use of https://en.cppreference.com/w/cpp/language/attributes/deprecated

**Review by epernod — APPROVED** [review]

**Pull request merged**
