### PR TITLE
[SofaKernel] Remove X11 dependency when SOFA_NO_OPENGL is enabled.

### PR DESCRIPTION
**Pull request by jnbrunet**
SOFA with OpenGL adds a X11 dependency. If we compiled SOFA without OpenGL, this dependency was still there, which caused problem when compiling for a headless system (no X11 and no GL).

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by fredroy** [comment]
I obviously strongly approve this PR, I would even go further and remove the glfont functions that nobody uses (and therefore totally remove the X11 dep)

**Review by fredroy — APPROVED** [review]

**Comment by jnbrunet** [comment]
@fredroy there you go, I'll remove the fast-merge as it now becomes a little bit more dangerous.

**Review by epernod — APPROVED** [review]

**Comment by damienmarchal** [comment]
Hi @hugtalbot  
Didn't we set this PR to ready last dev-meeting ?

**Comment by jnbrunet** [comment]
> Hi @hugtalbot
> Didn't we set this PR to ready last dev-meeting ?

He did
image

Now you just have to push this button:

image

**Pull request merged**
