### PR TITLE
[All] Almost green dashboard

### PR DESCRIPTION
**Pull request by epernod**
Fix scene crashing and regression tests
Still 3-4 voluntary failing unit tests.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Comment by fredroy** [comment]
Thanks a lot 👍
Quick review of what you have corrected:
 - ExtVec3f -> Vec3d
 - ShapeFunctiond ->ShapeFunction3d
 - mssing RequiredPlugins (😳)
 - new scenes (split from previous one e.g RemovingTetra2Triangle_options{1,2}.scn 
 - fixed ReadTopology
 - removed caduceus from regression. Could you say why?
 
 Other than that, I 💯 this PR 🙂

**Comment by epernod** [comment]
> 
>     * removed caduceus from regression. Could you say why?
> 

yes sorry, I put the comment in the commit message:  "[tests] Remove caduceus from the regression test, This scene is not appropriate to test as the resolution seems to depends on the HW for the Gauss Seidel to converge"

**Comment by fredroy** [comment]
> 
> 
> > ```
> > * removed caduceus from regression. Could you say why?
> > ```
> 
> yes sorry, I put the comment in the commit message: "[tests] Remove caduceus from the regression test, This scene is not appropriate to test as the resolution seems to depends on the HW for the Gauss Seidel to converge"

Ah my bad, did not think to check the commits messages

**Pull request merged**
