### PR TITLE
[all] Remove SOFA_FLOAT :)

### PR DESCRIPTION
**Pull request by damienmarchal**
This is just a small test to see if an automated replacement is working  "good" enough. 

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
@damienmarchal Conflicts must be resolved for CI to work :wink:

**Comment by damienmarchal** [comment]
Process:
  - remove all SOFA_WITH_FLOAT sections. 
  - remove the #ifdef SOFA_WITH_DOUBLE line.
  - replace all Vec3dTypes by Vec3Types (and Mass, and other types) with a refactoring tool.

**Comment by damienmarchal** [comment]
New version based on a recent master.

**Comment by damienmarchal** [comment]
No need to this PR anymore...because it was for integration into stc5 branch. I will re-open a new one against master.

**Pull request closed without merging**
