### PR TITLE
[GUI.Qt] Restore Stats (Charts) and DocBrowser for Qt6

### PR DESCRIPTION
**Pull request by fredroy**
Qt6 did not handle QtCharts and QtWebEngine until 6.2 (I think)

This PR restores the two features, and fix the code : some deprecated/changed functions here and there and QtCharts code is no longer in its own namespace.

This PR +  #3454 allow us to have the same feature between Qt5 and Qt6 (and maybe giving up on Qt5 soon)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by damienmarchal** [comment]
Nice.

**Comment by damienmarchal** [comment]
Ready, then merge.

**Comment by damienmarchal** [comment]
It was mergeable as far as I can say :) 
Why are you saying it fails ? I see nothing special on the dashboard.

**Comment by alxbilger** [comment]
I did fail on the master branch. But it seems ok now.

**Pull request merged**
