### PR TITLE
[SofaPython] FIX example broken by PR#459

### PR DESCRIPTION
**Pull request by damienmarchal**
Fix issue #749
https://github.com/sofa-framework/sofa/issues/749

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by epernod** [comment]
Those scenes were not tested? How did you detect the error?

**Comment by damienmarchal** [comment]
Report from users. They tests the example and it does not work;

**Comment by epernod** [comment]
Would it be easy to add theme to the scene tests for future problem detection?
They were not crashing I guess...

**Comment by damienmarchal** [comment]
I don't know...they were not crashing...it was just that the movement on key pressed was not done.

**Pull request merged**
