### PR TITLE
[All] Remove SOFA_SUPPORT_MOVING_FRAMES and SOFA_SUPPORT_MULTIRESOLUTION

### PR DESCRIPTION
**Pull request by damienmarchal**
Changelog:
- remove SOFA_SUPPORT_MOVING_FRAME  (because #ifdef is not the way to implement a feature)
- remove SOFA_SUPPORT_MULTIRESOLUTION   (because #ifdef is not the way to implement a feature)
- move code from .h to .cpp in DefaultCollisionGroupManager

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
DO you know for which case those ifdef where defines?

**Comment by damienmarchal** [comment]
My bet:
because one day someone wanted to implement mutliresolution and per-frame scene graph (to concatenate transformations in the graph's nodes)  but,  probably because it was before the use of git this was done in #ifdef instead of a branch that would have been merged once done. The consequence is this code is not activated anymore despite the feature are of interest.

So if someone needs these features and want to support hem...don't hesitate to take the code, put that on a branch and make a documented pull request.

**Comment by damienmarchal** [comment]
[ci-build][with-all-tests]

**Comment by damienmarchal** [comment]
ready, ready.

**Comment by epernod** [comment]
ugly upstream/master merge ^^
rebase before merge?

**Pull request merged**
