### PR TITLE
[Mapping] Deprecate module Sofa.Component.Mapping.MappedMatrix

### PR DESCRIPTION
**Pull request by alxbilger**
[ci-depends-on https://github.com/SofaDefrost/ModelOrderReduction/pull/145]

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
[ci-build][with-all-tests][force-full-build]

**Review by fredroy — APPROVED** [review]
I would almost directly delete it as it has been at least a year there is nothing of value inside 🤔
I suppose you want to be extra careful and warn people before deleting this module...

**Comment by alxbilger** [comment]
I removed the module from the `Sofa.Component.Mapping` dependencies. I also removed all the files from the module. And there is a warning message if someone uses the module. In conclusion, the module exists only to warn that it should not be used.

**Comment by fredroy** [comment]
> I removed the module from the `Sofa.Component.Mapping` dependencies. I also removed all the files from the module. And there is a warning message if someone uses the module. In conclusion, the module exists only to warn that it should not be used.

Yes that is what I wanted to say 😅 
Just I wanted to say that its content (components) itself was purged already one year ago

**Review by epernod — APPROVED** [review]

**Comment by fredroy** [comment]
[ci-build][with-all-tests][force-full-build]

**Comment by fredroy** [comment]
[ci-build][with-all-tests][force-full-build]

**Pull request merged**
