### PR TITLE
[SofaSimpleGUI] Without compatibility layer

### PR DESCRIPTION
**Pull request by alxbilger**
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Review by fredroy — APPROVED** [review]

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Review by epernod — APPROVED** [review]

**Comment by damienmarchal** [comment]
Ready, merge if CI agrees.

**Comment by alxbilger** [comment]
Scene tests are failing. Back to WIP

**Comment by epernod** [comment]
ok looking at the CI, only tests from plugin are failing because the scene are still requesting to load plugin with old plugin name. I can fix that quickly.

**Comment by alxbilger** [comment]
Wait for https://github.com/sofa-framework/sofa/pull/3351

**Pull request merged**
