### PR TITLE
ADD: method getCategories() returning all SOFA categories

### PR DESCRIPTION
**Pull request by marques-bruno**
A method to return all categories (those defined in CategoryLibrary at least...)

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by epernod** [comment]
What are theses categories used for?

**Comment by marques-bruno** [comment]
That's a very good question....
I think that initially it was used to sort components by categories (Forcefields, masses, collision algorithms, etc.)
There was a binding in SofaPython that was returning the categories associated to a component. Also, a class named SofaLibrary is using CategoryLibrary.
After your comment, a quick search in the sources shows me that SofaLibrary is not used anywhere actually:
- SofaLibrary itself is used nowhere. SofaModeler does hold a pointer to a SofaLibrary, but this pointer is never used antwhere in the code... 
- QSofaTreeLibrary inherits SofaLibrary -> not used anywhere in SOFA

So now that I see that, I vote for removing the CategoryLibrary / SofaLibrary / QSofaTreeLibrary from SOFA altogether.

What do you say?

**Comment by damienmarchal** [comment]
As far as know this is useful (and we use it in python) to get kind of parent class of an object (eg: testing if an object is a FF or a constraint or whatever).

**Comment by marques-bruno** [comment]
OK @damienmarchal, but then it still bothers me that categories seem to be hard-coded in the CategoryLibrary class, and since it's unused in sofa, nothing adds new categories / components to the library through its existing addCategory / addComponent methods...
Maybe we should rethink this framework..?

**Pull request merged**
