### PR TITLE
[all] Clean MechanicalMatrixVisitor

### PR DESCRIPTION
**Pull request by damienmarchal**
Split the content of MechanicalMatrixVisitor in separated files.
The files are located in a subdirectory called mechanicalvisitor/.

#1989
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by guparan** [comment]
@alxbilger I tried to resolve the conflicts by myself. If something is wrong, feel free to reset the branch to https://github.com/sofa-framework/sofa/pull/1992/commits/c37a1d8e9c6e790d54ddabf270b4955d4282be6e and re-merge with master to redo the conflict resolution.

**Comment by alxbilger** [comment]
@guparan Looks good! Thanks
@damienmarchal do you want to check again before the merge?

**Comment by damienmarchal** [comment]
@alxbilger ça me semble ok mais j'ai pas checké le détails des 157 fichiers :)

**Comment by fredroy** [comment]
The tests are happy, so OK for me.

**Comment by epernod** [comment]
Just putting here the list of new visitor!   
   ${SRC_ROOT}/mechanicalvisitor/MechanicalAccFromFVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalAccumulateConstraint.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalAccumulateMatrixDeriv.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalAddMBKdxVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalAddMBK_ToMatrixVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalAddMDxVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalAddSeparateGravityVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalAddSubMBK_ToMatrixVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalApplyConstraintsVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalApplyProjectiveConstraint_ToMatrixVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalBeginIntegrationVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalBuildConstraintMatrix.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalComputeContactForceVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalComputeDfVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalComputeEnergyVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalComputeForceVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalComputeGeometricStiffness.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalEndIntegrationVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalGetConstraintJacobianVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalGetDimensionVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalGetMatrixDimensionVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalGetMomentumVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalIntegrateConstraintVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalIntegrationVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalMultiVectorFromBaseVectorVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalMultiVectorPeqBaseVectorVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalMultiVectorToBaseVectorVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalPickParticlesVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalPickParticlesWithTagsVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalProjectJacobianMatrixVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalProjectPositionAndVelocityVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalProjectPositionVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalProjectVelocityVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalPropagateDxAndResetForceVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalPropagateDxVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalPropagateOnlyPositionAndResetForceVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalPropagateOnlyPositionAndVelocityVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalPropagateOnlyPositionVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalPropagateOnlyVelocityVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalResetConstraintVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalResetForceVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalSetPositionAndVelocityVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalVAllocVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalVAvailVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalVDotVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalVFreeVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalVInitVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalVMultiOpVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalVNormVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalVOpVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalVReallocVisitor.h
    ${SRC_ROOT}/mechanicalvisitor/MechanicalVSizeVisitor.h

**Pull request merged**
