### PR TITLE
[SofaCore] Name dynamically allocated vec ids

### PR DESCRIPTION
**Pull request by alxbilger**
In the scene `examples/Benchmark/Performance/TorusFall.scn`, vectors are dynamically allocated by EulerImplicitSolver and GenericConstraintSolver. They now have a name instead of a meaning less number.

image

The names are not associated to the VecIds, but to the Data associated to the VecIds.

Note: CGLinearSolver allocates dynamically temporary vectors. I did not add any complexity for having names for them, as they are "freed" after each solve. But they are actually not freed, just unset. I suspect its a source of the bug we already met when there are many vecids.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Comment by damienmarchal** [comment]
I suggest pecifying the "group" of the data so thay are not in the default group  "vector" but appears in their own panel.  
Some suggestion for naming (i have no real idea on what is the best one): 
 - "Constraint Vectors"
 - "Free Vectors"
 - "Free States" 
 - "Solver's properties"
 
 Actually, the vectors should also be grouped into something like "States"

**Comment by alxbilger** [comment]
@damienmarchal Excellent suggestion, thanks

**Comment by alxbilger** [comment]
@damienmarchal following your suggestion:

image
image
image

**Pull request merged**
