### PR TITLE
[all] CLEAN topology classes

### PR DESCRIPTION
**Pull request by epernod**
everything is in the title.
This PR: 
- clean some code commented.
- remove the HAVE_NEW_HEXA macro which was hardcoded to true since 2009
- change the NDEBUG topology test into a c++if condition so the code is compiled.

work duplicated with STC#5 branch

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
@guparan good to go, is up to date with stc5 branch.

**Pull request merged**
