### PR TITLE
[SofaMiscCollision] Extract OBB/Capsule code into its own plugin

### PR DESCRIPTION
**Pull request by fredroy**
based on:
- #2813 (which is itself based on #2790 )

All OBB/Capsule code-related into its own plugin.
Has kind of the same file structure as Sofa.Component.Collision.

Tests were adapted as well.

[ci-depends-on https://github.com/sofa-framework/THMPGSpatialHashing/pull/1]
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Comment by guparan** [comment]
Plugin to be externalized in the future?

**Pull request merged**
