### PR TITLE
[applications] remove shadow variable

### PR DESCRIPTION
**Pull request by maddin200**
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Review by alxbilger — COMMENTED** [review]
Does it mean `btTransform trans;` is not used at all?

**Comment by maddin200** [comment]
no just renaming

**Comment by epernod** [comment]
Yes I think you could remove the `btTransform trans;` created before the loop

**Review by epernod — COMMENTED** [review]
Yes I think you could remove the `btTransform trans;` created before the loop

**Comment by maddin200** [comment]
What is about trans.setIdentity(); ?

**Review by alxbilger — APPROVED** [review]

**Comment by alxbilger** [comment]
[ci-build]

**Pull request merged**
