### PR TITLE
[SofaGeneralAnimationLoop] MechanicalMatrixMapper: adds template

### PR DESCRIPTION
**Pull request by EulalieCoevoet**
The PR just adds the template "Vec1,Vec3" to the component MechanicalMatrixMapper.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hi Eulalie, 

The template instantiation part (in the .cpp) is not synchronized with the extern template part (in MechanicalMatrixMapper.h). 
But we can update that in a separate PR

**Comment by epernod** [comment]
I would add the extern template in the header in this PR. Otherwise we will forgot to add it ;)

**Comment by damienmarchal** [comment]
Actually we already forgot others :)

**Comment by EulalieCoevoet** [comment]
No problem :)

**Pull request merged**
