### PR TITLE
[plugin/SceneCreator] Cosmetic changes and remove un-needed include

### PR DESCRIPTION
**Pull request by damienmarchal**
A lot of cosmetic changes and removes some compilation warning related to unsigned int/int conversion

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings nor unit test failures.
- [x] does not break existing scenes.
- [x] does not break API compatibility.
- [x] has been reviewed and agreed to be transitional.
- [x] is more than 1 week old.
**Reviewers will merge only if all this checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by epernod** [comment]
closed?

**Comment by damienmarchal** [comment]
On 14/02/2017 09:29, erik pernod wrote:
>
> closed?
>
unmerged...because it is minor and I have no time to understand why it 
does not compile... I will open it again one day...
But if you are willing to you can make it work in the meantime :)

**Comment by epernod** [comment]
yes let it open, I'm going to make sceneCreator grow so I take any improvements on it. I will have a look when I have time.

**Comment by guparan** [comment]
I reopen ;)

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Pull request merged**
