### PR TITLE
[all] EDIT: use PluginRepository instead of Utils::getPluginDirectory

### PR DESCRIPTION
**Pull request by guparan**
Following discussions with @fjourdes in #502 

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by fjourdes** [comment]
Many thanks, sorry I did not have any time to take care of it... I just added one commit ( without asking your permission... ) so that `Utils::getPluginDirectory()` returns the content of the first path stored in the `PluginRespository` global variable.

**Comment by fjourdes** [comment]
As you noted, `Utils::getPluginDirectory()` use should be somewhat discouraged, because it offers less functionality compared to `PluginRespository` which can be expanded by an external application, provided it takes the responsibility of defining the content of the environment variable `SOFA_PLUGIN_PATH`

**Comment by damienmarchal** [comment]
[ci-build]

**Pull request merged**
