### PR TITLE
[All] Lifecycle update before v22.06

### PR DESCRIPTION
**Pull request by guparan**
PointConstraint is removed.
serr/sout/sendl are removed.
A lot of headers will now trigger the SOFA_DISABLED_HEADER error if included.

Please review, I may have done bad/brutal things.

[ci-depends-on https://github.com/sofa-framework/Registration/pull/3]
[ci-depends-on https://github.com/sofa-framework/SofaPython3/pull/268]
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
it seems some plugins are still using serr/sendl....

**Review by fredroy — CHANGES_REQUESTED** [review]
we need to uncomment (i.e enable) all the deprecation warning in all headers of Sofa.Compat as well

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Review by fredroy — APPROVED** [review]

**Comment by fredroy** [comment]
I made my own requested changes 😎

**Comment by damienmarchal** [comment]
Of course the PR will be breaking and we will need to update our code base. 
But this is all for the good. 
 
Clearly congratulation @SofaFramework for such high quality management of software evolution.

So if I understand correctly, this will be merge into master the day after the official release of v22.06 right ?

**Comment by fredroy** [comment]
> Of course the PR will be breaking and we will need to update our code base. But this is all for the good.
> 
> Clearly congratulation @SofaFramework for such high quality management of software evolution.
> 
> So if I understand correctly, this will be merge into master the day after the official release of v22.06 right ?

It should be breaking for some yes (the ones who did not do the change of the things flagged deprecated the last version and marked removed now, like the use of sout/serr/sendl)
But it should be merged just before releasing actually, now is the code of v22.06

**Comment by guparan** [comment]
Wow thanks @fredroy for the changes :muscle:

**Comment by guparan** [comment]
Last [ci-build] to unlock the merge button

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Comment by guparan** [comment]
Dashboard is down but status checks are green. Soooo ... ready?

**Review by epernod — APPROVED** [review]

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Pull request merged**
