### PR TITLE
Data update: simplify Data tracking

### PR DESCRIPTION
**Pull request by matthieu-nesme**
Adding a few utility functionalities to simplify Data tracking.

- Data tracking system is now using Data's counter (lighter and simpler).
- externalizing Data tracking system outside of DataEngine so it can be use elsewhere (including other kinds of components).
- adding DataTrackerEngine that is a kind of DataEngine but that is not a component (not a BaseObject). It can easily be added anywhere and can link any Data, such as inside a Component, or even between components.
- adding DataTrackerFunctor to call a functor as soon as a Data is modified.

What you can do: (have a look at the tests)

- check if a Data changed on a regular rhythm. e.g check at each time step if a stiffness parameters changed to update a Matrix.
- automatically update a Data if its dependencies changed. e.g. young modulus can be set as a dependency of stiffness matrix, so each time you ask for the matrix, if the modulus changed, the matrix will be updated (behavior similar to DataEngine)
- do an action as soon as a Data is modified. E.g. updating the gui scene graph as soon as a Node is (de)activated (by tracking the Data Node::activated).

### CODE REVIEW

**Comment by guparan** [comment]
Is this waiting for merge or still a work in progress?

**Comment by matthieu-nesme** [comment]
Waiting for merge.
Should answer every points of the "data update" workgroup (not listed in the issues?).

**Comment by guparan** [comment]
Because "data update" is considered as a background task since STC#2 ;)

**Comment by damienmarchal** [comment]
This PR is connected with:
https://github.com/sofa-framework/sofa/issues/61

I refresh the build to see if this still work then integrate it as no one gave negative feedbacks. 
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by guparan** [comment]
Why did you relaunch builds? They are already in Jenkins queue.

**Pull request merged**
