### PR TITLE
[SofaKernel] Some Topology cleaning...

### PR DESCRIPTION
**Pull request by epernod**
Starting the work of cleaning the topology in Sofa.. resting in peace since 2012...

- Change those methods: now returns unsigned int instead of int: 
  - getEdgeIndex(PointID v1, PointID v2);
  - getTriangleIndex(PointID v1, PointID v2, PointID v3);
  - getQuadIndex(PointID v1, PointID v2, PointID v3, PointID v4);
  - getTetrahedronIndex(PointID v1, PointID v2, PointID v3, PointID v4);
  - getHexahedronIndex(PointID v1, PointID v2, PointID v3, PointID v4, PointID v5, PointID v6, PointID v7, PointID v8);
- Now unfound ID == UINT_MAX instead of -1.
- Change several serr/sout into msg_

In this PR, 2 scene tests are now sending error due to the conversion of serr into msg_error.
This is beacuse some scene test try to do topological change on regularGrid which doesnt support that. I would like to keep those scene error and handle that in a next PR (to split PRs and simplify review process)

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
yes, it is written in the details ;)

**Comment by guparan** [comment]
Not sure about the UINT_MAX used for error handling. How about something like `BaseTopologyObject::INDEX_NOT_FOUND` (secretly equals to UINT_MAX)? Or an exception (cleaner)?

EDIT: There is already a `Topology::InvalidID` :wink:

**Comment by epernod** [comment]
yes but it ends in the same discussion as all the other typedefs that are in sofa::core::topology::Topology {}
You need to inherite or at least include that class to be able to use Topology::InvalidID ... 
Maybe a more generic one in sofa::defaultTypes ?

**Comment by untereiner** [comment]
Maybe put it out of the Topology class wiith something like 
`struct TopologyTraits{
    using InvalidID  = UINT_MAX;
};`

Then you can use it as TopologyTraits::InvalidID;
Same for the other typedefs

**Comment by untereiner** [comment]
A possible option for a first move towards the use of multiple mesh data structures would be to put all the "using" out of the xxxTopologyContainer classes into a traits.

`
template <T>
struct Cell { };
`
`
template <>
struct Cell<SofaBaseMesh> {
   using Vertex = index_type;
   using Edge = index_type;
    ....
};
`

The someone else could write (in a plugin)
`
template<>
struct Cell<MyOwnMeshDataStructure> {
  using Vertex = another_type;
  ....
};
`

**Comment by damienmarchal** [comment]
Ready ?

**Pull request merged**
