### PR TITLE
[SofaNG] Re-organize Framework

### PR DESCRIPTION
**Pull request by fredroy**
big, big fatass PR (because of moves mainly)

~~First, check if not breaking with the CI~~

Cleanup of framework's modules, in the same way as the components.

What have been done in this PR (a picture better than a thousand words)

Screenshot 2022-04-19 at 14 26 58

- no more Sofa.* folder
- all gathered in the same folder
- clean and tidy
- all Simulation modules in a Simulation Folder (no more weird split Sofa.SimulationCore in framework and SimulationCommon/Graph modules)
- all modules names are Sofa.ModuleName (with compat or aliases) 
- not breaking (💦)

# Discussions
- I put all the modules in a Framework but modules name, folders and namespaces (i.e like SofaNG) does not take into account that (and IMO I dont want). Thing is, I would find weird to put those modules directly into the root/ . But it is just an opinion.
- No Sofa.Framework nor Sofa.Simulation meta module (like SofaFramework now). I prefer this way but more opinions are welcome.

****

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Comment by guparan** [comment]
I think we only have 2 ways to keep the CMake/C++ consistency we want:
1. having a `Sofa` directory at repo root containing `Core`, `Components`, etc.
2. having `Core`, `Components`, etc. directly at repo root

I like the idea of having all the Framework related stuff in a subdirectory but you know what it implies: `sofa::framework::core::...`

**Comment by damienmarchal** [comment]
> I think we only have 2 ways to keep the CMake/C++ consistency we want:
> 
> 1. having a `Sofa` directory at repo root containing `Core`, `Components`, etc.
> 2. having `Core`, `Components`, etc. directly at repo root
> 
> I like the idea of having all the Framework related stuff in a subdirectory but you know what it implies: `sofa::framework::core::...`

My suggestion for the final repository layout is from root directory:
- move all plugins from ROOT/applications/plugins into a ROOT/plugins
- move all modules from ROOT/SofaKernel/modules into ROOT/modules (or in ROOT/framework i don't care)
- make Sofa.XXX into ROOT/modules (resp. ROOT/framework)

And the namespace in c++ file start after "plugins", "modules", "framework"  and is fully consistant. So having all Type, Core etc... into Sofa sub-directories.

**Comment by guparan** [comment]
Another suggestion:
```
/
    plugins
        BeamAdapter
        ...
    framework
        Sofa
            Compat
            Config
            Core
            ...
    modules
        Sofa
            Component
                Collision
                ...
    scripts
    tools
    ...
```
but in this case we have 2 Sofa projects which is not possible in CMake, so we would have to find a trick.

I still prefer the solution 1 from my previous comment. It's the cleanest and most consistent.

**Comment by fredroy** [comment]
```
/
    plugins
        BeamAdapter
        ...
    framework
        Sofa
            Compat
            Config
            Core
            ...
    components
        Sofa
            Component
                Collision
                ...
    scripts
    tools
    ...
```
Slight modification but seems to be consensual

**Comment by guparan** [comment]
Final architecture after discussions:
```
/
    plugins
        BeamAdapter
        ...
    Sofa
        framework   <-- this directory is not a CMake target (lower case)
            Compat
            Config
            Core
            ...
        Component
            Collision
            ...
    scripts
    tools
    ...
```

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Comment by fredroy** [comment]
Current form:
Screenshot 2022-05-03 at 09 12 44

**Comment by jnbrunet** [comment]
Can I still ask a small question ? :-) 

Why keeping the Framework directory? Would something like this be simpler?:

```
/
    plugins
        BeamAdapter
        ...
    Sofa
        Compat
        Config
        Core
        DefaultType
        Geometry
        ...
        Component
            Collision
            ...
    scripts
    tools
    ...
```

**Comment by fredroy** [comment]
> Can I still ask a small question ? :-)
> 
> Why keeping the Framework directory? Would something like this be simpler?:
> 
> ```
> /
>     plugins
>         BeamAdapter
>         ...
>     Sofa
>         Compat
>         Config
>         Core
>         DefaultType
>         Geometry
>         ...
>         Component
>             Collision
>             ...
>     scripts
>     tools
>     ...
> ```

like @hugtalbot said, it is to keep the sepearation framework (i.e APIs & stuff) and components (implementations).
Ideally like @guparan we should have made a framework dir/namespace structure but we decided not to break the framework code (so we still have sofa::core, sofa::helper....)

**Pull request merged**
