### PR TITLE
[Flexible] FIX deps to pluginized modules

### PR DESCRIPTION
**Pull request by guparan**
Fix 2 missing deps in Flexible due to pluginization.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Review by epernod — APPROVED** [review]

**Comment by fredroy** [comment]
Interesting, it was not complaining on the CI 🤔

**Comment by guparan** [comment]
Yes and I don't understand why! Fortunately, the nightly-generate-binaries job did complain: https://ci.inria.fr/sofa-ci-dev/job/sofa-custom/566/

**Comment by epernod** [comment]
Do we wait the end of the pluginization of SofaGeneral to see if other dependencies are broken?

**Comment by fredroy** [comment]
Actually, Flexible is supposed to compile without this PR, as SofaValidation (required in the plugin) needs SofaGeneral which contains the other dependencies (SofaGeneralEngine and SofaBoundaryCondition).
So I would say that there is a problem with the nightlies (and the CI is correct)

**Comment by guparan** [comment]
> 
> 
> Actually, Flexible is supposed to compile without this PR, as SofaValidation (required in the plugin) needs SofaGeneral which contains the other dependencies (SofaGeneralEngine and SofaBoundaryCondition).
> So I would say that there is a problem with the nightlies (and the CI is correct)

But SofaValidation does not link on SofaGeneralEngine nor SofaBoundaryCondition :raised_eyebrow:

**Comment by fredroy** [comment]
Thats weird indeed ; well you can just merge your PR, as it will be needed later when I deprecate SofaGeneral

**Pull request merged**
