### PR TITLE
[GeneralTopology] Grid Topologies cleanup + new SphereGrid

### PR DESCRIPTION
**Pull request by epernod**
PR on topologyGrid:

- Add new component: SphereGridTopology to create sphere topo. using grid (similar to CylinderGridTopology) with an example: SphereGridTopology.scn
- Clean the API GridTopology and its children: RegularGridTopology/SphereGridTopology/CylinderGridTopology, move several methods into mother class GridTopology.
- Add doxygen doc for the 4 classes
- Add tests for Cylinder and SphereGridTopology
- Add method addSphere/addRigidSphere in sceneCreator + tests + example

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings nor unit test failures.
- [x] does not break existing scenes.
- [x] does not break API compatibility.
- [x] has been reviewed and agreed to be transitional.
- [x] is more than 1 week old.
**Reviewers will merge only if all this checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Will be merged tomorrow unless someone send a no-go.

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
It seems there is some compilation problems on this PR. 
@epernod can you have a look ?

**Comment by epernod** [comment]
Ok will check that by next dev-meeting.

**Comment by epernod** [comment]
[ci-build]

**Comment by epernod** [comment]
Could someone give me a hint on what is the problem... @guparan or @damienmarchal maybe .
Looking for "error" in the full log give me this:
`..\SofaKernel\framework\sofa\core\..\..\sofa/defaulttype/DataTypeInfo.h(757) : fatal error C1060: compiler is out of heap space
c1xx : fatal error C1063: INTERNAL COMPILER ERROR`

Not sure if this is really the error that breaks the compile and if it is related to my modifications or to the VM used for the build.

**Comment by damienmarchal** [comment]
@epernod Sorry for that I'm quite sure this is not related to your PR. 

EDIT: This week end we were upgrading all windows machine to faster ones. The problem you saw was specific to the memory consumption of vs2013 which, at certain moment larger than the allocated 12GB. This problem problem was solved by adding a larger virtual memory.

**Comment by damienmarchal** [comment]
[ci-build]

**Pull request merged**
