### PR TITLE
[SofaGuiQt] Rename attributes to follow SOFA guidelines.

### PR DESCRIPTION
**Pull request by TanguyNav**

### CODE REVIEW

**Review by alxbilger — APPROVED** [review]

**Comment by alxbilger** [comment]
> looks fine to me, have you run the exec _runSofa_ yourself @alxbilger ?

No, only compiled successfully

**Comment by damienmarchal** [comment]
Tested.. and working :).

**Comment by damienmarchal** [comment]
Can you fast merge Hugo ?

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Pull request merged**
