### PR TITLE
[SofaKernel] mute extlibs warnings

### PR DESCRIPTION
**Pull request by untereiner**
e.g. Eigen among others

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by untereiner** [comment]
[ci-build]

**Comment by guparan** [comment]
Warning (from SOFA-dev meeting): `CMAKE_CURRENT_BINARY_DIR` should be removed from `SOFAFRAMEWORK_DEPENDENCY_INCLUDE_DIRECTORIES `

**Comment by untereiner** [comment]
If I am not wrong the only difference is that it mutes the warnings of CImg and gtest with the `CMAKE_CURRENT_BINARY_DIR` variable in `SOFAFRAMEWORK_DEPENDENCY_INCLUDE_DIRECTORIES`. Why should I drop it ?

**Comment by guparan** [comment]
In this context `CMAKE_CURRENT_BINARY_DIR = <bin_dir>/SofaKernel/SofaFramework`.
Why do we need to add `<bin_dir>/SofaKernel/SofaFramework` as **include** directory?
Sorry to answer your question with another question 😕

**Comment by untereiner** [comment]
Maybe someone should clean all these messy CMakelists ... a task for Sofa NG ? (a new question 😄 )

**Pull request merged**
