### PR TITLE
[SofaKernel] Fix SimpleApi forward declaration of BaseObject and relocatable of Sofa.GL

### PR DESCRIPTION
**Pull request by jnbrunet**
Needed for the good compilation of SofaPython3.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by damienmarchal** [comment]
The PR is all right to me. 

In the recent pr experiment I'm doing I tend to have a combo like this one
```cpp
sofa::core::objectmodel 
{
    class BaseObject;
    typedef sofa::core::sptr<BaseObject> BaseObjectSPtr 
}
```
It is much more easier to update the code with mass replacement of BaseObject::SPtr with BaseObjectSPtr.

**Review by damienmarchal — APPROVED** [review]

**Comment by jnbrunet** [comment]
> ```c++
> sofa::core::sptr<BaseObject>
> ```

`sofa::core::sptr<BaseObject>` is not much longer than `BaseObjectSPtr` and have to advantage of avoiding an alias :-)

**Comment by damienmarchal** [comment]
> > ```c++
> > sofa::core::sptr<BaseObject>
> > ```
> 
> `sofa::core::sptr<BaseObject>` is not much longer than `BaseObjectSPtr` and have to advantage of avoiding an alias :-)

This is exactly what I was thinking before actually having to do a full replacement of simulation::Node::SPtr on the whole code base. The replacement  requires some care to handle correctly the namespace variations everywhere in the code base 
sofa::simulation::Node::SPtr
simulation::Node::SPtr
Node::SPtr 
I found that a mass replacement from Node::SPtr to NodeSPtr was easier to deploy (and revert) massively.

**Comment by damienmarchal** [comment]
the ci est planté. Je merge.

**Pull request merged**
