### PR TITLE
[SofaGraphComponent] FIX SceneCheck build on MacOS

### PR DESCRIPTION
**Pull request by guparan**
CI info: I disabled Defrost MacOS builder to force this PR to build on sofa-ci-dev-macos.

To be merged asap (if CI agrees).

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
[ci-build]

**Comment by guparan** [comment]
Build failed with old error already seen in build [220](https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/master/CI_CONFIG=mac_clang-3.5,CI_PLUGINS=options,CI_TYPE=release/220/console).

**Comment by epernod** [comment]
[ci-build]

just testing if the problem is due to the lib. 
Will rebase if not.

**Comment by guparan** [comment]
Well done @epernod !

**Comment by guparan** [comment]
Could someone test if the AdvancedTimer is still working correctly with the new nlohmann_json version?
@jnbrunet @fredroy @damienmarchal ?

**Comment by epernod** [comment]
No regression test on the advanceTimer? ;)

**Comment by guparan** [comment]
Ready to merge.

**Comment by epernod** [comment]
green green green!!!

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Pull request merged**
