### PR TITLE
[All] Improve install and packaging

### PR DESCRIPTION
**Pull request by guparan**
### ALL THIS CHANGES MAINLY AFFECT SOFA INSTALL
(basically nothing changes for you if you never do `make install`)

Nothing is breaking BUT dependency problems may arise.
Using package subdirs and relocatable plugins will force us to define dependencies correctly because there will be no more magically accessible parts of SOFA. You will no longer be able to `#include` a file from a package not loaded with `find_package`.

### [[All] CLEAN extlibs integration and install](https://github.com/sofa-framework/sofa/commit/40669c610100a67f46b1405a972b39fe13291eba)
- extlib headers are now installed in include/extlibs
- Windows dependency pack headers are now installed in include/WinDepPack
- SOFA now always tries to `find_package` an extlib before using the embedded one
- header-only extlibs too are now easier to override (see extlibs/CMakelists.txt)
- **One question remains**: is extlibs/SuiteSparse needed?

### [[CMake] Install includes in package subdirs](https://github.com/sofa-framework/sofa/commit/68bef4fec16a410007163c5720a5b2ce003ac478)
Install module headers in a subdirectory named after their package (SofaGeneral, SofaMisc, SofaFramework, ...). This permits to have clean include directories and thus prevents `find_package` from giving access to unwanted foreign headers.
e.g. doing `find_package(SofaFramework)` will NOT be sufficient to `#include <SofaSomething/anything.h>` (you will get a file not found error).
I think it is way easier to understand that a `find_package` is missing when `#include` fails with "file not found" error (at write time if you have a good IDE, at build time otherwise) than with link error (at build time).
Moreover, it will be easier to understand what package is needed for a module by navigating in the include directory.
More details in commit message.

### [[CMake] Make plugins relocatable](https://github.com/sofa-framework/sofa/commit/5b0585f9ad2884cb5462884dffd711ae4d6f2266)
**THIS FEATURE IS OPTIONAL**. See the RELOCATABLE parameter of sofa_generate_package.
When building and installing SOFA with plugins - internal (in applications/plugins) or external (included with SOFA_EXTERNAL_DIRECTORIES) - the plugins will not be mixed with SOFA anymore.
Instead, they will be installed in their own directory under `<install_prefix>/plugins`.
More importantly, they will be relocatable which means they will behave like if they were built out-of-SOFA.
Principal advantage: we will be able to get redistributable plugin binaries through a classic SOFA build.    

### [Defrost binaries changes for a better install, specifically on MacOS](https://github.com/sofa-framework/sofa/commit/22f3c14a25bf879143fb58403a34d569e8ab727f)
- [CMake] FIX install: SofaMiscCollision, SofaDistanceGrid, SofaImplicitField
- [CMake] FIX install on MacOS: differentiate SOFA_BUILD_RELEASE_PACKAGE and SOFA_BUILD_APP_BUNDLE
- [SofaMacros] ADD backward compatibility for INCLUDE_INSTALL_DIR
- [SofaMacros] ADD EXAMPLE_INSTALL_DIR to sofa_create_package
- [SofaMacros] Improve sofa_set_python_directory macro
- [SofaPython] Wider dir search for env loading
- [SofaGuiQt] Remove VSync message
- [package.cmake] Do not force CMAKE_BUILD_TYPE + Enable more plugins

### [[DiffusionSolver] MOVE from image/extlibs to a real plugin](https://github.com/sofa-framework/sofa/commit/54f49d039aadaffd57a1d7f8ebab3af82e407674)
I see no reason not to do that. Dependencies to DiffusionSolver are simpler this way.

### [[CImgPlugin] CLEAN include directory](https://github.com/sofa-framework/sofa/commit/1a617d5350f74ac4a816255960d92638a26cba1b)
Sources moved to `src`. No more `../` horror in CImgPlugin include directories.

## Other changes

- [SofaHelper] FIX DynamicLibrary altered search path (Windows only) 
    Needed to prefer `bin` libraries over neighboor libraries
- [SofaFramework] FIX typo in config.h.in
- [runSofa] Check if plugins dir exists before adding to PluginRepository
- [SofaTest] FIX SofaPython finding in *Config.cmake.in
- [plugins] ADD missing *Config.cmake.in files
    Needed to use them as real plugins
- [All] Improve sofa_copy_libraries and sofa_install_libraries macros
    Make them easier to use
- [CMake] Rename sofa_set_python_directory into sofa_install_pythonscripts
    Clearer name in my opinion + using CMake multiValueArgs
- [CMake] Update package.cmake to enable plugins
    Prepare package.cmake to produce binaries with all plugins from "options" configuration.
- [SofaImplicitField] FIX tests enabling
- [CMake] CLEAN package.cmake
- [SofaSimulationCore] Handle reload differently in SceneLoader::Listener
    Needed to disable scene checks on reload.
- [SofaGraphComponent] Disable scene checks on reload
    Needed by live editor (which reloads the scene every time the file is changed).
- [plugins] Remove commented lines in CMakeFiles

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
very nice PR description...

**Comment by damienmarchal** [comment]
Bon on la merge celle là ?

**Comment by epernod** [comment]
ok for me, the only think I looked in the changes was the reload option, but the PR description already answered my question!
:+1:

**Pull request merged**
