### PR TITLE
[plugins] Remove fetching of SofaPython

### PR DESCRIPTION
**Pull request by alxbilger**
There are still lots of references to this plugin in the rest of the SOFA code base, including bindings in the `image` and `PSL` plugins.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by damienmarchal** [comment]
I'm ok to deprecate PSL until it is updated to SofaPython3 :)

**Comment by alxbilger** [comment]
Well, this PR does not change the status of `SofaPython`. It is still a deprecated external plugin and available on GitHub. This PR just remove the possibility to fetch it.

**Comment by alxbilger** [comment]
See https://github.com/sofa-framework/sofa/issues/3862

**Comment by alxbilger** [comment]
Next step: https://github.com/sofa-framework/sofa/issues/3873

**Pull request merged**
