### PR TITLE
[SofaBaseVisual][SofaDeformable] Clean some codes

### PR DESCRIPTION
**Pull request by epernod**
Small changes found in my dev branch:
1. clean various type mismatch warnings in **SofaBaseVisual** classes
2. Clean some unnecessary/deprectated header includes in **SofaDeformable** classes

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by guparan** [comment]
Let's count warnings: [ci-build][with-all-tests][force-full-build]

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
I checked the QuaterTest **EulerAngles** and it is not using code touched by this PR. This sounds like another blinking error test. 
Ok to open an issue on that but it is not related to this PR.

**Pull request merged**
