### PR TITLE
[SofaKernel gui/qt] Datacallback and datalink

### PR DESCRIPTION
**Pull request by courtecuisse**
Add two types in sofa: only header files that are not (yet) used by other components. 
The DataCallback allows to call a specific function after any modification of a data.

in the declaration of the class 
```
Data<double> d_data
DataCallback c_data; // I usually prefix with c_
```

At the initialization of the constructor:
```
: d_diff(initData(&d_diff, "name", "desc"))
, c_diff(d_diff) // listen to d_diff data. The constructor of the DataCallback takes a data as reference
```

Then anywhere (usually in the constructor body)
```
c_diff.addCallback(this,&MyComponent::myfunction1); 
c_diff.addCallback(this,&MyComponent::myfunction2); 
```

The main difference with an existing type in sofa if the possibility to attach several functions and more importantly to specify the component on which the callback will be called. This allows to define callbacks as member functions of the component, which simplify access to parameters. Additional test are added allowing to modify the data while the callback is called (in order to avoid cyclic calls). This is usefull for linked data i.e. The callback receives a modification from the parent, the callback is then called and it is allowed to modify the data in the callback which will automatically call update of childs of the data. 

The second type introduced in this PR is a wrapper allowing to easily associate a widget with a specific types of data. It can be used as follows: 

in a cpp file
`sofa::helper::Creator<sofa::gui::qt::DataWidgetFactory, GenericDataWidget< Data<bool>, QtDataBoxEdit > >	DWClass_bool("bool",true);`

QtDataBoxEdit is a Qwidget class defined by the user that needs to define usual functions needed in sofa widgets :     
```
void readFromData(const Data<bool>& data);
void writeToData(Data<bool>& data);
 ```

And constructor must take as parameter the parent and the data as follows :
`QtDataBoxEdit(sofa::gui::qt::DataWidget* parent,const sofa::core::objectmodel::Data<bool> & data) : QCheckBox(parent);`

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hi Adrien,

Thank for the PR, and the detailed description.

Few comments at first glance:
- are the class Callback & CallbackImpl not equivalent to the std::function and std::bind that are in the c++11 STL ? 
- about the "if(m_updating)" in the update function. I think it is there to avoid loops. Does it make sense to add a message warning if this happens ? 
- we don't use #pragma once in SOFA as this is not part of the standard . But I think the decision make sense 10 years ago but as the compiler support is now rather bit maybe we should switch to use it as managing the #include SOFA_SUPPER_LONG_NAME_H..is error prone. @guparan, do you think we can make a script to convert the complete code base for pragma once ?

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by marques-bruno** [comment]
Hi @courtecuisse , thanks for your PR.

Concerning the DataCallback, it seems to me that it is a very similar to the DataTrackerFunctor class in SOFA.
Functors would allow you to trigger a call to your component's method, or any other object that you pass to your functor's ctor. You could also assign multiple functors to a single input data, just like you do with the DataCallback::addCallback() method, or assign only one functor, that then uses a vector of std::functions internally, called successively in its operator().
Sure it requires to wrap your callback method in a struct or class, but the cost is not very high IMHO, compared to adding a new Data tracking class in SOFA, where multiple tracking methods already exist, and aren't well known, nor very used by most users, as this PR, or a quick search in SOFA's codebase proves (DataTrackerCallback, DataTracker, DataTrackerDDGNode, DataTrackerEngine, DataTrackerFunctor, DataEngine.......)

Maybe a better alternative would be to provide in SOFA a default functor for the DataTrackerFunctor, taking advantage of C++11's `std::function` function (as @damienmarchal mentioned) to store methods & call them in its operator()?

**Comment by damienmarchal** [comment]
Hi folks,

I was just passing by and notice the work done by fred so thanks for the work done. 

I made a branch where I refactor the DataCallback to make it use the std lib #include<functional> and lambdas instead of re-implementing a similar system with the class Callback/CallbackImpl. 
See: https://github.com/mimesis-inria/sofa/pull/12

But now this is done I wonder what are the difference with the DataCallback and the existing DataTrackerFunctor implemented in DataTracker.h ?  Can you explain a bit ? 

 To me the differences are:
 - the DataTrackerFunctor is allowing one callback and not multiple (but should be easy to change)
 - the DataTrackerFunctor is templated by the callback (which look not needed to me)  
 - the DataTrackerFunctor is not using lambda/functional  (but should be easy to change)
 - the DataTrackerFunctor is passing itself to the functor (which I think is a good idea to access the list of data that have changed, but...lambda are much more easy to work with.)
 -  the DataCallback is storing the tracked data in m_data but this is also done in its parent "inputs" is this data duplication useful ? 
-  the DataTrackerFunctor is "hacking" the setDirtyValue() to trigger the callback while the DataCallback is using notifyEndEdit(). It is unclear to me if this stricly equivalent but the DataTrackerFunctor implementation is shorter.  => So this is not equivalent...setDirtyValue is called before the value is changed while notifyendEndif ...when it has changed. 

To me the two approach needs to be either unified and/or cleaned so we have a consistent API. 

@marques-bruno  can you confirm that DataTrackerFunctor is notified before the value is changed, if so this is a big difference (well I wonder what the DataTrackerFunctor is used for)

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Review by marques-bruno — APPROVED** [review]

**Comment by guparan** [comment]
Tried the crashing test on MacOS VM (Assembly_test.testDecomposedString) and it passed several times, crashed one time, then passed again several times...
Can't investigate further atm.

**Comment by guparan** [comment]
The blinking test crash comes from Assembly_test.cpp:1051`createCompliantString( root, p0, p1, 2, 2.0, 1.0/stiffness, false, 1.0 );` (in Compliant plugin).
Could someone understanding this code investigate further?

**Comment by damienmarchal** [comment]
Ok for me. 

(for the future: I'm still unsure mixing push based logic  with the "on demand" will not cause more troubles than it solves).

**Pull request merged**
