### PR TITLE
[Helper] PluginManager: testing loading a plugin with a dependency on an other plugin

### PR DESCRIPTION
**Pull request by fredroy**
Illustrating #4462 

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Review by alxbilger — APPROVED** [review]
Thanks for this unit test that requires a lot of boilerplate code 👍

**Comment by alxbilger** [comment]
It seems that the test still fails on Ubuntu Debug: https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/master/CI_CONFIG=ubuntu_clang,CI_PLUGINS=options,CI_TYPE=debug/4872/testReport/UnitTests/

**Comment by fredroy** [comment]
`Plugin not found: "TestPluginB_d_d"` it may be the cause 🙊

**Pull request merged**
