### PR TITLE
[CImgPlugin] Export CImg_CFLAGS

### PR DESCRIPTION
**Pull request by guparan**
This PR will fix our last failing unit test on Unix! :tada: 

CImgPlugin defines for CImg build needed to also be defined by every project using CImg.
~~They are now exported in `CImgPlugin_CFLAGS`.~~
They are now defined PUBLIC by CImgPlugin.

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Review by fredroy — APPROVED** [review]

**Comment by damienmarchal** [comment]
Hello Guillaume,

Maybe we should use PUBLIC/PRIVATE/INTERFACE keyword in the target_link_libraries, target_compiler_definition, target_include_directory  to control how the parameters are exposed. 

More specifically, in CImgPlugin/CMakeLists.txt  I think we should replace
```
set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "${CIMG_CFLAGS} -DSOFA_BUILD_CIMGPLUGIN")
```
by 
```
target_compile_options(${PROJECT_NAME} PUBLIC ${CIMG_CFLAGS})
target_compile_definitions(${PROJECT_NAME} PRIVATE "-DSOFA_BUILD_CIMGPLUGIN")
```

By doing this we can totally remove the CImgPlugins_CFLAGS and only do:
```
find_package(CImgPlugin REQUIRED)
target_link_libraries(MyLib CImgPlugin)
```
The target_link_libraries will handle the dependencies of the public part of the included package in the right way and transitively. 

All that is new to me so if you try and if this work please confirm.

**Comment by guparan** [comment]
Thanks for the tip @damienmarchal, I'll try this today :-)

**Comment by guparan** [comment]
Build passes :tada:

**Comment by guparan** [comment]
Just realized that the error this PR was supposed to fix is still there: https://ci.inria.fr/sofa-ci/job/windows7_VS-2015_default_amd64/767/warnings2Result/category.96784904/
The original change (exporting the defines and re-defining them in subprojects) did fix this error though.

**Pull request merged**
