### PR TITLE
Remove high order classes

### PR DESCRIPTION
**Pull request by hdeling**
This pull request removes classes implementing High Order simplicial elements from SOFA.
Those classes have been moved to plugin sofaFramework/ plugin.HighOrder
Updates include 

- removing topological classes for High order triangulation and tetrahedral meshes
- removing tests associated with topological classes
- removing topological and mechanical mapping between regular and highorder meshes
- update of MeshMassMatrix by removing code to  compute mass of high order elements.

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings nor unit test failures.
- [x] does not break existing scenes.
- [x] does not break API compatibility.
- [x] has been reviewed and agreed to be transitional.
- [x] is more than 1 week old.

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
Hi Hervé, thank you for this PR! 
Couldn't these commits be added to your PR #220 ?

**Comment by hdeling** [comment]
These are basically the same commits as PR#220 . This PR lead to a messy situation and should be removed.

**Comment by guparan** [comment]
Just added "pr: wip" label because we need to fix Flexible plugin (make it use [plugin.HighOrder](https://github.com/sofa-framework/plugin.HighOrder)).

**Comment by matthieu-nesme** [comment]
If Flexible compiles, this PR is ready to be merged.

**Comment by damienmarchal** [comment]
Hi all,

It seems there is new test-scene failure since the merge of this PR. 
 - examples/Components/topology/Bezier2MeshMechanicalMapping.scn: [ERROR]   [DAGNode "TriangleTopology"] Object type "Bezier2MeshTopologicalMapping" creation Failed
  - examples/Components/topology/Bezier2MeshMechanicalMapping.scn: [ERROR]   [DAGNode "TriangleTopology"] Object type "Bezier2MeshMechanicalMapping" creation Failed
  - examples/Components/topology/Bezier2MeshMechanicalMapping.scn: [ERROR]   [DAGNode "BezierCubicTriangleTopology"] Object type "BezierTriangleSetTopologyContainer" creation Failed
  - examples/Components/topology/Bezier2MeshMechanicalMapping.scn: [ERROR]   [DAGNode "BezierCubicTriangleTopology"] Object type "BezierTetra2BezierTriangleTopologicalMapping" creation Failed
  - examples/Components/topology/Bezier2MeshMechanicalMapping.scn: [ERROR]   [DAGNode "BezierCubicTriangleTopology"] Object type "BezierTriangleSetGeometryAlgorithms" creation Failed
  - examples/Components/topology/Bezier2MeshMechanicalMapping.scn: [ERROR]   [DAGNode "BezierTriangleMeshFromEngine"] Object type "BezierTetrahedronSetTopologyContainer" creation Failed
  - examples/Components/topology/Bezier2MeshMechanicalMapping.scn: [ERROR]   [DAGNode "BezierTriangleMeshFromEngine"] Object type "BezierTetrahedronSetGeometryAlgorithms" creation Failed
.... more in the logs....
 
We need to fix that in a new PR.

**Pull request merged**
