### PR TITLE
[Spring] Enable spring by default if Data enabled is not set

### PR DESCRIPTION
**Pull request by epernod**
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
So if one did not explicitly enabled springs, it was not doing anything ?? wild 😅

**Review by fredroy — APPROVED** [review]

**Comment by bakpaul** [comment]
My mistake ! This comes from my refactoring...

**Review by bakpaul — APPROVED** [review]

**Comment by bakpaul** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][with-all-tests][force-full-build]

**Pull request merged**
