### PR TITLE
[SofaCUDA] Ignore example scenes using SofaCUDA on CI

### PR DESCRIPTION
**Pull request by guparan**
Following https://github.com/sofa-framework/sofa/pull/2016

I thought SofaCUDA scenes were not tested at all on CI but actually they are (some of them at least).
A `.scene-test` file is used to ignore all the scenes that require SofaCUDA.

Here are the scenes that are successfully tested (check them out [here](https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/master/CI_CONFIG=windows10_vs-2017,CI_PLUGINS=options,CI_TYPE=release/2474/testReport/SceneTests/applications_plugins_SofaCUDA_examples/)):
- StandardTetrahedralFEMForceFieldCPU.scn
- TetrahedralTensorMassForceFieldCPU.scn
- beam10x10x46-fem-implicit-CPU.scn
- beam10x10x46-hexafem-implicit-CPU.scn
- beam10x10x46-hexafem-rk4-CPU.scn
- beam16x16x76-fem-implicit-CPU.scn
- beam16x16x76-hexafem-rk4-CPU.scn
- quadSpringSphere.scn

Does it makes sense to have non-CUDA scenes in SofaCUDA? 
Maybe should we ignore all the plugin scenes?

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by epernod** [comment]
> Does it makes sense to have non-CUDA scenes in SofaCUDA?

yes this is to show the diff.
But for me it makes sens to remove the whole directory on the CI.

**Comment by guparan** [comment]
Thanks for the answer @epernod 
Others opinion? @hugtalbot @fredroy @alxbilger @damienmarchal 

:arrow_right: To keep the non-CUDA scenes tested by CI: click on the :+1: below
:arrow_right: To ignore all the scenes: click on the :-1: below

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Pull request merged**
