### PR TITLE
[NG] MOVE Beams to Components

### PR DESCRIPTION
**Pull request by untereiner**
As said in the title this PR puts the forcefield and mapping of beams into components (following the draft of sofa ng organization)

CHANGELOG
- cleaning of the forcefield
- creation of the beamMassMatrix
- move of all files

TODO
- add comments to the code
- clean the mapping
- add a test scene

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Thanks you very much for this interesting PR. 
I hope we will have feedback on the NG direction.

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by damienmarchal** [comment]
Hello, 

Since you made this PR @untereiner do you have any feedback on the NG proposal ?

**Comment by untereiner** [comment]
Hello,

Yep, but could we do it IRL and in french ... and eventually put a summary of the discussion in this thread ? Maybe next Wednesday meeting ?

**Comment by untereiner** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
I'm gonna make this compile ;)

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by damienmarchal** [comment]
Is there anyone having some time to offer and is interested in helping to have this PR merged ?

**Comment by damienmarchal** [comment]
Anyone ?

**Comment by untereiner** [comment]
I am not working on Sofa for now on. I can just close it I you prefer.

**Comment by damienmarchal** [comment]
Hello Lionel, 

No problem if you have no time to finalize this one for now. We can either close and post-pone it (we have a tag for this ;)) or we found a nice contributor that want to help to finish this one. :)

**Comment by guparan** [comment]
Closed for now, NG project will restart soon :wink:

**Pull request closed without merging**
