### PR TITLE
[SofaSparseSolver] Apply fill in permutation in SparseLDLSolver

### PR DESCRIPTION
**Pull request by dessteph**
Based on https://github.com/sofa-framework/sofa/pull/2756

I added a boolean data, applyPermutation, to the SparseLDLSolver. It gives the choice to the user to apply or not a fill-in reducing permutation on the matrix of the system. By default the boolean is true in order to keep the previous behavior.

FEMBAR-SparseLDLSolver.scn average computation time (to solve the system) with permutation :  3.31 ms
FEMBAR-SparseLDLSolver.scn average computation time (to solve the system) without permutation :  2.05 ms
Benchmarck MatrixAssembly_direct_blocs.scn (with permutation) :  7,45 ms
Benchmarck MatrixAssembly_direct_blocs.scn (without permutation) : 114,39 ms

As the fill-in reducing permutation is computed following heuristic instructions, there may be some situation where it is not worth applying this permutation.

Asynchronous solver still works, not applying the permutation seems to slow it down.
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
Nice ! 👍
As a side note, it could be useful to say that it contains your previous PR #2756 😗

**Comment by alxbilger** [comment]
I ran the benchmark in https://github.com/alxbilger/SofaBenchmark/blob/main/SofaBenchmarkScenes/src/SofaBenchmarkScenes/linearsolver/SparseLDLSolver.cpp:

# `applyPermutation="false"`

```
-------------------------------------------------------------------------------------------------------------------
Benchmark                                                         Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------------------------
BM_Scene_bench_SimulationFactor<SparseLDLSolverScene>/2        1000 ms         1000 ms            1 FPS=200/s frame=5ms
BM_Scene_bench_SimulationFactor<SparseLDLSolverScene>/4        2043 ms         2016 ms            1 FPS=198.45/s frame=5.03906ms
BM_Scene_bench_SimulationFactor<SparseLDLSolverScene>/8        4050 ms         4047 ms            1 FPS=197.683/s frame=5.05859ms
BM_Scene_bench_SimulationFactor<SparseLDLSolverScene>/16       8135 ms         8125 ms            1 FPS=196.923/s frame=5.07812ms
BM_Scene_bench_StepFactor<SparseLDLSolverScene>/512            2606 ms         2562 ms            1 FPS=199.805/s frame=5.00488ms
BM_Scene_bench_StepFactor<SparseLDLSolverScene>/1024           5261 ms         5250 ms            1 FPS=195.048/s frame=5.12695ms
BM_Scene_bench_StepFactor<SparseLDLSolverScene>/2048          10407 ms        10406 ms            1 FPS=196.805/s frame=5.08118ms
```

# `applyPermutation="true"`

```
-------------------------------------------------------------------------------------------------------------------
Benchmark                                                         Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------------------------
BM_Scene_bench_SimulationFactor<SparseLDLSolverScene>/2        1581 ms         1562 ms            1 FPS=128/s frame=7.8125ms
BM_Scene_bench_SimulationFactor<SparseLDLSolverScene>/4        3114 ms         3141 ms            1 FPS=127.363/s frame=7.85156ms
BM_Scene_bench_SimulationFactor<SparseLDLSolverScene>/8        6271 ms         6281 ms            1 FPS=127.363/s frame=7.85156ms
BM_Scene_bench_SimulationFactor<SparseLDLSolverScene>/16      12554 ms        12609 ms            1 FPS=126.89/s frame=7.88086ms
BM_Scene_bench_StepFactor<SparseLDLSolverScene>/512            3960 ms         3969 ms            1 FPS=129.008/s frame=7.75146ms
BM_Scene_bench_StepFactor<SparseLDLSolverScene>/1024           7831 ms         7844 ms            1 FPS=130.55/s frame=7.65991ms
BM_Scene_bench_StepFactor<SparseLDLSolverScene>/2048          15703 ms        15688 ms            1 FPS=130.55/s frame=7.65991ms
```

**Review by alxbilger — CHANGES_REQUESTED** [review]
Please fix the indentation. All the code inside your branch `if ( d_ applyPermutation.getValue() )` must be shifted/tabulated.

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Pull request merged**
