### PR TITLE
[SofaHelper] EDIT FileSystem and FileRepository for regression tests

### PR DESCRIPTION
**Pull request by guparan**
This PR contains needed SOFA modifications for regression tests reactivation:
- Remove SofaTest_test/Regression_test (moved to https://github.com/sofa-framework/regression) and SofaVerification
- FIX DataRepository init: always load sofa.ini at construction
- FIX SofaGTestMain for out-of-sofa use
- ADD `FileSystem::findFiles` for recursive search
- FIX some scenes
- ADD `RegressionStateScenes.regression-tests` and `RegressionTopologyScenes.regression-tests` for listing tested scenes

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
You can see an example of regression test results here: https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-830/11/CI_CONFIG=windows7_vs-2015_amd64,CI_PLUGINS=options,CI_TYPE=release/testReport

**Comment by damienmarchal** [comment]
This is great, I love this !!

**Comment by epernod** [comment]
This should fix:
regression_test issue: #801
regresison test topology: #829
failing regression test need to be discussed in next dev meeting: #828

**Comment by epernod** [comment]
Full doc updated in readme: https://github.com/sofa-framework/regression

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Pull request merged**
