### PR TITLE
[SofaGeneralSimpleFem] add vonMises method in TetrahedralCorotationalFEMForceField

### PR DESCRIPTION
**Pull request by Mrbunbun**
VonMisesStress_TetrahedralCorotationalFEMForceField

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
Not that I want to be that guy, but the code is quite copy-pasted from TetrahedronFEMForcefield (even the data name starts with '_' ) 🧐 . Wont it be possible to factorize the code with TetrahedronFEMForcefield  or anything like that ?

**Comment by epernod** [comment]
> 
> 
> Not that I want to that guy, but the code is quite copy-pasted from TetrahedronFEMForcefield (even the data name starts with '_' ) 🧐 . Wont it be possible to factorize the code with TetrahedronFEMForcefield or anything like that ?

of curse the answer is "Yes, but..." 
Like that is it not that simple because they have a totally different way to store the data. I see 2 methods that could be factorized.
- the computeVonMises which could take the data as parameter, but I don't know where it should be placed.
- the draw method, but it is too specific to be put in the drawTools.

is there a ForceField toolkit or helper somewhere?

**Review by alxbilger — CHANGES_REQUESTED** [review]
I agree with @fredroy. Try to factorize what can be factorize. @fredroy can you give a hint on where to put the factorize code?
Also, follow the code style guidelines: prefix the Data with `d_`

**Comment by fredroy** [comment]
For now, I would say we could introduce a file into the SofaSimpleFEM module (the first module introducing the FEM in SOFA), with  a name like FEMUtils.h (I am not good with names...). Inside you can put the functions (or a class with static functions) factorizing the code (I would say something like computeVonMisesFromElement() and drawVonMisesElements())

**Comment by epernod** [comment]
> 
> 
> For now, I would say we could introduce a file into the SofaSimpleFEM module (the first module introducing the FEM in SOFA), with a name like FEMUtils.h (I am not good with names...). Inside you can put the functions (or a class with static functions) factorizing the code (I would say something like computeVonMisesFromElement() and drawVonMisesElements())

In fact TetrahedronFEMForceField and TetrahedralCorotationalFEMForceField should be merged. Historically the Tetrahedral is only a copy past with topological changes support.  Now that topological changes are done using callbacks, the merge could be done by simply adding an option that will or won't registered the call back.

**Pull request closed without merging**
