### PR TITLE
[runSofa] Fix the generation of the autoload list

### PR DESCRIPTION
**Pull request by fredroy**
Based on 
- #3102

The autoloading libraries (plugin/module/whatever) feature was not including the "new" libraries (i.e  Sofa.Component* ) since the fact that are neither plugin nor module (but still loadable)
This PR fixes it.
Autoloading is not really recommended but a lot of scenes outside this repo relies on it implicitely.

TODO: decide if autoloading should off by default (and force the users to explicitly load their own necessary libs in their scenes)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Review by alxbilger — APPROVED** [review]

**Comment by alxbilger** [comment]
@fredroy I solved the conflicts, but I suggest you take a look on it to validate

**Comment by alxbilger** [comment]
> TODO: decide if autoloading should off by default (and force the users to explicitly load their own necessary libs in their scenes)

Even if autoloading is disabled, the Qt GUI loads its own list of plugins (the one saved by the plugin manager GUI).

**Comment by guparan** [comment]
I'm not sure about this one. I'd like to replace `sofa_add_component_subdirectory` with a more standard macro based on `sofa_add_generic`.
Give me a few hours to try that.

**Comment by fredroy** [comment]
> @fredroy I solved the conflicts, but I suggest you take a look on it to validate

thanks 👍 seems alright!
(even github is happy ` This merge commit was added into this branch cleanly.` )

**Comment by guparan** [comment]
Redone in #3120

**Pull request closed without merging**
