### PR TITLE
[SofaBaseVisual] Fix VisualModelImpl to use topologyData and callback to handle topological changes

### PR DESCRIPTION
**Pull request by epernod**
This PR depends on PR #2299 (should be rebased)

1. Use callback to update the list of triangles/quads and vertices when topological changes happened.
2. Add also callback on texcoord to update texture coordinate when mesh changed.

- Update of texture coordinates was buggy when removing points

- Adding new points where created with texCoord(0, 0)

-> Using the callback on texcoords, use ancestors and coefficient of added point to apply the good texCoords

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
This PR is now including a fix pushed in PR #2359 . Waiting for this new PR approval first.

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Review by fredroy — APPROVED** [review]

**Pull request merged**
