### PR TITLE
[examples] Use MeshMatrixMass in hyperelastic examples

### PR DESCRIPTION
**Pull request by hugtalbot**
Since users often copy paste examples, let's show good scene habits: when modeling volumetric, the MeshMatrixMass should be used instead.

I guess this will trigger the regression tests (but I need to recompile regression first, so I give the CI  a chance :) )

[ci-depends-on https://github.com/sofa-framework/Regression/pull/64]

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Review by alxbilger — APPROVED** [review]
Let's fix the regression reference and go

**Review by bakpaul — APPROVED** [review]

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by alxbilger** [comment]
[ci-build][with-all-tests][force-full-build]

**Comment by bakpaul** [comment]
[ci-build][with-all-tests]

**Pull request merged**
