### PR TITLE
[CMake] ADD option to fetch pull-request commits in ExternalProject

### PR DESCRIPTION
**Pull request by guparan**
When your SOFA PR fails on CI somewhere in an external project, it may be because your change is breaking for that external project.
In that case, the best (and preferred) solution is that you push a fix in the external project so that when your PR is merged in SOFA, it does not fail on CI.
Here is the typical workflow for that use case.

1. You open a PR in SOFA (let's call it "SOFA PR").
2. SOFA CI fails to build/test your SOFA PR because some external projects are enabled and you didn't enable them in your local tests.
3. You realize that the failure is due to your changes.
4. You fix the issue in the external project and open a PR (let's call it "external PR").
5. You reference your external PR in the description of your SOFA PR with  
`[ci-depends-on https://github.com/<org>/<repo>/pull/<id>]`
6. SOFA CI can now build/test your PR. It will automatically replace the external project with the "result of the merge of your external PR".
7. As soon as SOFA CI is green and external PR is merged, your SOFA PR is ready to merge.

This way, you do not need to touch any `ExternalProject.cmake` file in your SOFA PR :+1:

The only change in this PR consists in adding `GIT_CONFIG "remote.origin.fetch=+refs/pull/*:refs/remotes/origin/pr/*"` to all ExternalProject.cmake files.
This change permits to have access to any commit in any pull-request (including merge commits). See [this nice cheatsheet about how to fetch PRs](https://gist.github.com/piscisaureus/3342247).
All other changes have been done [in CI scripts](https://github.com/sofa-framework/ci/blob/master/scripts/pre-builds.sh#L50-L124) and are ready to use.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by guparan** [comment]
[ci-build]

**Comment by jnbrunet** [comment]
See discussion [here](https://github.com/sofa-framework/sofa/pull/2004#issuecomment-820394921)

**Comment by guparan** [comment]
[ci-build]

**Comment by guparan** [comment]
[ci-build]

**Comment by jnbrunet** [comment]
What's up with the CI? Build failed on centos and ubuntu?

**Comment by guparan** [comment]
> 
> 
> What's up with the CI? Build failed on centos and ubuntu?

A weird error that happens sometimes... I relaunched and it's OK now.

**Pull request merged**
