### PR TITLE
Improved MeshVTKLoader

### PR DESCRIPTION
**Pull request by etienneschmitt**
-MeshVTKLoader can now read FIELD data of legacy file.
-lookup tables are ignored.

### CODE REVIEW

**Comment by matthieu-nesme** [comment]
Are you sure the "inVTKFile.close();" are no longer needed in case of errors?

Adding Thomas to the discussion, I think he is using VTK files.

**Comment by etienneschmitt** [comment]
Since c++ ifstreams use the RAII principle the call to close() is done in inVTKFile's destructor.

**Comment by untereiner** [comment]
When will this PR be merged ?  @guparan

**Comment by damienmarchal** [comment]
[ci-build]

**Review by damienmarchal — COMMENTED** [review]
Hi Etiennes, 

This pull-request seems to implements new features (is this the case ?). If this is the case I really think that for each new feature a basic test suite should be provided to validate it and  to avoid 'future' regression. 

A simple scene+test just loading a file with a FIELD data would make it.

**Comment by etienneschmitt** [comment]
hi @damienmarchal ,
I've added a small test (loading a binary vtk file with point and cell attributes). Is that enough ?

**Comment by damienmarchal** [comment]
@etienneschmitt, thank you for the test. 
 
The dashboard seems to report there is problem with the added test: 
https://www.sofa-framework.org/dash/?branch=pr/fix_vtkloader

EDIT1: isn't the file 'vox8_binary.vtk' missing ?

Apart from the dashboard issue i would say:
  +1 for the use of c++x11  
  +1 for the test  
  +1 for the new feature 
:)

As @thomas-lemaire  was assigned by Mathieu to this PR I assume having its feedback is important before merging.

**Comment by bcarrez** [comment]
Etienne, if the test succeeds on your PC please fix your branch so that the test succeeds on the dashboard also. Otherwise, this pull request could not be accepted.

**Comment by etienneschmitt** [comment]
@bcarrez Ok it was the "classical one", i forgot to add the mesh in the last commit. This time it should work on an other computer than mine.

**Comment by guparan** [comment]
Checks show SUCCESS but tests are ignored. 
Your unit test crashes, check the logs: https://ci.inria.fr/sofa-ci/job/ubuntu_gcc-4.8_options/4259/console

**Comment by etienneschmitt** [comment]
@guparan  My tests were wrong (they read previously deleted data). Now everything seems fine.

**Comment by thomas-lemaire** [comment]
Yes I am using vtk files, but read/write with VTK library itself, not with sofa

**Pull request merged**
