### PR TITLE
[CMake] Remove COMPONENTSET, keep DEPRECATED

### PR DESCRIPTION
**Pull request by guparan**
This PR removes the COMPONENTSET mechanism from our CMakeLists.
Deprecated components are now identified by the option SOFA_WITH_DEPRECATED_COMPONENTS.

I also couldn't resist to reformat a bit. Tell me if I did something wrong!

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
Will try a build on CI with `SOFA_WITH_DEPRECATED_COMPONENTS=OFF`

**Comment by guparan** [comment]
Here we go, let's try to [ci-build][with-scene-tests]

**Comment by guparan** [comment]
Build fails because of a dependency from MouseOperations to multiple deprecated components in SofaUserInteraction.
Any clue on this component guys?
@damienmarchal @fredroy @ErwanDouaille @epernod

**Comment by guparan** [comment]
TODO: add file for deprecated components, SceneChecker will read this file.
Back to wip.

**Comment by guparan** [comment]
@damienmarchal Could you have a look at my recent commits (particularly https://github.com/sofa-framework/sofa/pull/586/commits/661d7609897dda39bf7f11d0e232e4799f3176f6) please?
[ci-build][with-scene-tests]

**Comment by damienmarchal** [comment]
Hi @guparan everything looks fine to me except that I disagree with having sofa code in tools/ :)

Because to me tools/ is just there to hold external tools that are not compiled from sofa code. 
Some utilitary code should be in SofaKernel/Framework/Simulation/Module 
While application build on top of Sofa should be in applications :)

**Comment by guparan** [comment]
Understood, I'll move it to applications/projects :-)

EDIT: Then SofaGTestMain should be moved too.

**Comment by guparan** [comment]
Here we go!

**Pull request merged**
