### PR TITLE
[all] Speed up spheres rendering + code cleaning (URGENT)

### PR DESCRIPTION
**Pull request by fredroy**
Speed up by a (huge) factor the rendering of several spheres.
This is done in 2 ways:
 - optimizing with VBO for "normal" spheres (like before, with rings and segments parameters) 
 - impostors (https://paroj.github.io/gltut/Illumination/Tutorial%2013.html)

On the same computer, for 150K spheres :
- 0.8fps with previous rendering
- 22fps with VBO
- 46 fps with impostors 

This task is also the beginning of optimizing draw tools, by removing deprecated glu calls and non optimized OpenGL code ; and by using VBO/IBO and shaders. (class BasicShapesGL)

This PR should resolve more or less the issue #142 . 
It depends if this issue talks about spheres only or more generally speeding up rendering itself (in that case, it will need much more commits ;) )

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings nor unit test failures.
- [x] does not break existing scenes.
- [x] does not break API compatibility.
- [x] has been reviewed and agreed to be transitional.
- [x] is more than 1 week old.

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by matthieu-nesme** [comment]
YEAH! Thanks Fred, do we have to wait for a week before merging?

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by matthieu-nesme** [comment]
@fredroy  It is working well, one minor problem is the spheres are darker, is it possible to tweak the shader to display them lighter by default? Thanks.

**Comment by fredroy** [comment]
You are right that the spheres are too dark ; I forgot to add the ambient component in the final color computation ; I will submit a patch right away.

**Comment by fredroy** [comment]
Pull-Request : #192

**Pull request merged**
