### PR TITLE
[Regression] Add HexahedronFEMForceFieldAndMass to regression tests

### PR DESCRIPTION
**Pull request by alxbilger**
[ci-depends-on https://github.com/sofa-framework/Regression/pull/37]

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
Are you using this component?
I thought it was nearly deprecated

**Comment by alxbilger** [comment]
I don't know about the status of this component, but I just want to keep the compatibility with this component in my matrix refactoring branch. Note that there is a similar component in BeamAdapter: AdaptiveBeamForceFieldAndMass

**Comment by epernod** [comment]
Ok, was just for curiosity.
I think only the naming is similar with the one from BA. but the theory is totally different. Would be good to ask the authors...

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Pull request merged**
