### PR TITLE
[SofaKernel] Remove multigroup option in MatrixLinearSolver

### LINKED ISSUE #816: remove MultiGroup in LinearSolver
In  the component MatrixLinearSolver, there is the option "multi group"  (false by default) that complexity the code unnecessarily. 
The goal of this option was to solve each Mechanical Object under the LinearSolver  as if there were independant manner.  I**n practice, the approach is not compatible with multi-mapping** (and was maybe coded at the time when the scene graph was a tree...).

If no one stop us... we will remove it soon.

https://github.com/sofa-framework/sofa/blob/a21a0a33812f9a1b3f0d1f30fdc8d61aad560150/SofaKernel/modules/SofaBaseLinearSolver/MatrixLinearSolver.h#L182

@sofa-framework/reviewers

### PR DESCRIPTION
**Pull request by damienmarchal**
This is related to the issue at: https://github.com/sofa-framework/sofa/issues/816
Fixes #816 

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
ok for me if the tests pass but I don't understand what is involved behind between the groups and multi-mapping.

**Review by epernod — APPROVED** [review]

**Comment by damienmarchal** [comment]
Hi all,

Thank Erik for the review of this PR. It seems there is one scene test failure that may be related "RuleBaseCollisionManager".

@ChristianDuriez  any idea where this could come from ?

**Comment by guparan** [comment]
@damienmarchal The failure is related to @epernod work on topologies. Not related to this PR :wink:

**Pull request merged**
