### PR TITLE
[SofaGeneralLinearSolver] Clean BTDLinearSolver

### PR DESCRIPTION
**Pull request by p-shg**
Moved function definitions from .h to .inl

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
Congrats for your first PR @p-shg :clap: 

There is a build error on Windows though (who said it would be quick & easy?):
```
BTDLinearSolver.inl(84): error C2244: 'sofa::component::linearsolver::BlocFullMatrix<N,T>::Bloc::operator -': unable to match function definition to an existing declaration
BTDLinearSolver.inl(81): note: see declaration of 'sofa::component::linearsolver::BlocFullMatrix<N,T>::Bloc::operator -'
BTDLinearSolver.inl(84): note: definition
BTDLinearSolver.inl(84): note: 'sofa::defaulttype::Mat<sofa::component::linearsolver::BlocFullMatrix<N,T>::BSIZE,sofa::component::linearsolver::BlocFullMatrix<N,T>::BSIZE,T> sofa::component::linearsolver::BlocFullMatrix<N,T>::Bloc::operator -(void) const'
BTDLinearSolver.inl(84): note: existing declarations
BTDLinearSolver.inl(84): note: 'sofa::defaulttype::Mat<,,real> sofa::component::linearsolver::BlocFullMatrix<N,T>::Bloc::operator -(const sofa::defaulttype::Mat<,,real> &) const'
BTDLinearSolver.inl(84): note: 'sofa::defaulttype::Mat<,,real> sofa::component::linearsolver::BlocFullMatrix<N,T>::Bloc::operator -(void) const'
BTDLinearSolver.inl(90): error C2244: 'sofa::component::linearsolver::BlocFullMatrix<N,T>::Bloc::operator -': unable to match function definition to an existing declaration
BTDLinearSolver.inl(87): note: see declaration of 'sofa::component::linearsolver::BlocFullMatrix<N,T>::Bloc::operator -'
BTDLinearSolver.inl(90): note: definition
BTDLinearSolver.inl(90): note: 'sofa::defaulttype::Mat<sofa::component::linearsolver::BlocFullMatrix<N,T>::BSIZE,sofa::component::linearsolver::BlocFullMatrix<N,T>::BSIZE,T> sofa::component::linearsolver::BlocFullMatrix<N,T>::Bloc::operator -(const sofa::defaulttype::Mat<,,real> &) const'
BTDLinearSolver.inl(90): note: existing declarations
BTDLinearSolver.inl(90): note: 'sofa::defaulttype::Mat<,,real> sofa::component::linearsolver::BlocFullMatrix<N,T>::Bloc::operator -(const sofa::defaulttype::Mat<,,real> &) const'
BTDLinearSolver.inl(90): note: 'sofa::defaulttype::Mat<,,real> sofa::component::linearsolver::BlocFullMatrix<N,T>::Bloc::operator -(void) const'
```

**Comment by marques-bruno** [comment]
Probably a missing `typename` in the return type of the overloaded operators (in the .inl) We'll investigate on Friday @p-shg ?

**Comment by damienmarchal** [comment]
This PR is still in WIP.

**Comment by marques-bruno** [comment]
> This PR is still in WIP.

We'll work on it friday with @p-shg

**Comment by guparan** [comment]
Looks fine now.
[ci-build][with-scene-tests]

**Comment by marques-bruno** [comment]
> Looks fine now.
> [ci-build][with-scene-tests]

Yeah... Although we simply moved the definitions of the problematic operator overloads back into the .h... so problem half solved... if anyone has an idea how to make it build on windows... I'm curious. Otherwise, let's just merge... :)

**Review by marques-bruno — APPROVED** [review]

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests]

**Pull request merged**
