### PR TITLE
[SofaSparseSolver][SofaPreconditioner] modularization

### PR DESCRIPTION
**Pull request by damienmarchal**
As said in the title this PR puts SofaSparseSolver and SofaPreconditioner as a real module that can be activated/deactivated. 

CHANGLELOG/
 - move source files to src/SofaSparseSolver & src/SofaPreconditioner so the .h are not leaked anymore. 
 - conditional code based on #define SOFA_HAVE_METIS/SOFA_HAVE_CSPARSE is now changed to favor the use of *find_package* to detect and activate conditional building depending on dependencies. 
- add a modules/CMakeLists.txt to integrate that
- add the touched component into the list of 'moved' component

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests]

**Comment by damienmarchal** [comment]
@guparan, @hugtalbot Could we considering progressing on those...they are now wainting for review since weeks :)

**Comment by guparan** [comment]
I'm on it :wink:

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
Nice work @damienmarchal, this PR is approved.
Please have a quick look at my few changes.
I set the "breaking" label since every code linking to those two modules will have to add the appropriate `find_package`.

**Review by guparan — APPROVED** [review]

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
TODO: resolve conflict then merge
Do not forget to add "every code linking to those two modules will have to add the appropriate find_package" to commit message.

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Pull request merged**
