### PR TITLE
[LinearSystem.Direct] Remove metis dependency

### PR DESCRIPTION
**Pull request by alxbilger**
Everything depending on Metis is now in moved in https://github.com/sofa-framework/Sofa.Metis

[ci-depends-on https://github.com/sofa-framework/CSparseSolvers/pull/3]

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Review by fredroy — APPROVED** [review]

**Review by fredroy — COMMENTED** [review]
I approved just before 😅 but should you not add it into the plugins cmakelists (with fetch, etc) ?

**Comment by alxbilger** [comment]
@fredroy yes this is the plan. Don't know yet if it will be in this PR or in another. Don't forget that https://github.com/sofa-framework/Sofa.Metis/pull/1 is to be reviewed as well.

**Comment by fredroy** [comment]
[ci-build][with-all-tests][force-full-build]

**Pull request merged**
