### PR TITLE
[all] Refactor Read/Write Accessor. 

### PR DESCRIPTION
**Pull request by damienmarchal**
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build][ci-with-scene-tests][ci-with-regression-tests]

**Comment by damienmarchal** [comment]
[ci-build][ci-with-scene-tests][ci-with-regression-tests]

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests][with-regression-tests]

**Comment by damienmarchal** [comment]
[ci-build]

Change done... back to review. 
@fredroy, @hugtalbot

**Comment by fredroy** [comment]
Yep, I did not find a "standard" std:: thingy to do the is_iterable or something like that (except concept from c++20), so good to go for me as well.
[ci-build][force-full-build][with-all-tests]

**Comment by damienmarchal** [comment]
When I see all these ci-build-full-regression stuff... I always think this will lock for 2 hours each of the CI node and I feel very depressed  about other's person PR be moved to new nodes by the scheduler and thus becoming full-build instead of incremental ones.

**Comment by damienmarchal** [comment]
So ... @hugtalbot, @fredroy  :)

**Comment by damienmarchal** [comment]
@zzzz

**Pull request merged**
