### PR TITLE
[CMake] ADD QtIFW generator + improvements

### PR DESCRIPTION
**Pull request by guparan**
One step towards continuous delivery in SOFA :tada: 

This PR reworks/cleans CPack usage for release packaging and adds a new generator : [Qt Installer Framework](http://doc.qt.io/qtinstallerframework/ifw-overview.html). Very useful to unify packaging methods, it will be at first used to generate nice installers for Linux.

This means no more .zip package for Linux binaries, unless you want to keep them?

Note: This PR also adds the opening of an URL after installation to ask the user to consider donating to the SOFA project. Do not hesitate to comment if you disagree with this idea.

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
Packaging started in CI: https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/PR-796/3/

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests]

**Pull request merged**
