### PR TITLE
[LinearSolver.Direct] Minor clean up in SparseCholeskySolver

### PR DESCRIPTION
**Pull request by alxbilger**
* Code factorization
* Remove unnecessary C-style casts
* Remove unnecessary redirecting intermediate function
* Use class access specifiers (make members protected)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
It seems the cleanup introduced a regression unfortunately (`FEMBAR_PrecomputedLinearSolver .scn` is crashing)

**Comment by alxbilger** [comment]
I really like those kind of small PR that transform into a giant time-consuming one.

**Comment by alxbilger** [comment]
@fredroy the regression is fixed

**Comment by fredroy** [comment]
thanks for the heads-up 👍

**Review by fredroy — APPROVED** [review]

**Pull request merged**
