### PR TITLE
[SofaNewMat] Fix compilation

### PR DESCRIPTION
**Pull request by alxbilger**
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
@guparan @fredroy I guess this plugin is not compile by the CI. Would it make sense to add it?

**Comment by fredroy** [comment]
> @guparan @fredroy I guess this plugin is not compile by the CI. Would it make sense to add it?

IMO, this plugin was doomed to be removed in a near future. But we can still compile on the CI it if necessary

**Comment by alxbilger** [comment]
@fredroy Totally removed or in an external plugin?

**Comment by fredroy** [comment]
> @fredroy Totally removed or in an external plugin?

I would put it in an external plugin (but just for storage so kind of removed in the same time).
We dont like removing code 😅

**Pull request merged**
