### PR TITLE
[Simulation.Core] Fix memory leak when deleting a Task

### PR DESCRIPTION
**Pull request by fredroy**
TODO

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Review by alxbilger — COMMENTED** [review]
I don't understand the differences here.

**Comment by fredroy** [comment]
> I don't understand the differences here.

That's the problem, this is supposed to do the same thing : either calling the delete operator with size or not size, because in this end both of them call the same code in the StdTaskAllocator https://github.com/sofa-framework/sofa/blob/d855365c71b4b83190ca4af3ce412bd4dbdc1b2f/Sofa/framework/Simulation/Core/src/sofa/simulation/DefaultTaskScheduler.cpp#L47

But in the end calling the version without size fixes the leak 😶‍🌫️
caduceus.scn with 1000steps: 
Before: (operator delete with size)
```
Direct leak of 63936 byte(s) in 999 object(s) allocated from:
    #0 0x7fdeaeac0488 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:95
    #1 0x7fdea4253138 in _M_create<sofa::component::animationloop::FreeMotionAnimationLoop::FreeMotionAndCollisionDetection(const sofa::core::ExecParams*, const sofa::core::ConstraintParams&, SReal, sofa::core::MultiVecId, sofa::core::MultiVecId, sofa::core::MultiVecDerivId, sofa::simulation::common::MechanicalOperations*)::<lambda()> > /usr/include/c++/12/bits/std_function.h:161
    #2 0x7fdea4253138 in _M_init_functor<const sofa::component::animationloop::FreeMotionAnimationLoop::FreeMotionAndCollisionDetection(const sofa::core::ExecParams*, const sofa::core::ConstraintParams&, SReal, sofa::core::MultiVecId, sofa::core::MultiVecId, sofa::core::MultiVecDerivId, sofa::simulation::common::MechanicalOperations*)::<lambda()>&> /usr/include/c++/12/bits/std_function.h:215
    #3 0x7fdea4253138 in _M_manager /usr/include/c++/12/bits/std_function.h:198
    #4 0x7fdea4253138 in _M_manager /usr/include/c++/12/bits/std_function.h:282
    #5 0x7fdea81a4486 in std::function<void ()>::function(std::function<void ()> const&) /usr/include/c++/12/bits/std_function.h:391
    #6 0x7fdea81a4486 in sofa::simulation::TaskScheduler::addTask
<lots and lots of other leaks...>
...
SUMMARY: AddressSanitizer: 808967 byte(s) leaked in 15938 allocation(s).
```
After:  (operator delete without size)
```
<no more Tasks leak>
SUMMARY: AddressSanitizer: 744967 byte(s) leaked in 14938 allocation(s).
```

And I don't understand why 😅

My primary intention was that  (without looking at the StdTaskAllocator, I noticed that calling the operator delete with sizeof(Task) was not correct as the pointer to Task is pointed actually to a CallableTask (which is bigger in memory) thus it was supposed to free less memory (as sizeof(Task) < sizeof(CallableTask). But after digging into the code, I saw that both of the operator delete are supposed to call the same code. I even checked with the debugger that, indeed both of them reach the function in StdMemoryAllocator...
So I guess some other things happen here but I cannot explain why 🤐

**Comment by alxbilger** [comment]
Ok thanks for the explanation. Is there any information in the git history?

**Comment by bakpaul** [comment]
Hey @fredroy @alxbilger, what about this pr ?

**Comment by fredroy** [comment]
> Hey @fredroy @alxbilger, what about this pr ?

I did not really investigate for the moment so I guess I will close it and maybe come back on it later

**Pull request closed without merging**
