### PR TITLE
Remove FFMPEG_exec target from the dependencies of SofaFramework

### PR DESCRIPTION
**Pull request by jnbrunet**
Currently, if you build Sofa with FFMPEG support, linking SofaFramework to an external project will require to find the FFMPEG_exec target, which will not be found: the cmake script to find the FFMPEG executable isn't installed by the Sofa install process.

This FFMPEG executable path is never used in header files, only in cpp, I don't see any reason to force external projects to find it.

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
The question is: [does VideoRecorderFFMPEG need FFMPEG_exec](https://github.com/sofa-framework/sofa/blob/master/SofaKernel/framework/sofa/helper/CMakeLists.txt#L308-L311)?

**Comment by jnbrunet** [comment]
> The question is: does [VideoRecorderFFMPEG need FFMPEG_exec](https://github.com/sofa-framework/sofa/blob/master/SofaKernel/framework/sofa/helper/CMakeLists.txt#L308-L311)?

Yes it does, because, watch out....

[SofaKernel/framework/sofa/helper/gl/VideoRecorderFFMPEG.cpp](https://github.com/sofa-framework/sofa/blob/ef4114de87ccb97ad6792f553419644b5e77eb98/SofaKernel/framework/sofa/helper/gl/VideoRecorderFFMPEG.cpp#L97)
  ```
  std::stringstream ss;
    ss << FFMPEG_EXEC_FILE
       << " -r " << m_framerate
        << " -f rawvideo -pix_fmt rgba "
        << " -s " << m_ffmpegWidth << "x" << m_ffmpegHeight
        << " -i - -threads 0  -y"
        << " -preset fast "
        << " -pix_fmt " << codec // yuv420p " // " yuv444p "
        << " -crf 17 "
        << " -vf vflip "
        << "\"" << m_filename << "\""; // @TODO C++14 : replace with std::quoted
```

Yes, `FFMPEG_EXEC_FILE` is hard-coded and defined by 

`add_definitions( "-DFFMPEG_EXEC_FILE=\"${FFMPEG_EXEC_FILE}\"" )` in [findFFMPEG_exec.cmake](https://github.com/sofa-framework/sofa/blob/ef4114de87ccb97ad6792f553419644b5e77eb98/cmake/Modules/FindFFMPEG_exec.cmake#L18).

Which means that don't you ever package Sofa with FFMPEG support. If the user who installs your package has its ffmpeg elsewhere, everything will collapse.

**Comment by guparan** [comment]
Ok, very nasty...
So I agree with your PR, we should not impose the `find_package(FFMPEG_exec)` to dependencies.
But it is not enough. We should clean this hardcoded path by installing the executable.

**Review by fredroy — APPROVED** [review]

**Comment by guparan** [comment]
I just replaced the nasty `add_definitions( "-DFFMPEG_EXEC_FILE=\"${FFMPEG_EXEC_FILE}\"" )` by a dynamic `.ini` file. 
Could you update your review @fredroy ?

**Comment by guparan** [comment]
Woops, I should not have removed FindFFMPEG.cmake :sweat_smile: 
Let me make my mistake disappear with a magic force push...

**Review by fredroy — APPROVED** [review]

**Comment by jnbrunet** [comment]
To be honest, I don't think this INI file should be in the Sofa API, but more on the application side (GUI, python or whatever). The API should simply be giving the FFMPEG path by the application.

**Comment by guparan** [comment]
Understood, will look at it asap.

**Comment by guparan** [comment]
Done. Waiting for your review @jnbrunet :wink:

**Comment by guparan** [comment]
@jnbrunet Could you take a look at my latest changes?

**Comment by jnbrunet** [comment]
Hey @guparan, sorry for the delay.

 It looks much better now.

The only thing that bugs me is, why make the ffmpeg option dependant on compilation checks if only the ffmpeg executable is needed.

I would remove completely the compilation checks for ffmpeg, and always show the option in the GUI, with a textbox to specify the ffmpeg path. If no path are specified, check the INI file if it has one, if not then gray-out the options for ffmpeg output. If it is a valid path (checked during runtime), then save that path in the INI file.

I think this would make much more sense and would not restrict the user if he have ffmpeg somewhere on his computer that was not found during compilation or if he downloaded a compiled version of Sofa with ffmpeg support but his ffmpeg path doesn't match the one used for compilation.

What do you think?

**Comment by guparan** [comment]
I understand and I agree but I have no time do to that for now. I propose to create an issue about it and merge this.

**Comment by jnbrunet** [comment]
Good for me, +1 to merge this

**Comment by adagolodjo** [comment]
Hi guys, This PR breaks the headless plugin, at least the version I am using. @jnbrunet or @guparan if one of you have time to explain me more on monday. Thanks

**Comment by jnbrunet** [comment]
Hey @Younesssss ,

We will need a little bit more information. What's the output? Are you on master?

**Comment by adagolodjo** [comment]
Hey @jnbrunet ,

Yes, I am on master.  But the thing is that the Headless is not working anymore on the Master branch. That's why I am merging SOFA master on this PR https://github.com/sofa-framework/sofa/pull/919 "But for some reasons that I forgot, we can't merge that in the master". 

With this PR, apart from the compilations problems witch I solved (I hope well), the component is not generating the output  video anymore.

**Pull request merged**
