### PR TITLE
[SofaKernel] Fix the Filemonitor_test random failure on MacOs

### PR DESCRIPTION
**Pull request by bcarrez**
Update: 

- now with a correct implementation of the timeout parameter. Tests should not fail randomly now...
- also updated the filemonitor tests to use this timeout parameter correctly

### CODE REVIEW

**Comment by bcarrez** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
This PR fix the issue https://github.com/sofa-framework/sofa/issues/140

**Comment by bcarrez** [comment]
@hugtalbot , it looks like this is still this good old "reference is not a tree" problem... not even related to code :-(

**Comment by damienmarchal** [comment]
@hugtalbot The code seems ok to me and fix test that are bugued. 
I vote for fast integration ASAP we have an all green dashboard.

**Pull request merged**
