### PR TITLE
[Core] Dump ObjectFactory in json

### PR DESCRIPTION
**Pull request by alxbilger**
The prettyfied output of the unit test:

```
[
  {
    "className": "DefaultAnimationLoop",
    "creator": {
      "": {
        "class": {
          "className": "DefaultAnimationLoop",
          "namespaceName": "sofa::simulation",
          "shortName": "defaultAnimationLoop",
          "templateName": "",
          "typeName": "DefaultAnimationLoop"
        },
        "object": {
          "data": [
            {
              "group": "",
              "help": "object name",
              "name": "name"
            },
            {
              "group": "",
              "help": "if true, emits extra messages at runtime.",
              "name": "printLog"
            },
            {
              "group": "",
              "help": "list of the subsets the objet belongs to",
              "name": "tags"
            },
            {
              "group": "",
              "help": "this object bounding box",
              "name": "bbox"
            },
            {
              "group": "",
              "help": "The state of the component among (Dirty, Valid, Undefined, Loading, Invalid).",
              "name": "componentState"
            },
            {
              "group": "",
              "help": "if true, handle the events, otherwise ignore the events",
              "name": "listening"
            },
            {
              "group": "",
              "help": "If true, compute the global bounding box of the scene at each time step. Used mostly for rendering.",
              "name": "computeBoundingBox"
            },
            {
              "group": "",
              "help": "If true, solves all the ODEs in parallel",
              "name": "parallelODESolving"
            }
          ],
          "link": [
            {
              "help": "Graph Node containing this object (or BaseContext::getDefault() if no graph is used)",
              "name": "context"
            },
            {
              "help": "Sub-objects used internally by this object",
              "name": "slaves"
            },
            {
              "help": "nullptr for regular objects, or master object for which this object is one sub-objects",
              "name": "master"
            },
            {
              "help": "Link to the scene's node that will be processed by the loop",
              "name": "targetNode"
            }
          ]
        },
        "target": ""
      }
    },
    "description": "foo\n"
  }
]
```

and the templated object:

```
[
  {
    "className": "DummyComponent",
    "creator": {
      "Vec3f": {
        "class": {
          "categories": [
            "_Miscellaneous"
          ],
          "className": "DummyComponent",
          "namespaceName": "sofa",
          "parents": [
            "BaseObject"
          ],
          "shortName": "dummyComponent",
          "templateName": "Vec3f",
          "typeName": "DummyComponent\u003CStdVectorTypes\u003CVec\u003C3,float\u003E,Vec\u003C3,float\u003E,float\u003E\u003E"
        },
        "object": {
          "data": [
            {
              "defaultValue": "unnamed",
              "group": "",
              "help": "object name",
              "name": "name",
              "type": "string"
            },
            {
              "defaultValue": "0",
              "group": "",
              "help": "if true, emits extra messages at runtime.",
              "name": "printLog",
              "type": "bool"
            },
            {
              "defaultValue": "",
              "group": "",
              "help": "list of the subsets the objet belongs to",
              "name": "tags",
              "type": "TagSet"
            },
            {
              "defaultValue": "",
              "group": "",
              "help": "this object bounding box",
              "name": "bbox",
              "type": "BoundingBox"
            },
            {
              "defaultValue": "Undefined",
              "group": "",
              "help": "The state of the component among (Dirty, Valid, Undefined, Loading, Invalid).",
              "name": "componentState",
              "type": "ComponentState"
            },
            {
              "defaultValue": "0",
              "group": "",
              "help": "if true, handle the events, otherwise ignore the events",
              "name": "listening",
              "type": "bool"
            }
          ],
          "link": [
            {
              "help": "Graph Node containing this object (or BaseContext::getDefault() if no graph is used)",
              "name": "context"
            },
            {
              "help": "Sub-objects used internally by this object",
              "name": "slaves"
            },
            {
              "help": "nullptr for regular objects, or master object for which this object is one sub-objects",
              "name": "master"
            }
          ]
        },
        "target": ""
      }
    },
    "description": "foo\n"
  }
]
```

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by damienmarchal** [comment]
Additional info to have:
-  the data type using getValueTypeString()
- if it is input or output (for DataEngines)

**Comment by alxbilger** [comment]
> * if it is input or output (for DataEngines)

Isn't it defined by the group string? Input Data have the group "Inputs", and output "Outputs"

**Comment by damienmarchal** [comment]
> > * if it is input or output (for DataEngines)
> 
> Isn't it defined by the group string? Input Data have the group "Inputs", and output "Outputs"

I would say that being an input is because the Data has been added with DataEngine::addInput  ... the fact it is in the group "Inputs" is just an UX choice.

**Comment by alxbilger** [comment]
@damienmarchal How can I get the information that a Data is an input or not?

**Comment by alxbilger** [comment]
TODO: add parent classes + eventually category + add a test with a template

**Comment by damienmarchal** [comment]
The status indicating if it is input or output is not hard coded in the data structure.
During the STC it was decided that we should have it. Several category of inputs have been decided: input, output, input-and-output, unknow (see the STC reports for the precise naming). To me the easiest is to export everything with the "unknow" type (which indicate ... the "we don't know exactly" current state. As you pointed for DataEngine,  you can then use the fact a data is part of the "Input" / "Output"... but it is only an heuristic. It is possible to have better heuristic... eg: detecting through the DDG superclass of a data field if this data is an input in an update callback.... but I think  this is too complex... and purposeless given that the information should be added (soon) in  BaseData.

**Comment by alxbilger** [comment]
TODO: add type of Links

**Pull request merged**
