### PR TITLE
[LinearSolver] Remove CSparse-based linear solvers

### PR DESCRIPTION
**Pull request by alxbilger**
They are moved in an external plugin: https://github.com/sofa-framework/CSparseSolvers

Two components are impacted: `SparseLUSolver` and `SparseCholeskySolver`.

The plugin `CSparseSolvers` is now fetchable

> ⚠️ `SparseLUSolver` has an equivalent using Eigen in SOFA (without the need of a plugin): `EigenSparseLU`, and `SparseCholeskySolver` equivalent is `EigenSimplicialLLT`.

[ci-depends-on https://github.com/sofa-framework/SofaPython3/pull/378]
[ci-depends-on https://github.com/sofa-framework/BeamAdapter/pull/119]

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
@alxbilger you did not keep the (git) history of the files when moving to the new plugin.

**Comment by alxbilger** [comment]
> @alxbilger you did not keep the (git) history of the files when moving to the new plugin.

It's such a pain. I suspect you don't like me much to request such a task. In this branch https://github.com/alxbilger/CSparseSolvers/tree/move_csparse_files, I have the same plugin but with all the SOFA history. I guess it's not really what we want neither. Do you know how to proceed?

**Comment by fredroy** [comment]
> > @alxbilger you did not keep the (git) history of the files when moving to the new plugin.
> 
> It's such a pain. I suspect you don't like me much to request such a task. 

🥰

> In this branch https://github.com/alxbilger/CSparseSolvers/tree/move_csparse_files, I have the same plugin but with all the SOFA history. I guess it's not really what we want neither. Do you know how to proceed?

I would proceed like this:
 - in a fresh clone of SOFA, on master move (git mv) all the CSParse_plugin related files into the new folder (application/plugins/cparseplugin), commit
 - use git filter-repo, see the doc: https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository. This will only keep the history of the files you kept in the folder.
 - push all of that into the new repo

Credit to @hugtalbot https://github.com/sofa-framework/sofa/issues/1442

**Comment by alxbilger** [comment]
@fredroy the history is now preserved

**Comment by alxbilger** [comment]
[ci-build][with-all-tests][force-full-build]

**Comment by fredroy** [comment]
> @fredroy the history is not preserved

It does now no ? I can see commits down to ` Commits on Mar 10, 2009` ? (a9bd817a4ec46a06e07b9f755660c58d48cf9d17)

**Comment by alxbilger** [comment]
> > @fredroy the history is not preserved
> 
> It does now no ? I can see commits down to ` Commits on Mar 10, 2009` ? ([a9bd817](https://github.com/sofa-framework/sofa/commit/a9bd817a4ec46a06e07b9f755660c58d48cf9d17))

Yes, it is preserved

**Comment by fredroy** [comment]
[ci-build][with-all-tests][force-full-build]

**Comment by fredroy** [comment]
@alxbilger it seems that some scenes which use `EigenSimplicialLLT` instead of a CSparse-based linear solver  are crashing, maybe because of the default template CSRMat3x3

**Comment by bakpaul** [comment]
Why is the minimum cmake version of CSparsePlugin 3.24 -> ci won't work if it stays like that. I've configured it with 3.22 (shipped version of Ubuntu 22.04) and it works fine.  (I know not exactly in this PR, but this is the pr that propose the CSparePlugin creation)

**Comment by alxbilger** [comment]
@bakpaul The 3.24 version of CMake was in anticipation of @olivier-roussel's work on fetching mechanism. But since the 3.24 version is no longer required, it could be the same than SOFA.

**Comment by alxbilger** [comment]
[ci-build][with-all-tests][force-full-build]

**Comment by alxbilger** [comment]
[ci-build][with-all-tests][force-full-build]

**Comment by alxbilger** [comment]
@bakpaul This PR does not take the latest commits in sofa-framework/ci. Hence, it does not fetch and compile the plugin CSparseSolvers. Here is what I see in the logs:
```
--------------- Clone CI scripts ---------------
pwd = /builds/workspace/sofa-framework/PR-4258/ubuntu_gcc_options_release
Cloning into 'ci'...
640400517e592bfa826a46dea29b6ddd512abf02 Merge pull request #21 from hugtalbot/202308_remove_meshsteploader_from_list
CI scripts are available in /builds/workspace/sofa-framework/PR-4258/ubuntu_gcc_options_release/ci/scripts
```
It's not the latest commit in the master branch. Can you investigate why?

**Comment by bakpaul** [comment]
My bad, I modified the CI to checkout before your changes because I though that I merged too early, but I finally realized that it was useless. So back to normal !

**Comment by alxbilger** [comment]
ok thanks ;)

**Comment by alxbilger** [comment]
[ci-build][with-all-tests][force-full-build]

**Comment by fredroy** [comment]
[ci-build][with-all-tests][force-full-build]

**Review by bakpaul — APPROVED** [review]

**Pull request merged**
