### PR TITLE
[SofaExporter] FIX offset of one dt in WriteState

### PR DESCRIPTION
**Pull request by VannesteFelix**
This PR fix an issue with the WriteState component.

When we are using WriteState, we indicate as an argument the period with which we want to save the states.

The states will be then saved in a file when a modulo of the period is reached.
But I have observed that there is always a one step offset between reaching the time to save and the actual saving.

So I naively add one dt to the time WriteState is working with. 

If there is an other way to resolve this issue without hard-coding in WriteState like I have done, I will be happy implement it 

Thanks in advance
______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by jnbrunet** [comment]
I don't think the current behaviour is wrong.

The order of event in the animationloop is:
```
1. AnimateBeginEvent
2. SetTime(StartTime + dt)
3. AnimateEndEvent
```

The `WriteState` component uses `AnimateBeginEvent`, so in that case, as @hugtalbot  said, you should set the proper periodicity as an argument. This hardcoded fix will break the periodicity of everyone who set their `WriteState` relative to the `AnimateBeginEvent` (at the very beginning of the animation loop, before the time is updated).

**Comment by VannesteFelix** [comment]
Thanks for your remarks.

With what you said @jnbrunet , it is normal that there is a one dt offset. 

So the user has to know how sofa work internally to put the right periodicity ?
And even if he know that, if for example he want to precisely save each 5sc (with a dt of 1sc) with the current behavior it will save at : 6-11-16-21 how can he saved at 5-10-15-20 ?

And why instead of saving at AnimateEndEvent, where if there is change during the step they will be saved, we save at AnimateBeginEvent ?

Maybe I have misunderstood something... in any case thanks in advance for your answers.

**Comment by jnbrunet** [comment]
I'm not sure why you say that the state will be saved at 6-11-...

Having the `WriteState` working at the beginning of the animation loop (before the dt is incremented) means that it is exactly the same as if it was run at the end of the previous animation loop (absolutely nothing will happen between these two events, you can see them as a single point in time).

Let's take an example with a period of 2 with the `DefaultAnimationLoop`
```
>> The positions of the mechanical object at this point represent the state at t=0

t=0
---
BeginEvent() 
          [0 >= 0 + 2]
   --> if (t >= last_write_time + period) then WRITE_STATE()
Collisions() + ConstraintsSolve() + ComputeForces() + TimeSolve()
t = t + dt
EndEvent()

>> The positions of the mechanical object at this point represent the state at t=1

t=1
---
BeginEvent() 
          [1 >= 0 + 2]
   --> if (t >= last_write_time + period) then WRITE_STATE()
Collisions() + ConstraintsSolve() + ComputeForces() + TimeSolve()
t = t + dt
EndEvent()

>> The positions of the mechanical object at this point represent the state at t=2

t=2
---
BeginEvent() 
          [2 >= 0 + 2] TRUE
   --> if (t >= last_write_time + period) then WRITE_STATE()
Collisions() + ConstraintsSolve() + ComputeForces() + TimeSolve()
t = t + dt
EndEvent()

>> The positions of the mechanical object at this point represent the state at t=3
```

Setting a period of 2 with a dt of 1 will save the state of your object at t=2, 4, 6, ...

**Comment by VannesteFelix** [comment]
Ok thanks a lot @jnbrunet for the explanation,
I now understand my problem that wasn't one actually...

It still remain that there is a confusion (from where mine come from) that on the GUI it display: 
- "Time : myPeriodicity*n"
and it will save when it display:
- "Time : myPeriodicity*n+dt"
but internally it really saved with the time myPeriodicity*n.

Can we add in the writeState condition the possibility to save also during AnimateEndEvent ?
Normally it won't change the behavior of the writeState component but it will allow to remove the GUI confusion I have got.

**Comment by guparan** [comment]
Hey @VannesteFelix, should this PR be closed?

**Comment by damienmarchal** [comment]
Hello @VannesteFelix 
Can you answer plz so we can move forward with this PR.

**Comment by VannesteFelix** [comment]
Hello,

I have just commit what I have proposed in my last comment.
If you find it useful, please merge it, else we can close this PR. 

Thanks

**Comment by jnbrunet** [comment]
Your modification will have the effect of writing the state both at the beginning and at the end of the step, the last one overwriting the previous one, hence resulting in two writes having the same result (only the afterstep state).

I would suggest to add a data parameter to the object allowing the user the choose either the start or the end of the step, keeping the default value of this new parameter as the current behaviour (begin event).

**Comment by VannesteFelix** [comment]
Yes you are right @jnbrunet .

I think adding a parameter isn't a good solution because in the end this parameter won't change the resulting state saved but when it's saved.

I propose either we keep it like that with a saved at  AnimateBeginEvent which can eventually confuse people (and I speak from experience) on the real time it was saved, or change it to save during AnimateEndEvent.

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
Same changes were done in #714 so I close this one :wink:

**Pull request closed without merging**
