### PR TITLE
[SofaGeneralEngine] Add a computeBBox to the SmoothMeshEngine

### PR DESCRIPTION
**Pull request by untereiner**
______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
Let's add a test like in https://github.com/sofa-framework/sofa/pull/289 !

**Comment by damienmarchal** [comment]
Looks all good to me ... and gg guillaume for the extra test.

**Comment by guparan** [comment]
All rewards go to @untereiner ;-)

**Comment by damienmarchal** [comment]
My mistake, It is probably because I'm used to see  Guillaume doing the ultimate polishing in PRs :)

**Comment by damienmarchal** [comment]
[ci-build]

**Pull request merged**
