### PR TITLE
[SofaFramework] Create Sofa.LinearAlgebra (BaseVector/BaseMatrix & co)

### PR DESCRIPTION
**Pull request by fredroy**
Starting point for #2150 

Create a new module in SofaFramework called Sofa.LinearAlgebra, aiming to gather all structures related to linear algebra, i.e
stuff related to BaseMatrix & BaseVector.
To ensure maximum compatibility, this PR does not propagate the change to the whole SOFA. The downside of this is that SOFA cannot compile without the Sofa.Compat module for the moment (should be ok as the option is ON by default).
Further PRs:
 - move tests as @alxbilger has well commented,
 - move other *Matrix/Vector things from BTDLinear, etc
 - split and create separate files for BlocFullMatrix
 - and before the v21.12 release, effectively change the code base to only use sofa::linearalgebra and not the compatibility layer.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Review by alxbilger — CHANGES_REQUESTED** [review]
Very good initiative!
As a first review, I suggest to also move the type-parameterized tests of BaseMatrix, which are now in SofaDefaultType.Testing. And probably put it in Sofa.LinearAlgebra.Testing.

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Pull request merged**
