### PR TITLE
[SofaNG] Setup Topology

### PR DESCRIPTION
**Pull request by fredroy**
1st big guy

#1527
based on 
- #2605

Deprecates **SofaBaseTopology**, **SofaGeneralTopology**, **SofaMiscTopology**;
Partially deprecates **SofaNonUniformFem** and **SofaTopologicalMapping**

Dispatches the topology-related stuff between:
 - **container** : storing topology information, and itself split in 3 parts:
     - **~~static~~constant container:** static topologies with containers, does not handle topological change
     - **dynamic container**: topologies with containers and handle topological change (topoalgo, geoalgo, container and modifier)
    - **grid**: topologies based on grid (and no containers like the other ones) 
- **mapping**: topological mappings
 - **utility**: components making topological operations on other components for example 

This compat layer on this one is less efficient, as people is more relying on this one than the others.
Reminder: the compat layer does not really work well if:
 - using forward declarations (but it means that the fwd declaration itself was useless in the first place),
 - using explicit instanciations somewhere else (as you cannot use explicit instanciations on templated aliases)
 - you did not include previously the good header for what you are using (e.g some code are using MeshtTopology but does not include MeshTopology.h)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Review by alxbilger — APPROVED** [review]
That's a tough one!
I used https://github.com/fredroy/sofa/compare/sofang_utils...sofa_topology to review your PR.
It seems logical. I guess only the names are to discuss in a meeting.

**Comment by alxbilger** [comment]
Some builds are hanging

**Comment by fredroy** [comment]
[ci-build][force-full-build][with-all-tests]

**Pull request merged**
