### PR TITLE
Stc4 improve scene checkers

### PR DESCRIPTION
**Pull request by damienmarchal**
______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by bcarrez** [comment]
Looks ok to me. Should be merged after the lunch break !

**Comment by guparan** [comment]
Do not hesitate to push directly in deprecating_components ;-)

**Comment by guparan** [comment]
To keep history simple, I will push your commit manually and close this PR afterwards.

**Comment by damienmarchal** [comment]
I didn't want to commit directly in the branch to avoid breaking it but it seems that the main branch is already broken ;)

**Pull request closed without merging**
