### PR TITLE
[MultiThreading] removed the boost thread dependency

### PR DESCRIPTION
**Pull request by epernod**
______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
Here it is @fspadoni
and I just checked the configure script of the CI, this plugin is compiled.

**Comment by fspadoni** [comment]
I tried to fix the linux compiling error. 
Hope it works

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by damienmarchal** [comment]
Hi @epernod , @fspadoni 

Thanks for the PR. 
This is the kind of code I would like to have test unit for. Do you think it could be possible ?

**Comment by epernod** [comment]
Definitively, @damienmarchal could you point out an example of component/class unit test well written. To have the best practice.

**Comment by damienmarchal** [comment]
Hello Erik,

I don't know there is no so much places where I consider the tests well written :)
I like the following:
- vector_test.cpp and Utils_test.cpp are interesting because they use the INSTANTIATE feature of gtest
- SimpleApi_test.cpp is interesting especially the "SimpleApi_test::testParamString" as it use the c++ api equivalent to the python one to create dynamic scenes. 
- BaseContext_test is also interesting because it inherit the test from BaseSimulationData

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Pull request merged**
