### PR TITLE
[CMake] Start finding Qt6 then Qt5

### PR DESCRIPTION
**Pull request by hugtalbot**
As discussed in the SOFA dev meeting, prefer now using Qt6 over Qt5. Therefore, look firstly for Qt6 before Qt5.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Review by fredroy — CHANGES_REQUESTED** [review]
Did you try ? (i.e having both and try to compile)
I did on Ubuntu 22.04 and it does not work at all 👮

**Review by alxbilger — CHANGES_REQUESTED** [review]
I think you also need to modify the following part:

```cmake
# Will only use Qt6 if Qt6 is found and Qt5 is not found
# if Qt5 and Qt6 are both found, Qt5 will take priority
# Qt6 needs cmake >= 3.16, https://doc.qt.io/qt-6/cmake-get-started.html 
find_package(Qt5 COMPONENTS Core QUIET)
if (NOT Qt5Core_FOUND)
    if(${CMAKE_VERSION} VERSION_GREATER "3.16.0")
        find_package(Qt6 COMPONENTS Core CoreTools QUIET)
    endif()
endif()
```

**Comment by fredroy** [comment]
> I think you also need to modify the following part:
> 
> ```cmake
> # Will only use Qt6 if Qt6 is found and Qt5 is not found
> # if Qt5 and Qt6 are both found, Qt5 will take priority
> # Qt6 needs cmake >= 3.16, https://doc.qt.io/qt-6/cmake-get-started.html 
> find_package(Qt5 COMPONENTS Core QUIET)
> if (NOT Qt5Core_FOUND)
>     if(${CMAKE_VERSION} VERSION_GREATER "3.16.0")
>         find_package(Qt6 COMPONENTS Core CoreTools QUIET)
>     endif()
> endif()
> ```

not only that .... 🙈

**Comment by fredroy** [comment]
https://github.com/hugtalbot/sofa/pull/111

**Review by fredroy — APPROVED** [review]
Tested on ubuntu 2204 with both qt5 and qt6 installed

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Review by bakpaul — APPROVED** [review]

**Pull request merged**
