### PR TITLE
[SofaGeneralEngine] ADD computeBBox in BeamFEMForceField. FIX Vertex2Frame

### PR DESCRIPTION
**Pull request by raffaellatrivisonne**
Fixed Vertex2Frame (deleted a _return_ which prevented the component to work properly)

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
[ci-build]

**Comment by guparan** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
Let's start a fresh [ci-build]  against recent master.

**Comment by damienmarchal** [comment]
It compile...now warnings or test failure so let's merge it. 
Thanks raffaela.

**Comment by damienmarchal** [comment]
I should buy new glasses...one of the tests is now failing. I think this is minor and I'm not sure if the test or the component have to be fixed.

**Comment by guparan** [comment]
It seems that `serr` was outputed as WARNING in the test and thus not making it fail. See pre-merge output [here](https://ci.inria.fr/sofa-ci/job/ubuntu_clang-3.8_options/267/consoleText) and search for "Vertex2Frame : no vertices or normals found..."
Replacing it with `msg_error` create a "real" error so the test fails.

**Comment by damienmarchal** [comment]
Thanks guillaume for the investigation,
The easy solution is to use msg_warning instead (restoring the old behavior). 
But shouldn't something that prevent the component to work be reported as an error  and thus we should fix the test ?

**Pull request merged**
