### PR TITLE
[SofaKernel] Remove un-needed StringUtil.h in Base.h

### PR DESCRIPTION
**Pull request by damienmarchal**
My most important PR so-far.

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by olivier-goury** [comment]
I love these kind of PRs

**Comment by damienmarchal** [comment]
Come on, no-one pressed the merge button.

**Comment by fredroy** [comment]
Tests passed so, mergin' 🎵

**Comment by damienmarchal** [comment]
You are so brave Fred. (Of course brave like in braveheart...not like a "un brave homme"). 


...but I just noticed.... you didn't merged it ...I retract the bravity token.

**Comment by damienmarchal** [comment]
I think I have to merge it myself...

"pfff faut tout faire ici."

**Comment by fredroy** [comment]
ahah I wanted to leave a message and merge... And I just left the message.
🥇

**Comment by damienmarchal** [comment]
It is important to focus on the important and drop the superfluous.

**Pull request merged**
