### PR TITLE
[all] ISSofa merge: Multithreading

### PR DESCRIPTION
**Pull request by guparan**
This PR is certainly the biggest contribution from InSimo merge sprint.   
It will be further discussed during STC#3.

### New features
- Add logGraphUpdates / logDataUpdates global variable in objectmodel to be able to debug multi-threading issue (not declared in headers, temporary until a better design is proposed)
- Add a flag d_threadsafevisitor in solvers to disable writing in mechanicalstates of InteractionForceField in MechanicalVReallocVisitor/MechanicalVFreeVisitor as it might crash in multithreaded context
- Add `Contact::computeResponse()` and `Contact::finalizeResponse()` to separate thread-safe from sequential parts of the response computations
- Implement thread-safe Data engine/links updates by adding a lock while calling update().This requires that requestUpdate() or requestUpdateIfDirty() be called instead of update() directly, which is now protected.Bonus side effect is that it no longer matter where or if engines call cleanDirty() in their update method.
- Update all engines to new thread-safe design
- Add execution info in Task and index in WorkerThread
- Add support for multithreaded task logging (for visual profiling)
- Add some const correctness in getColor and getName methods.

### Improvements
- Remove ClassInfo, deprecated in favor of BaseClass, and make sure all static instances are initialized while registering objects in the factory, to FIX "pure virtual call" crashes with visual c++ in multi-threaded contexts
- Replace `Creator<Contact::Factory,` with `sofa::core::collision::ContactCreator<` to improve thread safety of contact creation.
- AnimateBeginEvent and AnimateEndEvent can now receive an optional pointer to a TaskStatus ( in a form of a void pointer ). When using SofaMultithreading, this taksStatus pointer can be used to spawn the AnimateBeginEvent method in a separate thread. It is the reponsibility of the component to decide whether or not its AnimateBeginEvent method is thread safe.
- Change BaseObject argument parsing. When parsing, ensures if src attribute is used with link @ now allow the use of src="". Topologies container associated to src="" are supposed to be filled by following topological mapping. Using src="@" to avoid link warning drove to an autolink where the loader refers on container itself. Modification of implicated scenes and xml accordingly.
- WorkerThread maintains a list of stealable tasks as well as a list of higher priority thread specific tasks. Remove ThreadSpecificTask (not used and redundant with new thread-specific task queues). Update Task logging.
- Adapted MultiThreading plugin to the new build system.
- SetDirectory no longer changes the system current directory (shared by all threads in the process), but uses a global variable to record the current directory to be used within Sofa. But changing to the current file's directory is needed to load Python scene. For the moment, python loader is not use with multithreading, changing directory in the loader is a temporary solution. The functioning of python scene loader need to be adapted in the futur.

### Cleans
- Streamline calls to createResponse in case no groupManager is used
- Clean warnings in Task and TaskSchedulerBoost for Multithreading plugin.

### Bugfixes
- Fix crash with multithreaded collision detection. Call `TriangleModel::getTriangleFlag` method for all triangles of the topology to force the initialization of adjacency.information in the topology before some actual collision detection code is executed.
- DDGNode should never be copied to ensure thread safe. Add private copy constructor that gives compilation error to ensure that.
- Compilation fixes for compatibility with boost 1_55. Corrected also the copyright notice.
- Fix execution freeze bug due to simultaneous and reciprocal task stealing between 2 threads (WorkerThread).
- Fix data race at startup, WorkerThread:mTaskScheduler was set by the main thread while being read by the worker thread.

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings nor unit test failures.
- [ ] does not break existing scenes.
- [ ] does not break API compatibility.
- [ ] has been reviewed and agreed to be transitional.
- [ ] is more than 1 week old.

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
[build-ci]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by matthieu-nesme** [comment]
It was decided on the STC not to merge this PR in the actual state, but to wait for more commits.

**Comment by guparan** [comment]
Let's close this PR for now, waiting for news from InSimo...
@JeremieA, @fjourdes, @Ngautier

**Pull request closed without merging**
