### PR TITLE
[SofaBaseMechanics] Restore useRestPos Data initialization for BarycentricMapping

### PR DESCRIPTION
**Pull request by fredroy**
The initialization of the data disappeared at some point in the past 🤥
This PR restores it.

Credits to:
 - [InSimo](https://github.com/InSimo)(@JeremieA , @fjourdes ) 
 - @remibessard who reported it back to us

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
Can we take the opportunity to renaming it `d_useRestPosition` ?

**Review by guparan — APPROVED** [review]

**Comment by guparan** [comment]
> 
> 
> Can we take the opportunity to renaming it `d_useRestPosition` ?

I'm not sure it's a good idea to transform a fix into a breaking change. Waiting for @fredroy insight :mag:

**Comment by fredroy** [comment]
> 
> 
> > Can we take the opportunity to renaming it `d_useRestPosition` ?
> 
> I'm not sure it's a good idea to transform a fix into a breaking change. Waiting for @fredroy insight 🔍

Exactly my thoughts.
Wondering the fact that indeed this is badly needed BUT it will be breaking.

Arguments for renaming:
 - does not follow the guideline and the other Data<> in BarycentricMapping are following it,
 - referenced only **ONCE** in the whole sofa code base
 - does not breaking anything scene-wise (the stringName wont change)

Arguments for not renaming:
- breaking plugins using this Data<> directly

Conclusion: 
My opinion would be to rename it indeed 🧐

**Comment by epernod** [comment]
as all the others Data of this components already have the d_. I'm for renaming it as well.

**Comment by fredroy** [comment]
Actually this is not really true, the problem is that the other things with a 'd_' are NOT data 🤪, they are Link and thus should be prefixed with 'l_' . 
So this class is not following the correct guidelines 😬 (and members not having 'm_' etc...)

**Comment by epernod** [comment]
ok... I think we should do an afternoon of brainless coding sprint to update all those components with the good guidelines... 
so this one is ready to go I guess. 
LGTM !

**Pull request merged**
