### PR TITLE
[examples] Fix or disable scene tests

### PR DESCRIPTION
**Pull request by guparan**
WIP PR.
For now, it disables all python scenes in Flexible and Compliant.

IMPORTANT: do not merge until https://github.com/sofa-framework/SofaPython3/tree/fix_or_disable_scene_tests is merged into SofaPython3 and ExternalProject tag is reset to master here.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by fredroy** [comment]
[ci-build][with-scene-tests]

**Comment by fredroy** [comment]
[ci-build][with-scene-tests]

**Comment by fredroy** [comment]
Somebody has to merge https://github.com/sofa-framework/SofaPython3/pull/126 before changing the pointer for SofaPython3...

**Comment by jnbrunet** [comment]
Looks like the SP3 tag hasn't been reset to the master branch, or I am missing something? @guparan

**Pull request merged**
