### PR TITLE
[SofaHelper] Handle recent MSH format in MeshGmshLoader

### LINKED ISSUE #1528: Gmsh recent format not supported
This 
$MeshFormat
4.1 0 8

is not supported in MeshGmshLoader

### LINKED ISSUE #2433: MeshGmshLoader does not handle latest gmsh format
### Problem

**Description**
The MeshGmshLoader does not seem to handle latest gmsh format.

Associated Forum post: https://www.sofa-framework.org/community/forum/topic/unable-to-load-mesh/

---------------------------------------------

### Environment

**Context**

- System: Windows 10 + Ubuntu 18.04
- Version of SOFA: master branch + v21.06.00 binaries

**Command called**

```txt

runSofa examples/Components/loader/MeshGmshLoader.scn

```

---------------------------------------------

### Logs

**Full output**

```txt

[ERROR]   [MeshGmshLoader(GmshLoader)] File 'sq.msh' finally appears not to be a Gmsh file.

```

File to test:
[sq.zip](https://github.com/sofa-framework/sofa/files/7372243/sq.zip)

### PR DESCRIPTION
**Pull request by Camille-K**
This is an attempt at fixing #1528.

At the moment, file parsing in MeshGmsh.cpp and MeshGmshLoader.cpp is (hopefully) correctly handled, including more recent MSH file formats (=>4.0).
EDIT: I don't fully understand how the loader works, mainly why MeshGmshLoader::readGmsh() is temporarily not used (commented in l.111), with the parsing apparently relying only on MeshGmsh::readGmsh(). However I tried to keep the same structure as before, simply taking into account the case where the .msh version is > 2.
A .msh file with version 4.1 is added (share/mesh/msh4_cube.msh), and its parsing by the MeshGmshLoader is tested both in examples/Components/loader/MeshGmshLoader.scn and in a new unit test. Both tests are working locally.

Regarding the original purpose of #1528, the PR should be sufficient.

Fixes #2433 #1528
______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by Camille-K** [comment]
[ci-build][with-all-tests]

**Comment by Camille-K** [comment]
[ci-build][with-all-tests]

**Comment by Camille-K** [comment]
[ci-build][with-all-tests]

**Review by epernod — APPROVED** [review]

**Pull request merged**
