### PR TITLE
[SofaExplicitOdeSolver] Introduce examples scenes

### PR DESCRIPTION
**Pull request by alxbilger**
Introduce examples scenes for 4 cases of Euler explicit solver:
1) Mass matrix is not diagonal and Euler is not symplectic: EulerExplicitSolver.scn
2) Mass matrix is diagonal and Euler is not symplectic: EulerExplicitSolver_diagonal.scn
3) Mass matrix is not diagonal and Euler is symplectic: EulerSymplecticSolver.scn
4) Mass matrix is diagonal and Euler is symplectic: EulerSymplecticSolver_diagonal.scn

I did my best to create stable scenes, but it is not that simple with an Euler explicit solver. Especially if not symplectic. It comes at the price of very small time step sizes.

This PR is based on #2163. It will need to be updated after #2165 is merged

[ci-depends-on https://github.com/sofa-framework/Regression/pull/15]

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by alxbilger** [comment]
Now that https://github.com/sofa-framework/sofa/pull/2165 is merged, I could remove the Data `optimizedForDiagonalMatrix` from the scenes. I confirm that the code goes to the right branch depending on the diagonal property of the mass matrix.

**Comment by fredroy** [comment]
Two regression tests are failing :
- Regression_test/StateRegression_test.sceneTest/EulerExplicitSolver
- Regression_test/StateRegression_test.sceneTest/EulerExplicitSolver_diagonal

I suppose this is because you moved them into a new folder and the Regression project has not been updated accordingly.

**Comment by alxbilger** [comment]
@fredroy, yes it makes sense. Thanks for pointing it out.

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by guparan** [comment]
[ci-build][with-all-tests][force-full-build]

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Review by fredroy — APPROVED** [review]

**Pull request merged**
