### PR TITLE
[ManifoldTopologies] Undust and clean

### PR DESCRIPTION
**Pull request by epernod**
Clean Manifold Topologies plugin:
- Replace serr/sout by msg_
- Move all code inside cpp files
- Clean header inclusions
- Fix template declaration
- Clean warnings

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Review by guparan — COMMENTED** [review]
Hey @epernod, you could replace a lot (all?) of `if (CHECK_TOPOLOGY)` blocks by `msg_XXX_when(CHECK_TOPOLOGY)` :wink:

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
> Hey @epernod, you could replace a lot (all?) of `if (CHECK_TOPOLOGY)` blocks by `msg_XXX_when(CHECK_TOPOLOGY)` 😉

done.

**Comment by damienmarchal** [comment]
Ben merge.

**Pull request merged**
