### PR TITLE
Flexible smoothing

### PR DESCRIPTION
**Pull request by BenjaminGilles**
[Flexible] add engines and examples for strain smoothing, and minor cleaning

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hi Benjamin, 

Maybe I'm wrong but it seems to integrate a lot of commit touching a lot of different sofa part (SofaKernel, SofaOpenGL) which does not precisely match the pull-request description.

Wouldn't it be better to separate that into several more specific pull-request ?

**Comment by matthieu-nesme** [comment]
Yes. Benjamin I do not know what you did exactly.
The modifications seem good but the incorporated commits are not. (I guess it can create trouble if we want to merge them later).
I'll create your PR, so you'll see how to do.

**Comment by matthieu-nesme** [comment]
Benjamin, have a look to #77.
I branched upstream/master, and I cherry-pick only your commits in this branch.

**Comment by BenjaminGilles** [comment]
Hello, 
yes sorry I messed up with my git client.
I cherry picked the right modifications, but I integrated many older commits somehow.
I guess we can close this PR, and pull Matthieu's one instead.

**Pull request closed without merging**
