### PR TITLE
[SofaKernel] In DataFileName, the name FILE used in the PathType enum could be ambigous 

### PR DESCRIPTION
**Pull request by epernod**
FILE should stay a C keyword for managing FILE

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings.
- [ ] does not generate new unit test failures.
- [ ] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hello @epernod,

Thanks for the fix... I also fixed it in a different way (and lost in the middle of all the changes) in the PR#1460. 
My fix was using enum class (C++11) instead of the classic enum (C). Enum class was designed to specifically avoid name clash so it is nice to use them.

**Comment by epernod** [comment]
> Hello @epernod,
> 
> Thanks for the fix... I also fixed it in a different way (and lost in the middle of all the changes) in the PR#1460.
> My fix was using enum class (C++11) instead of the classic enum (C). Enum class was designed to specifically avoid name clash so it is nice to use them.

Ok just saw your fix @damienmarchal . Do you prefer your way? I can change this PR.

**Comment by damienmarchal** [comment]
Yes c++11 way is the right one :)

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Review by marques-bruno — APPROVED** [review]

**Comment by damienmarchal** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by damienmarchal** [comment]
THere is 16 scene crashing on centos....but this seems to be because of timeout.
Any idea ?

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
> THere is 16 scene crashing on centos....but this seems to be because of timeout.
> Any idea ?

blinking time out errors on the CI I guess...

**Comment by damienmarchal** [comment]
So can you confirme that this PR does not fails on the scene on your PC ?

**Comment by epernod** [comment]
Yes I'm using that fix and I do not see errors but I didn't run all the tests.

**Comment by guparan** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Pull request merged**
