### PR TITLE
[SofaPython] Reload all the imported python modules when reloading a scene (CTRL+R)

### PR DESCRIPTION
**Pull request by damienmarchal**
This PR is an attempt to solve the  problem pointed in Issue #193 

Problem summary: 
Currently in runSofa when reloading the scene only the ScriptController's are reloaded but not the python code imported by the controllers. 

This PR:
solve the issue which avoid to restart runSofa each time an imported module used by a ScriptController is changed. 

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [ ] does not generate new warnings nor unit test failures.
- [ ] does not break existing scenes.
- [ ] does not break API compatibility.
- [ ] has been reviewed.
- [ ] is more than 1 week old.

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by matthieu-nesme** [comment]
Thanks a lot for being able to solve that because it has been a pain in the ass for too long!

But please, remove all that stuff about plugin reinit!!! Moreover it depends on the app/gui implementation, it is not satisfying.

I think a simple workaround would do the job in PythonEnvironment::Init():
`
PyRun_SimpleString("
try: __SofaPython_mainenvironment__.uninstall(); except: __SofaPython_mainenvironment__=ImportFrame()");
`
(approximative code)

**Comment by damienmarchal** [comment]
The problem is to have the uninstall function called when we need to reload the files (when the end user application is reloading). 

This can be done per PythonScriptController in the 'cleanup' code. But the cost will be repeated each time a PythonScriptController is created/destructed in the scene so I'm not a big fan of it. Neither for the explicit reinit.
 
I don't understand your suggestion.

A pure python solution may be to install a kind of hook in python that count the number of PythonScriptController that is created...and count the number of cleanup...and if this cleanup count is zero...it means we need to force a plugin reload.  It may work but I'm not sure this is very good because creating PythonScriptController on the fly and deleting them would force module reload.  

The last solution I can think abou tis to have the PythonEnvironment inheriting from BaseObject and thus...be part of the scene (automatically added in the root) ... this PythonEnvironment will thus receive a single cleanup event and do the cleaning when it deserve to. 
This solution sound conceptually ok to me if we accept that our scene contains an automatically added object.

**Comment by matthieu-nesme** [comment]
I'll propose a light version based on your code.

**Comment by damienmarchal** [comment]
Feel free to commit in this PR.

**Comment by matthieu-nesme** [comment]
It is done in #202.

**Comment by damienmarchal** [comment]
I added here a second version based on having a single PythonEnvironment in the scene. 

This component have in charge the cleaning of python environment when the scene is about to be destroyed. 

Conceptually it is quite ok, the drawback is that to be installled in the scene it have to check it does not yet existing using the getNodeObject function which is a non-constant time one. 
So compared to the 'reinit' based approach it have overhead.

**Comment by damienmarchal** [comment]
This will go into PR 202 So I close it.

**Pull request closed without merging**
