### PR TITLE
[examples] Remove scenes about deprecated components

### PR DESCRIPTION
**Pull request by guparan**
The title says it all. Feel free to comment if any of the removed scenes should be kept.

Removed scenes:
- Components/controller/ArticulatedHierarchyBVHController.scn
- Components/controller/EdgeSetController.scn
- Components/controller/MechanicalStateController.scn
- Components/controller/NodeToggleController.scn
- Components/forcefield/BuoyantForceField.scn
- Components/forcefield/BuoyantForceField2Boxes.scn
- Components/forcefield/ForceMaskOff.scn
- Components/forcefield/WashingMachineForceField.scn
- Components/mapping/CatmullRomSplineMapping.scn
- Components/mapping/ProjectionToTargetLineMapping.scn
- Components/mapping/ProjectionToTargetPlaneMapping.scn
- Components/topology/HexaCenterPointMapping.scn
- Demos/10000.scn

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Hi guillaume,

is there a error/warning when someone is using a removed componet saying that the component has been removed ...and need to contact us for re-adding it ?

**Comment by guparan** [comment]
Yes I actually fixed it in https://github.com/sofa-framework/sofa/pull/905, see https://github.com/sofa-framework/sofa/commit/c608d441edd35f6e8eb90ebfc420cb941c3bd750 and https://github.com/sofa-framework/sofa/commit/e1b55cba5ff200c7a11f6992974159b55cec000f.

The error is printed on CI but you have to open the output of a scene test to see it (Jenkins only shows the first line of an error in the "SOFA SceneTest Errors" view).

See for example the [output of failing scene Components/forcefield/ForceMaskOff.scn](https://ci.inria.fr/sofa-ci-dev/job/sofa-framework/job/master/CI_CONFIG=ubuntu_gcc-5.4,CI_PLUGINS=options,CI_TYPE=release/636/artifact/parent_dir/build/scene-tests/examples/Components/forcefield/ForceMaskOff.scn/output.txt) (latest master build).

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
So the 3 remaining scenes are:
- edgeDeformationMapping.scn needing CatmullRomSplineMapping
- optitrackGrasping.scn needing GraspingManager
- MechanicalStateController.scn needing EdgeSetController

Any idea of what to do with them guys? As they are not component specific, it may be important to keep them.

**Pull request merged**
