### PR TITLE
Adding GLSL livecoding basic support

### PR DESCRIPTION
**Pull request by damienmarchal**
This commit add the ability to edit shader while sofa is running and on-the fly updating the rendering.
This is an improvement on the workflow for anyone that is developing shading code.

Some may be concerned about performances issues so here are more details: 

The overhead is near zero.
    The GLSLListener is triggered by the file FileMonitor.
    FileMonitor is using the event based "select" system API and is not actively 'polling' the files. AFAIK this is the most efficient way to monitor files.
    If the application don't call FileMonitor::update(0) then this cost nothing.

Currently only runSofa is calling FileMonitor::update(0) when started with the -i (for interactive) command line option.

So the different scenarios are:
    your own app.... (no cost)
    runSofa -i & changing the file (this cost the reload of the shader (few millisecond each change)
    runSofa -i & not changing the file (this cost calling the select system call)
    runSofa as usual...this cost nothing.

### CODE REVIEW

**Comment by damienmarchal** [comment]
Arg!!! I didn't notice the pull request will containes also the Idle renaming that is a different pull-request not yet accepted in sofa... how do we handle this case ?

**Comment by matthieu-nesme** [comment]
I think there could be a memory leak if InitGLSL is called several times.
Would not it be easier/cleaner to handle m_filelistener with a smart pointer?
Otherwise, all good!

**Comment by damienmarchal** [comment]
Hi Mathieu, 

Thank for your review. 
InitShader or InitGLSL ? 

About the InitShader function as it was containing some memory management code 
```cpp
   // If any of our shader pointers are set, let's free them first.
    if(!m_hShaders.empty() || m_hProgramObject)
        Release();
```
I assumed that is was already ok to be called several time and that it was not leaking memory, maybe I was wrong so I will look at that more carefully. 

I will also clean the thing with the m_filelistener (even if I think the right way would be to change the API of the FileMonitoring API (but this must be done in a separated pull-request))

About InitGLSL I see no memory allocation there ?

**Comment by matthieu-nesme** [comment]
oh sorry it was in the constructor, so there were no pb...

**Comment by damienmarchal** [comment]
@hugtalbot  Can you merge it please (unless someone see problems and give feedback)

**Pull request merged**
