### PR TITLE
[SofaKernel] Improve File:line info in error message (for python and xml error reporting)

### PR DESCRIPTION
**Pull request by damienmarchal**
Currently when object are unable to be created there is no filename/line information on where the problem come from. 

In this PR I implemented the missing <<operator in messaging.h to report those line number. 
Now you can write: 
```cpp
  msg_info() << SOFA_FILE_INFO_COPIED_FROM("myPythonFile.py", 4) << "blah balh" 
```
To have the file name & line number associated in the message emitting information. If you don't the emitting information will be the source code file&line location. 

If updated the xml load to take this feature into account. 
The python loader is updated in the PR #304 

 
______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by bcarrez** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by bcarrez** [comment]
Note: the build fail on OSX is due to API change in boost 1.64 that makes the Multithreading plugin fail to build. I would not pay attention to it until Multithreading is fixed.

**Comment by damienmarchal** [comment]
Fixed the conflict...let's rebuild

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
The CI finished but the dashboard is not up-to date.
The test failure are pre-existing to the PR. So I merge it.

**Pull request merged**
