### PR TITLE
[SofaSphFluid] Externalize SofaSphFluid

### PR DESCRIPTION
**Pull request by bakpaul**
Externalize the plugin SofaSphFluid and add the fetching mechanism. This aims at disabling the regression tests when it is not built (e.g. for default configurations on the CI)

I've externalized the plugin here: https://github.com/sofa-framework/SofaSphFluid and kept the history of changes

[ci-depends-on https://github.com/sofa-framework/Regression/pull/61]
[ci-depends-on https://github.com/sofa-framework/ci/pull/46]

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by bakpaul** [comment]
[ci-build][with-all-tests]

**Comment by bakpaul** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
so the CI will not test SPH regression anymore?

**Comment by bakpaul** [comment]
Yes it will, but not for 'default' configurations, but - - for 'options' one. Those are the same as the one compiled by the PRs. It actually changes nothing but removes regression errors for 'default' configuration (only on the dashboard) because the lib was not found, which is normal because it is not compiled. 

This PR comes along with two other ones on Regression and ci to remove the regression files and add the fetching for 'option' configurations.

**Review by fredroy — APPROVED** [review]

**Comment by bakpaul** [comment]
[ci-build][with-all-tests]

**Pull request merged**
