### PR TITLE
[Core.Topology] Restore invalid ids in invalid containers

### PR DESCRIPTION
**Pull request by alxbilger**
Issue introduced in https://github.com/sofa-framework/sofa/pull/1167. The static variables were no longer initialized.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by fredroy** [comment]
Well spotted ! 🤘

**Review by fredroy — APPROVED** [review]

**Comment by fredroy** [comment]
But better than assiging invalidID at runtime, should not we just dtich this function and inline static constexpr the InvalidXXXInYYYYY ?
Actually in the present case, the InvalidXXXInYYYYY can be modified...

```
    inline static constexpr EdgesInTriangle        InvalidEdgesInTriangles {sofa::InvalidID, sofa::InvalidID, sofa::InvalidID};
    inline static constexpr EdgesInQuad            InvalidEdgesInQuad {sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID};
    inline static constexpr TrianglesInTetrahedron InvalidTrianglesInTetrahedron {sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID};
    inline static constexpr EdgesInTetrahedron     InvalidEdgesInTetrahedron {sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID };
    inline static constexpr QuadsInHexahedron      InvalidQuadsInHexahedron {sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID };
    inline static constexpr EdgesInHexahedron      InvalidEdgesInHexahedron { 
        sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID,
        sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID, sofa::InvalidID
    };
```

**Comment by alxbilger** [comment]
@fredroy thanks for the suggestion. I was thinking about it actually. And here is my proposition. Let me know what you think

**Comment by fredroy** [comment]
> @fredroy thanks for the suggestion. I was thinking about it actually. And here is my proposition. Let me know what you think

even better 👍
But i am surprised you dont need the `inline` keyword when you initialize the static member(s) 🤔

**Comment by alxbilger** [comment]
> > @fredroy thanks for the suggestion. I was thinking about it actually. And here is my proposition. Let me know what you think
> 
> even better 👍 But i am surprised you dont need the `inline` keyword when you initialize the static member(s) 🤔

Maybe I do need it, but at least it compiled with MSVC

**Comment by fredroy** [comment]
Seems the `inline` keyword is not necessary, maybe because the `constexpr` keyword is inline by itself

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by alxbilger** [comment]
@epernod Can you have a look on my changes in TopologyChecker. I had to add this to satisfy the unit tests in TopologyChecker_test. Otherwise, it crashes.

**Review by fredroy — APPROVED** [review]

**Pull request merged**
