### PR TITLE
[Component.Setting] Introduce PrintLog component to set printLog to all the graph components

### PR DESCRIPTION
**Pull request by alxbilger**
A detailed description of the component is provided in the code
Unit tests are added.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
I understand the feature, I understand the need and I agree I would use it.... but I find really weird to set the option using a component in the graph...

Do you know if there is an option in the Node? we could use the same logic but per Node

**Comment by epernod** [comment]
Ok sorry my message was not totally clear. I meant, you check the option in the Node and it propagate the printLog to all child Node and their components.
So if you want all the printLog, you activate it in the root Node.
Just suggesting.

**Comment by alxbilger** [comment]
Thanks for you feedback @epernod. I think your suggestion is the more natural. Actually, I tried to set `printLog` in a log, to see if it was already working (but no). But I always feel uncomfortable when modifying such an important base class. I don't want that some classes become God classes. That's why I did not touch the Node class. But I am definitively open to discussion

**Comment by alxbilger** [comment]
I am ok with the suggestion

**Pull request closed without merging**
