### PR TITLE
[all] issofa_constraintsolving: improve constraints

### PR DESCRIPTION
**Pull request by guparan**
Needed by #459 
@fjourdes I let you add informations in the comments 😉 

### New features
- Add correctionVelocityFactor and correctionPositionFactor Data in UncoupledConstraintCorrection to experiment with modulating the constraint response influence on visual tool positions.
- Add more detail in timing of GenericConstraintSolver.

### Improvements
- Constraint problem locking extended to be safer (but not yet completely safe) when using multiple forcefeedback devices.
- GenericConstraintCorrection: automatically search LinearSolver from context when solverName is not specified (same behavior as LinearSolverConstraintCorrection).
- Factorize the computation of the compliance matrix and virtualize the computation of dx.
- Improve UncoupledConstraintCorrection compliance computation. Use the same factors for the compliance matrix computation and the correction computation as the one used in LinearSolverConstraintCorrection.

### Cleans
- Clean and Optimize UncoupledConstraintCorrection, factorize code between rigids and vecs, optimize addComplianceInConstraintSpace significantly for large number of constraints.
- Move new constraint accumulation visitors from GenericConstraintSolver.h to MechanicalVisitor.h so that they can be used by other solvers.
- Code refactoring in GenericConstraintCorrection.

### Bugfixes
- Fix FreeMotionAnimationLoop allocates the freeposition / freevelocity as first thing in the time step.
- Fix Haptic mode with haptic influence from constraints applied on all frames. It was not working well on the simulation side.
- Add a correction velocity factor and correction position factor as data in UncoupledConstraintCorrection.
- Fix, the GenericConstraintSolver was not providing the correct number of interations for profiler stats.
- GenericConstraintCorrection's ODESolver is now searched locally.
- Fix the Local Jacobian Matrix. It was not resized when no more constraints were applied on a MechanicalState.
- UncoupledConstraintCorrection for rigid is now in a 7 value vector. When using the default initialization of the compliance using the mass matrix of the rigid the linear part of the compliance was added twice.

### Moved files
- Move contact identifier code in a separate file to avoid inelegant FrictionContact.h inclusion in each contact class file.

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by fjourdes** [comment]
There is nothing really to add, however this pr is non breaking. There are no changes in the api whatsoever that will prevent exsiting code to work, since the changes introduced that are breaking are deactivated by default. 
The only breaking change reside in the fix related the factor used in the compliance matrix computation for the `UncoupledConstraintCorrection` to make it consistent with other constraint correction schemes. This fix is deactivated by default since you need to activate the Data `useOdeSolverIntegrationFactors` ( off by default ) to enable this change.

**Review by fjourdes — APPROVED** [review]

**Comment by damienmarchal** [comment]
So there is no "no-go" from any one. So I rebuild from recent master with testing the scene...and then...merge. 
[build][with-scene-tests]

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by damienmarchal** [comment]
@guparan what about merging this one ?

**Comment by damienmarchal** [comment]
[ci-build][build-with-scene]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by guparan** [comment]
[ci-build]

**Pull request merged**
