### PR TITLE
[MultiThreading] FIX: examples installation

### PR DESCRIPTION
**Pull request by Innokentiy-Alaytsev**
Example scene files are in "scenes" directory and not in "examples" directory,
as expected by CMake install command.

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by Innokentiy-Alaytsev** [comment]
Hello!

I'm not sure about what is better: to fix CMakeLists.txt or to rename the directory with example scenes. Can someone clarify this for me?

**Comment by guparan** [comment]
Hi @WilkGardariki,
Thanks for this fix. Let's start the [ci-build]. 
About your question, I guess the simpler is the better. There are other plugins with a scenes folder (CGal, Geomagic).
I am also interested in a _examples vs scenes_ discussion. I personally prefer _scenes_ as I find it more accurate.

**Comment by matthieu-nesme** [comment]
I would rather rename every "scenes" dir in "examples" to follow plugin guidelines.

**Comment by Innokentiy-Alaytsev** [comment]
Hello!

@guparan , what do you think about matthieu-nesme's suggestion? Renaming a directory is not a big deal, I can do it instead of fixing CMakeLists.txt.

**Comment by guparan** [comment]
I'm ok with the renaming but please make sure to add a WARNING in your commit message as it may break some algos for MultiThreading users.

**Comment by Innokentiy-Alaytsev** [comment]
Hello!

Sorry for taking so much time for this - I've taken fancy on my primary work :)

About pull request: I've renamed example scene directory and fixed documentation. I hope no one mind that I've removed the previous version of the commit.

**Comment by guparan** [comment]
[ci-build]

**Pull request merged**
