### PR TITLE
[SofaPython] Add support for Sofa.msg_ with emitter other than a string.

### PR DESCRIPTION
**Pull request by damienmarchal**
The existing Binding does not cover the whole feature of the c++ API.
With this PR it does.This is not breaking anything...it only add new features with their associated tests. 

This allows python messages and error to be routed to the right component and have it added to its backlog and displayed in the GUIs.

______________________________________________________

This PR: 
- [ ] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
Yeah...CI is broken again...

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by guparan** [comment]
This PR is not ready at all, 25 unit tests are crashing 😢

**Comment by damienmarchal** [comment]
Thanks Guillaume for the safe-guard eyes. 
A 2 character fix later now all the tests are passing so I switched the status "to review".

**Pull request merged**
