### PR TITLE
[SofaBaseLinearSolver] Add ability to activate printing of debug information at runtime

### PR DESCRIPTION
**Pull request by damienmarchal**
Here is a very simple implementation that enable extra printing to help in understanding why some scenes are failing/crashing. 

I also add few scenes with single solvers because those components where not tested anywhere in our CI. 

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests]

**Comment by damienmarchal** [comment]
@hugtalbot I was not able to reproduce the scene crash on my pc. 
I will remove the scene :)

**Comment by tgaugry** [comment]
Seems fine for me :+1:

**Comment by damienmarchal** [comment]
@guparan, @hugtalbot Could we considering merging those...they are now wainting since weeks :)

**Comment by damienmarchal** [comment]
[ci-build][with-scene-tests]

**Comment by guparan** [comment]
[ci-build][with-scene-tests]

**Comment by epernod** [comment]
[ci-build][with-scene-tests]

**Pull request merged**
