### PR TITLE
[SofaBaseTopology][DrawTools] Some fix/update in topology internal draw methods.

### PR DESCRIPTION
**Pull request by epernod**
- Update: Set drawColor as Data<RGBAColor> for topology debug drawing.
- Update: triangle and Quad drawing to display them a little smaller to better see the geometry structure.
- Fix: drawing scale indices could be Inf.
- Fix: normal color drawing and check buffer sizes in DrawTool
- Update: replace word colour by color to match openGL spelling in DrawTool

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by epernod** [comment]
removingtetra2triangleprocess_00000004

new version of triangle debug draw

**Comment by epernod** [comment]
tetra2triangletopologicalmapping_00000002

Fix of color normals drawing. RGBAColor = normal direction (X, Y, Z) normalised with alpha = 1.0

**Comment by epernod** [comment]
[ci-build][with-all-tests]

**Comment by damienmarchal** [comment]
Why is it back to wip ?

**Comment by epernod** [comment]
because of this https://github.com/sofa-framework/sofa/pull/877/commits/191fd5bc6fc3e9b2c61416ed396bbaa517b4e72b @damienmarchal . Will be ready to go if compilation is ok.

**Comment by damienmarchal** [comment]
Ready...go 

Thanks Erik for the work done.

**Pull request merged**
