### PR TITLE
[plugins] ADD submodules for ROS, SoftRobots, STLIB

### PR DESCRIPTION
**Pull request by robotsorcerer**
+ Added the submodules that enable the ROS Connector Plugin
  - This includes the submodules for SoftRobot, STLLIB and SofaROSConnector from Fabian Aichele

+ Added a bash script that automates the build with `CMakeLists.txt`

+ Added a Dockerfile for automated debian builds

+ Appended the path to the `FindROS` and `Log4CXX` modules to the root `CMakeLists.txt` file

+ I will be leaving a customized docker build on my [docker repo](https://hub.docker.com/u/lakehanne/sofa)

+ Enough said :100: 

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
Hi @lakehanne, thank you for your PR and welcome to the SOFA community :wave: 

I just retargeted your PR towards sofa-framework:master because it seems that you merged master into your v19.06 so it makes more sense (the diff is now readable).

About the changes you made, we have our own way to include external repositories in SOFA (we don't use git submodules). Please have a look at applications/plugins/SofaHighOrder or applications/projects/Regression.

Moreover, I'm not sure we want to add ROS, SoftRobots and STLIB in SOFA as external repos. This should be discussed with @sofa-framework/reviewers

**Comment by robotsorcerer** [comment]
Ah, gotcha!

**Comment by damienmarchal** [comment]
Hi @lakehanne 

I have the impression that dependency tracking between plugins with only cmake external repo is hard. 

This is why I released a sofa package manager called sofa-spm: https://github.com/SofaDefrost/SPM

**Comment by robotsorcerer** [comment]
Cool tool! Thanks!

**Comment by damienmarchal** [comment]
About sofa-spm, it is possible to submit new plugins install recipes by making PR to https://github.com/SofaDefrost/SPM-RECIPES

**Comment by damienmarchal** [comment]
I close this PR because this is duplicating feature available in SPM.

**Pull request closed without merging**
