### PR TITLE
[SofaSphFluid & SofaMiscCollision] Pluginizing the two modules

### PR DESCRIPTION
**Pull request by damienmarchal**
Module are systematically compiled which have a sensible impact to Sofa. 
I'm moving that into plugin to allow dev to conditionnally activate/deactivate the plugin they 
don't need.

In this PR I'm moving SofaMiscCollision & SofaSphFluid. 
I made the two because there is a dependency between them. 
There should be no big problem with this PR. 
But in the main CMakeList.txt I change the order of subdirectories so that plugins are before scenecreator. 

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
Thank you @damienmarchal  for this nice work as always.
I see you removed all the `typedef` but did not re-defined them in plugins. Won't this break user code?

**Comment by damienmarchal** [comment]
@guparan  
Actually there were not used at all in the sofa code base so I simply remove them. To you have a suggestion about that ?

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
Merged in our STC4 branch

**Comment by epernod** [comment]
ok... I was merging it in master... 1 last conflict and it was done.

**Comment by damienmarchal** [comment]
I'm awafully sorry erik...

It was said in https://github.com/sofa-framework/sofa/pull/429
But forgot to close the PR.

I hope you didn't lose too much time with that.

**Pull request closed without merging**
