### PR TITLE
Fix some of the failing tests for a greener dashboard. 

### PR DESCRIPTION
**Pull request by damienmarchal**
Fix the failing test in
   - MeshROI_test 
   - PluginManager_test
   - in TestMessageHandler remove un-used attribute that was causing a compilation warning in clang
   - in image_test do some cosmetic cleaning to find why it fails... but in fact the problem should be fixed on the CI by installing convert & gm.exe on the VM.  (this is done since this morning)
   - Improve the tests in FixedConstraint_test.
 ______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by fredroy** [comment]
Imagemagick should not be required to read jpeg files ; CImg just needs libjpeg (and -Dcimg_use_jpeg compilation flag).

**Comment by damienmarchal** [comment]
CIMg use convert or gm as a fallback scenario which happens when the plugin is not compiled with libjpeg et libtiff support.

Conclusion 1: we need to update our VM to install libjpeg et libtiff installs on centos & windows. 

Conclusion 2: we need to replace the current error message saying that "convert" or "gm.exe" cannot be found by one explaining that to have jpg/tiff support we need to re-compile the plugin in the right way.

EDIT: thanks @fredroy for the infos about CImg.

**Comment by damienmarchal** [comment]
@matthieu-nesme, @EulalieCoevoet  

I'm trying to fix the test failure in FixConstraint_test when compiled in debug. The failure is related to SparseLDLSolver that do things like that: 
```cpp
     METIS_NodeND(&n, &xadj[0],&adj[0], NULL, NULL, perm,invperm);
``` 
Compiling the test in debug activates the vector bound checking which rise the error message as [0] on an empty vector does not make sense. This error message makes the test fails. 

Compiling the test in release mode de-activates the vector bound checking so the test is not failling anymore. But adj.size() is still zero and adj[0] is still used. According to the standard this is undefined behavior so we need to fix that. 

I made a fix in which I set a minimal size of one to the faulty vectors.... but I'm not sure that having an empty adj vector is not an indication of a deeper problem (or the manifestation of a specific case) and that the right fix should to properly handle this case instead of playing with memory array to "hide" it.   

As you have experience with solvers any feedback would be appreciated.

**Comment by matthieu-nesme** [comment]
Sorry I do not know neither SparseLDLSolver (and the assembled solvers implemented in the sofa core), nor METIS.

If `adj` is a std::vector, I think the safe way to get the raw pointer is `adj.data()`.
(the old-school way: `adj.empty()?null_ptr:&adj[0]`)

**Comment by damienmarchal** [comment]
According to the manual test i started here : 
https://ci.inria.fr/sofa-ci/job/ubuntu_clang-3.8_options-debug/105/consoleFull
It now succeed on all test on the clang_option_debug build. 

So it should be ready !!!

**Pull request merged**
