### PR TITLE
fixing compilation w/o libpng

### PR DESCRIPTION
**Pull request by matthieu-nesme**

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by guparan** [comment]
I guess I merged too fast. This PR breaks `ImagePNG_test.ImagePNG_NoFile`.

**Comment by guparan** [comment]
So apparently `ImagePNG_test.ImagePNG_NoFile` fails when executed **after** `logging_test`.
I don't know Message API enough to understand what is wrong but it seems to be related to `MessageDispatcher::clearHandlers()` calls in `logging_test`.
Any idea @matthieu-nesme @damienmarchal ?

**Comment by damienmarchal** [comment]
Yes I have an idea... 

The problem is probably because currently there is two approaches to interpret the messages send with  the Message API  as test failure.  Fixing should be easily, will do that this evening. 

More in-depth... I think this is a good opportunity to discuss how the component messages are interpreted as test...currently we have two different approaches. 

One of the approach is a global message handler that interprets all errors as test failure. This handler can be "explicitely" deactivated when we don't need this behavior. But if we forgot to do so this behavior propagates to each _test in the same test suite (I think this is what is happening here). 

I found this behavior not precise enough so I develop ExpectMessage & MessageAsTestFailure which are RAII classes to finely select which message generates test failure with the granulary of the RAII
(so it is automatically removed when the RAII is destroy). 
The good point about this approach is that:
   - we can raise test failure for any kind of message (this depend on the test)
   - we can raise test failure is a message is expected but not send (like using a wrong filename must generate a message). 
   - we behavior is only active during the RAII lifetime. 

I don't know if we need to keep them both. What is your opinion ?

**Pull request merged**
