### PR TITLE
[Viewer] FIX draw scenes on classical and retina screens

### PR DESCRIPTION
**Pull request by untereiner**
Tested on classical and retina screens on os x system and classical screen on linux system. I do not know how to create a unit test for this fix.

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by untereiner** [comment]
Apparently the builder on os x links against Qt4. Is this version of Qt mandatory ? The function devicePixelRatio() is only available starting from Qt5.5

**Comment by fredroy** [comment]
I would say that we should drop Qt4 support (Qt5 has been released 5 years ago), and the new GUI will need Qt5.7 anyway....

**Comment by damienmarchal** [comment]
So we probably need to update our CI machines with QT5.7... @bcarrez it is for you :)

EDIT: we cannot merge that before the update of CI.

**Comment by bcarrez** [comment]
trying to update qt without updating the whole system (OSx builder is on OSx 10.9...)

**Comment by bcarrez** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
Ready + 7 days of quarantine....let's merge. 
Thank Lionel/

**Pull request merged**
