### PR TITLE
[SofaCore] Clean RotationMatrix

### PR DESCRIPTION
**Pull request by damienmarchal**
- moves the definition from .h in a .cpp 
- moves RotationMatrix.h and RotationMatrix.cpp in SofaBaseLinearSolver (because this is where it should be according to its dependency to SparseMatrix)

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by fredroy** [comment]
@damienmarchal I came accross the problem of RotationMatrix being in Sofa.Core, whereas all the other *Matrix class were contained into SofaBaseLinearSolver (with a nice include from Sofa.Core to SofaBaseLinearSolver 😗)
Plus the fact that IMO, instead of all the *Matrix being in SofaBaseLinearSolver, I would put all of them into SofaFramework actually. Reasons are that some stuff being not LinearSolver still need SparseMatrix for example, and need a SofaBaseLinearSolver dependency just for it. 
My interrogation would be where exactly in SofaFramework, as BaseMatrix (and BaseVector) being into Sofa.Defaulttype, which is a bit weird. Maybe in Sofa.Type ? or alongside LinearSolver.h in Sofa.Core ?
Could be of interest of @alxbilger as well.
Otherwise we can move RotationMatrix into SofaBaseLinearSolver indeed, to solve the crappy soft dependency.

**Comment by alxbilger** [comment]
Maybe all derived classes from `BaseMatrix` deserve their own module. `Sofa.Matrix` for example.

**Comment by fredroy** [comment]
I even did not see there was an issue on it already: https://github.com/sofa-framework/sofa/issues/2150

**Comment by damienmarchal** [comment]
@fredroy  So Dediced to follow the small step strategy... just move RotationMatrix in SofaBaseLinearSolver for the moment.
For the moment I suggest to keep everything in SofaBaseLinearSolver... as a refactoring of this part would requieres to:
- unify the namespaces to match the modules names
- and if needed to move all the matrices in their proper module (Sofa.Matrix, Sofa.Type).
- and imply a change in a lot of #include everwhere of our code base. 

In addition, after this PR is supposed to be the cleaning or other part of SofaBaseLinearSolver (see #2238)

**Comment by fredroy** [comment]
[ci-build][with-all-tests]

**Review by fredroy — APPROVED** [review]

**Pull request merged**
