### PR TITLE
[sceneutility] Deprecate MakeAlias and MakeDataAlias

### PR DESCRIPTION
**Pull request by alxbilger**
Because it is not used and not useful

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by damienmarchal** [comment]
These two components were added as a tool to smooth the transition between the use of hard-coded alias in our code base to "no alias" at all. The underlying idea was to propose our users, and more specifically the one complaining about the disappearance of the alias they are using, a simple way to restore it (if they don't want to update their complete scene base). 

About the fact is it not used... this is not surprising as we are not removing the aliases as it was planned and when we do it we are updating all the scenes in our code base (removing the need for MakeAlias).

I personally think that the approach proposed in (#PR 2512: https://github.com/sofa-framework/sofa/pull/2512) is much elegant  compared to the MakeAlias (and would advocate to remove MakeAlias when something similar to 2512 is merged) 

In any case  (either with MakeAlias *or* the Import component) hard-coding multiple aliases for a single component in our c++ code is an UX mistake while letting user specify their aliases is an UX feature, so I would be more in favor for having a clear roadmap to remove the aliases.

**Comment by alxbilger** [comment]
Thanks for the clarification @damienmarchal. It makes sense. 
As you said, it's a feature. Therefore, I just want to make sure that this feature is used enough to justify the maintenance cost.
Note that I believed that the feature was also possible with Python, but I don't see it. I would prefer it, compared to a scene component which does not bring anything to the simulation.

**Comment by alxbilger** [comment]
Agreed to keep both components

**Comment by damienmarchal** [comment]
During the coding session it was pointed that it was a "xml" feature. Maybe this could be implemented in the parser (given we want to improve it).

**Pull request closed without merging**
