### PR TITLE
[SofaGeneralObjectInteraction] Remove stiffness multiplicator in SpringForceField

### PR DESCRIPTION
**Pull request by untereiner**
*SpringForceField fixes

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [ ] does not break API compatibility.
- [ ] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by damienmarchal** [comment]
@untereiner , 

I'm concerned about the the impact of the fix against existing scenes. 
So can you explain a bit more what is fixed ? Was it a broken behavior resulting in a failing test or a failling scene or is it fixing a 'yet un-noticed' and fundamentally broken behavior ? 
If the computation is changed, is there any risk to have other people scenes to behave differently ?

**Comment by damienmarchal** [comment]
This PR is now 13 days old, is there any news ?

**Comment by guparan** [comment]
Ping @untereiner

**Comment by untereiner** [comment]
Ok, I have meanly three reasons:
- how explain mechanically that the stiffness is multiplied by a length ?
- there is no test when the length is 0 (almost) (the problem that occured to me)
- when the length is very small you will have a very high stiffness which is different from the stiffness you enterred.

I understand your concerns but I think the behavior is not what expected (at least for the third reason). The existing scenes take maybe into account these strange behavior.

**Comment by damienmarchal** [comment]
I fully agree the change should be done.

I suggest the following approach to warn user there is changes:
- add a Data<bool> "forceOldBehavior" set to false that allow users to keep using the behavior they are used to. 
- when this parameter is not set, print a Warning at init explaining that the behavior have changed and that user that want to use the old behavior should add the parameter "forceOldBehavior=true" to their scene, if user want to remove the warning he need to add "forceOldBehavior=false". 
- when the warning is true or false change  the behavior of the component accordingly.

**Comment by damienmarchal** [comment]
I just submitted a PR to help reporting behavior changes to users. It is in #322 
I have added a hook for "BoxStiffSpringForceField".

**Comment by untereiner** [comment]
That is a great job! It will improve a lot the scene handing!
I can do the requested changes as well if they are still needed.

**Comment by damienmarchal** [comment]
What you can do is to add a Data<bool> forceOldBehavior in the componant to allow users to switch between the two versions and the SceneChecker will manage the warning of users.

**Comment by damienmarchal** [comment]
[ci-build]

**Comment by damienmarchal** [comment]
@hugtalbot Looks ok to me.

**Pull request merged**
