### PR TITLE
[SofaBaseMechanics] Clean barycentric mapping

### PR DESCRIPTION
**Pull request by EulalieCoevoet**
Cleaning and refactoring in BarycentricMapping (only for topology container)

_description from comment below:_

Sure, sorry. So I wanted to optimize the initialization of BarycentricMapping, see issue #784 for clear description of the problem. 

To avoid more duplication of code, and to allow the optimization to be available for a maximum of topology types, I needed the code to be refactored. 

So:

1. I created an abstract class (BarycentricMapperTopologyContainer) that gather the shared implementations of BarycentricMapperEdgeSetTopology, BarycentricMapperTriangleSetTopology, BarycentricMapperQuadSetTopology, BarycentricMapperTetrahedronSetTopology, and BarycentricMapperHexahedronSetTopology.

2. Enabeling to refactor the apply(), applyJ(), applyJT(), getJ(), draw() functions and more importantly the  function I want to optimize, init().

The PR also include some cleaning, in particular the renaming of variables. That could indeed break not updated code. 

What I couldn't do, is to also refactor the code of BarycentricMapperMeshTopology...

______________________________________________________

This PR: 
- [x] builds with SUCCESS for all platforms on the CI.
- [x] does not generate new warnings.
- [x] does not generate new unit test failures.
- [x] does not generate new scene test failures.
- [x] does not break API compatibility.
- [x] is more than 1 week old (or has fast-merge label).

**Reviewers will merge only if all these checks are true.**

### CODE REVIEW

**Comment by guparan** [comment]
Thanks for this massive PR @EulalieCoevoet :+1:

Here is the error output for CentOS build:
```
In file included from /usr/include/boost/intrusive_ptr.hpp:16:
/usr/include/boost/smart_ptr/intrusive_ptr.hpp:68:34: error: use of undeclared identifier 'intrusive_ptr_add_ref'
        if( px != 0 && add_ref ) intrusive_ptr_add_ref( px );
                                 ^
/builds/workspace/sofa-framework/PR-798/centos_clang-3.4_options_release/src/SofaKernel/framework/sofa/core/../../sofa/core/objectmodel/SPtr.h:56:28: note: in instantiation of member function 'boost::intrusive_ptr<sofa::component::mapping::BarycentricMapperEdgeSetTopology<Vec3dTypes, ExtVec3fTypes> >::intrusive_ptr' requested here
    New(Args&& ... args) : SPtr( new T(std::forward<Args>(args)...) ) { }
                           ^
/builds/workspace/sofa-framework/PR-798/centos_clang-3.4_options_release/src/SofaKernel/SofaBase/../modules/SofaBaseMechanics/BarycentricMapping.inl:973:40: note: in instantiation of function template specialization 'sofa::core::objectmodel::New<sofa::component::mapping::BarycentricMapperEdgeSetTopology<Vec3dTypes, ExtVec3fTypes> >::New<sofa::component::topology::EdgeSetTopologyContainer *&, sofa::component::topology::PointSetTopologyContainer *&>' requested here
                            m_mapper = sofa::core::objectmodel::New<EdgeSetMapper>(t5, toTopoCont);
                                       ^
```

SofaCUDA seems also to be a problem on Linux build.

**Comment by guparan** [comment]
Could we have a bit more details about what you did and why you did it please ?

**Comment by EulalieCoevoet** [comment]
Sure, sorry. So I wanted to optimize the initialization of BarycentricMapping, see issue #784 for clear description of the problem. 

To avoid more duplication of code, and to allow the optimization to be available for a maximum of topology types, I needed the code to be refactored. 

So:

1. I created an abstract class (BarycentricMapperTopologyContainer) that gather the shared implementations of BarycentricMapperEdgeSetTopology, BarycentricMapperTriangleSetTopology, BarycentricMapperQuadSetTopology, BarycentricMapperTetrahedronSetTopology, and BarycentricMapperHexahedronSetTopology.

2. Enabeling to refactor the apply(), applyJ(), applyJT(), getJ(), draw() functions and more importantly the  function I want to optimize, init().

The PR also include some cleaning, in particular the renaming of variables. That could indeed break not updated code. 

What I couldn't do, is to also refactor the code of BarycentricMapperMeshTopology...

**Comment by guparan** [comment]
@EulalieCoevoet Hi, do you plan to fix the CUDA errors?

**Comment by EulalieCoevoet** [comment]
So, 
I've fixed the compile problems with SofaCUDA and clang.
And... I went a bit further with the cleaning, by splitting the 11 classes that where in BarycentricMapping files... into dedicated files. I'm convinced It will easy future development...

**Comment by EulalieCoevoet** [comment]
Hi guys, 
I have trouble fixing the windows CI... if someone could help, it would be great (@epernod ).

**Comment by damienmarchal** [comment]
The compilation problem appears between 7b183a2 and aeb4f8.

**Comment by damienmarchal** [comment]
@EulalieCoevoet I got the problem. It was because you added SOFA_BASE_MECHANICS_API to the mapper. I suspect the problem is that when you specialize the template in a different dll (like the rigid that is in miscmapping) tthe specialization is of course using SOFA_MISC_MAPPING_API while the base class is using SOFA_BASE_MECHANICS_API.

**Comment by EulalieCoevoet** [comment]
Thanks @damienmarchal !

**Comment by guparan** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
@EulalieCoevoet 
Thanks for this PR. Just for the record, why ?
`What I couldn't do, is to also refactor the code of BarycentricMapperMeshTopology...`

**Review by epernod — APPROVED** [review]

**Comment by EulalieCoevoet** [comment]
@epernod lack of time... I guess it wasn't straightforward and I didn't want to spend more time on it.

**Pull request merged**
