### PR TITLE
[SofaSimulationCore] Remove unused InitPerThreadDataTask

### PR DESCRIPTION
**Pull request by alxbilger**
InitPerThreadDataTask is not used. I suggest to remove it.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
It appears the only place where `InitPerThreadDataTask` is used is in the global function `initThreadLocalData`, which is used in  `AnimationLoopParallelScheduler`. Therefore, I cannot remove this piece of code.

**Comment by fredroy** [comment]
> 
> 
> It appears the only place where `InitPerThreadDataTask` is used is in the global function `initThreadLocalData`, which is used in `AnimationLoopParallelScheduler`. Therefore, I cannot remove this piece of code.

Seems that InitTasks.h is also used by GenericConstraintSolver. Should be close this PR ?

**Comment by alxbilger** [comment]
> Seems that InitTasks.h is also used by GenericConstraintSolver.

There is no reason to include `InitTasks.h` in GenericConstraintSolver. I'll make another PR to remove it.

I agree to close this PR

**Comment by alxbilger** [comment]
https://github.com/sofa-framework/sofa/pull/2266

**Pull request closed without merging**
