### PR TITLE
[Type] Conversion to scalar for Mat1x1

### PR DESCRIPTION
**Pull request by alxbilger**
Explicit and implicit conversion to scalar are introduced for matrices 1x1. Unit tests are added.

______________________________________________________

By submitting this pull request, I acknowledge that  
**I have read, understand, and agree [SOFA Developer Certificate of Origin (DCO)](https://github.com/sofa-framework/sofa/blob/master/CONTRIBUTING.md#sofa-developer-certificate-of-origin-dco)**.
______________________________________________________

**Reviewers will merge this pull-request only if**  
- it builds with SUCCESS for all platforms on the CI.
- it does not generate new warnings.
- it does not generate new unit test failures.
- it does not generate new scene test failures.
- it does not break API compatibility.
- it is more than 1 week old (or has fast-merge label).

### CODE REVIEW

**Comment by alxbilger** [comment]
[ci-build][with-all-tests]

**Comment by epernod** [comment]
In which case is a Mat1x1 used instead of a Real?

**Comment by alxbilger** [comment]
> In which case is a Mat1x1 used instead of a Real?

[Here](https://github.com/sofa-framework/sofa/blob/9234b0885ae2686660f1ae737f7ff0a387134ba6/Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/StiffSpringForceField.h#L71). The size of Mat depends on DataTypes, which can be Vec1d.

**Comment by epernod** [comment]
> > In which case is a Mat1x1 used instead of a Real?
> 
> [Here](https://github.com/sofa-framework/sofa/blob/9234b0885ae2686660f1ae737f7ff0a387134ba6/Sofa/Component/SolidMechanics/Spring/src/sofa/component/solidmechanics/spring/StiffSpringForceField.h#L71). The size of Mat depends on DataTypes, which can be Vec1d.

ok why not... 🚀 🧑‍🔬 
as we said it is: 🍆 🪰

**Review by epernod — APPROVED** [review]

**Review by fredroy — APPROVED** [review]

**Pull request merged**
